# Aufgabenblatt 5: Datenbearbeitung

importiere folgende Bibliotheken:
- pandas as pd
- numpy as np
- import random

## Aufgabe 1: Slicing
### a) auf Listen
- erstelle eine Liste `slice_list` 
- mit den Werten von 1 bis 30, erstelle die Liste `nicht` manuell

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

- Verwenden die Slicing-Notation, um jedes `zweite` Element aus dieser Liste auszuwählen und in einer neuen Liste zu speichern. 
- Gebe sowohl die ursprüngliche Liste als auch die neue Liste aus.

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29]

- Verwenden die Slicing-Notation mit dem `Startindex 1` und der `Schrittweite 2`, um eine neue Liste namens jedes_zweite_element_ab_index_eins zu erstellen
- (gebe edes `zweite` Element startend mit dem `zweiten` Element)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]

- Verwenden die Slicing-Notation und selektiere auf den Bereich von den Elementen `5-13` 
- und gebe nur jedes `dritte` Element in der neuen Liste aus

[5, 8, 11]

- gebe mittels Slicing-Notation nur die letzten `vier` Elemente aus

[27, 28, 29, 30]

- Verwende die Slicing-Notation. Das Slicing soll beim `fünften` Element starten und beim `vorletzen` Element der  Liste enden
- und zeige nur jedes `vierte` Element an in der neuen Liste

[5, 9, 13, 17, 21, 25, 29]

### b) verändere Werte mittels Slice 
- verwende die `slice_liste` aus Aufgabe `a`
- nun überschreibe die Werte `28` aus der `slice_liste` mittels slice auf den neuen Wert `40`

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 40, 29, 30]

- nun überschreibe mehrerer nacheinanderfolgende Werte 
- die Werte `10,11,12` in der `slice_liste` sollen mittels slice durch `41,42,43` ersetzt werden

[1, 2, 3, 4, 5, 6, 7, 8, 9, 41, 42, 43, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 40, 29, 30]

### c) Slice auf String
- erstelle den String Satz: `Das ist ein langer Satz zum Testen für das slicen in Strings.`

Das ist ein langer Satz zum Testen für das slicen in Strings.

gebe aus dem String Satz folgendes aus
- Das erste Ausgegebene Element ist das `8` Element 
- Es soll jedes `dritte` Element ausgegeben werden
- Die Liste soll bis auf das `vorletzte` Element geslicet werden
<br> <br> **Lösung** 'e nra meef sleiSis'

'e nra meef sleiSis'

- gebe aus dem String Satz das Wort `Satz` aus
- um das Wort zu bestimmen, sollst du nicht manuell Zählen. Eine Idee ist das verwenden eines for loops
- wenn du jedem Stringelement einen Index zu geordnet hast, kannst du das Wort `Satz` mittels Slicen ausgeben.

0 D
1 a
2 s
3
4 i
5 s
6 t
7
8 e
9 i
10 n
11
12 l
13 a
14 n
15 g
16 e
17 r
18
19 S
20 a
21 t
22 z
23
24 z
25 u
26 m
27
28 T
29 e
30 s
31 t
32 e
33 n
34
35 f
36 ü
37 r
38
39 d
40 a
41 s
42
43 s
44 l
45 i
46 c
47 e
48 n
49
50 i
51 n
52
53 S
54 t
55 r
56 i
57 n
58 g
59 s
60 .

'Satz'

### d) slicen auf einen Dataframe 

- der df_slice wird bei jedem ausführen des Codes anders aussehen, weil er zufällige Werte erstellt. Dies hat Auswirkungen auf die Lösungen. Die angezeigten Lösungen können nicht identisch sein mit euren Ausgaben

In [ ]:
# der Parameter size bestimmt die Anzahl der rows und Columns
# der Parameter columns gibt die einzelnen Column namen wieder
df_slice = pd.DataFrame(np.random.randint(1,6, size=(15, 4)), columns=list('ABCD'))
df_slice

    A  B  C  D
0   1  5  1  3
1   1  4  4  2
2   5  2  4  4
3   3  4  2  2
4   2  3  4  3
5   5  2  1  4
6   2  5  2  4
7   3  2  2  4
8   1  2  4  3
9   4  1  1  3
10  2  2  5  1
11  3  2  5  4
12  5  4  3  4
13  1  1  3  5
14  4  1  3  1

- zeige mittels der `head` Funktion die ersten `3` rows vom DataFrame `df_slice` an

   A  B  C  D
0  1  5  1  3
1  1  4  4  2
2  5  2  4  4

- verwende die Slicing-Notation und gebe aus dem DataFrame `df_slice` die rows (records) auf Indexebene `3-5` wieder

   A  B  C  D
2  5  2  4  4
3  3  4  2  2
4  2  3  4  3

- verwende die Slicing-Notation und gebe aus dem DataFrame `df_slice` allle Records wieder, 
- welche in dem Indexbereich von `1-8` (rows) sind und 
- gebe nur jeden `zweiten` Wert aus

   A  B  C  D
1  1  4  4  2
3  3  4  2  2
5  5  2  1  4
7  3  2  2  4

- verwende die Slicing-Notation auf den Dataframe `df_slice` 
- Slice von der `ersten` row bis einschliesslich der `fünften` row
- neben dem slicen auf der row ebene selektiere dabei die columns `B` und `D` mittels slicing

   B  D
0  5  3
2  2  4
4  3  3

- slice nun den Dataframe `df_slice` auf die columns von `B bis D`

    B  C  D
0   5  1  3
1   4  4  2
2   2  4  4
3   4  2  2
4   3  4  3
5   2  1  4
6   5  2  4
7   2  2  4
8   2  4  3
9   1  1  3
10  2  5  1
11  2  5  4
12  4  3  4
13  1  3  5
14  1  3  1

### e)  Selektion auf Werte in einem Dataframe
- erstelle aus den Dataframe `df_slice` einen eigenen Sub-Dataframe, 
- welcher die Selektionskriterien in der column `A` gleich `2` ist

    A  B  C  D
4   2  3  4  3
6   2  5  2  4
10  2  2  5  1

- erstelle aus den Dataframe `df_slice` einen eigenen Sub-Dataframe, 
- welcher die Selektionskriterien in der column `A` gleich `2` oder `4` ist

    A  B  C  D
4   2  3  4  3
6   2  5  2  4
9   4  1  1  3
10  2  2  5  1
14  4  1  3  1

- erstelle aus den Dataframe `df_slice` einen eigenen Sub-Dataframe, 
- welcher die Selektionskriterien in der column `A` gleich `3` und  `B` gleich `5` hat

   A  B  C  D
6  2  5  2  4

kennst du noch eine andere Schreibweise? für die Aufgabe: 
- erstelle aus den Dataframe `df_slice` ein Sub-Dataframe, 
- welcher die Selektionskriterien in der column `B` gleich `2` oder `4` ist
<br> **Tipp:** etwas ist in etwas enthalten --> eine python Funktion

    A  B  C  D
1   1  4  4  2
2   5  2  4  4
3   3  4  2  2
5   5  2  1  4
7   3  2  2  4
8   1  2  4  3
10  2  2  5  1
11  3  2  5  4
12  5  4  3  4

- erstelle den Dataframe df_slice mit anderen Columnnamen: wie z.B. 
    - AB
    - CD
    - EF
    - GH

    AB  CD  EF  GH
0    2   1   2   1
1    2   3   1   4
2    1   3   1   5
3    1   2   3   1
4    2   3   4   4
5    4   4   1   1
6    2   5   5   5
7    2   1   2   5
8    4   4   2   4
9    5   2   3   1
10   5   3   1   4
11   4   2   5   4
12   2   2   3   3
13   5   2   3   3
14   1   2   2   2

## Aufgabe 2: allgemeine Datenbearbeitung
### a) erweiteren und bearbeiten des DataFrames aus der Aufgabe `1d)`
- reduziere den DataFrame `df_slice` auf die Columns `A` und `B`, 
- sowie die ersten `10` Rows und nenne den neuen DataFrame `work_df`

   A  B
0  1  5
1  1  4
2  5  2
3  3  4
4  2  3
5  5  2
6  2  5
7  3  2
8  1  2
9  4  1

- nenne die Columns im Datframes `work_df` um:
    - `A` in `VALUE_1` und 
    - `B` in `VALUE_2`

   VALUE_1  VALUE_2
0        1        5
1        1        4
2        5        2
3        3        4
4        2        3
5        5        2
6        2        5
7        3        2
8        1        2
9        4        1

- füge dem Dataframe `work_df` eine neue Column hinzu
- die Column soll den Namen `GERADE_DIV` haben
- die Column `GERADE_DIV` besteht nur aus dem Wert `2`

   VALUE_1  VALUE_2  GERADE_DIV
0        1        5           2
1        1        4           2
2        5        2           2
3        3        4           2
4        2        3           2
5        5        2           2
6        2        5           2
7        3        2           2
8        1        2           2
9        4        1           2

- erweitere den DataFrame `work_df` um eine neue Column
- kopiere die Column `VALUE_1` mit allen seinen Werten in eine neue Column mit dem Namen `COPY_VALUE_1`

   VALUE_1  VALUE_2  GERADE_DIV  COPY_VALUE_1
0        1        5           2             1
1        1        4           2             1
2        5        2           2             5
3        3        4           2             3
4        2        3           2             2
5        5        2           2             5
6        2        5           2             2
7        3        2           2             3
8        1        2           2             1
9        4        1           2             4

löschen vom Columns 
- lösche die Column `VALUE_1` aus dem Dataframe `work_df`

   VALUE_2  GERADE_DIV  COPY_VALUE_1
0        5           2             1
1        4           2             1
2        2           2             5
3        4           2             3
4        3           2             2
5        2           2             5
6        5           2             2
7        2           2             3
8        2           2             1
9        1           2             4

erstellen einer neuen berechneten Column in den DataFrame
- die neue Column soll den Wert von `COPY_VALUE_1` mit dem Wert von `VALUE_2` subtrahieren
- schreibe das Ergebnis in eine neue Column mit den Namen `SUB_ERGEBNIS` in den Dataframe `work_df`

   VALUE_2  GERADE_DIV  COPY_VALUE_1  SUB_ERGEBNIS
0        5           2             1            -4
1        4           2             1            -3
2        2           2             5             3
3        4           2             3            -1
4        3           2             2            -1
5        2           2             5             3
6        5           2             2            -3
7        2           2             3             1
8        2           2             1            -1
9        1           2             4             3

- entferne nun alle duplicate in dem ganzen Dataframe `work_df` 
<br><br> **ACHTUNG** `auch wenn dein work_df keine Doubletten hat`

   VALUE_2  GERADE_DIV  COPY_VALUE_1  SUB_ERGEBNIS
0        5           2             1            -4
1        4           2             1            -3
2        2           2             5             3
3        4           2             3            -1
4        3           2             2            -1
6        5           2             2            -3
7        2           2             3             1
8        2           2             1            -1
9        1           2             4             3

- entferne nun alle duplicate, auf den Columns `VALUE_2` und `GERADE_DIV` aus dem ganzen Dataframe `work_df` 
- behalte beim löschen den `letzten` Eintrag, von allen gleichen duplizierenden Einträgen

   VALUE_2  GERADE_DIV  COPY_VALUE_1  SUB_ERGEBNIS
3        4           2             3            -1
4        3           2             2            -1
6        5           2             2            -3
8        2           2             1            -1
9        1           2             4             3

- erstelle für den Dataframe `work_df` einen neuen `Index` beginnend bei 0

   index  VALUE_2  GERADE_DIV  COPY_VALUE_1  SUB_ERGEBNIS
0      3        4           2             3            -1
1      4        3           2             2            -1
2      6        5           2             2            -3
3      8        2           2             1            -1
4      9        1           2             4             3

- erstelle die Summe (über alle Columns) in einer neuen Column mit dem Namen `SUM` in Dataftrane `work_df`

   index  VALUE_2  GERADE_DIV  COPY_VALUE_1  SUB_ERGEBNIS  SUM
0      3        4           2             3            -1   11
1      4        3           2             2            -1   10
2      6        5           2             2            -3   12
3      8        2           2             1            -1   12
4      9        1           2             4             3   19

- gebe für die  Column `SUM` im Dataftrane `work_df` jeweils den `minmalen` Wert und den `maximalen` Wert aus

19
10

- gebe die Mittelwerte für `alle` Columns aus dem Dataframe `work_df`

index            6.0
VALUE_2          3.0
GERADE_DIV       2.0
COPY_VALUE_1     2.4
SUB_ERGEBNIS    -0.6
SUM             12.8
dtype: float64

veränder den Index erneut
- Die Column `SUM` soll der neue Index im Dataftrane `work_df` sein
- Des Weiteren soll die Column `index` gelöscht werden

     VALUE_2  GERADE_DIV  COPY_VALUE_1  SUB_ERGEBNIS
SUM
11         4           2             3            -1
10         3           2             2            -1
12         5           2             2            -3
12         2           2             1            -1
19         1           2             4             3

- erstelle eine neue Column namens `ROUND` im Dataftrane `work_df`
- in der Columns `ROUND` sollen die Column `VALUE_2` durch `COPY_VALUE_1` dividiert werden und 
- das Ergebnis soll auf 3 `Nachkommastellen` gerundet werden

     VALUE_2  GERADE_DIV  COPY_VALUE_1  SUB_ERGEBNIS  ROUND
SUM
11         4           2             3            -1  1.333
10         3           2             2            -1  1.500
12         5           2             2            -3  2.500
12         2           2             1            -1  2.000
19         1           2             4             3  0.250

- erstelle eine neue Column namens `POTENZ` im Dataftrane `work_df`
- in der Columns `POTENZ` sollen die jeweiligen Potenzen von `VALUE_2` auf `COPY_VALUE_1` berechnet werden
- das Ergebnis soll hierbei auf 1 Stelle `vor` dem Komma gerundet werden.

     VALUE_2  GERADE_DIV  COPY_VALUE_1  SUB_ERGEBNIS  ROUND  POTENZ
SUM
11         4           2             3            -1  1.333      60
10         3           2             2            -1  1.500      10
12         5           2             2            -3  2.500      20
12         2           2             1            -1  2.000       0
19         1           2             4             3  0.250       0

- zähle und gebe alle verschiedenen Ausprägungen von `COPY_VALUE_1` im Dataftrane `work_df` aus
<br><br> **value_counts**

COPY_VALUE_1
2    2
3    1
1    1
4    1
Name: count, dtype: int64

- gebe den Dataftrane `work_df` gedreht aus

SUM               11    10    12   12    19
VALUE_2        4.000   3.0   5.0  2.0  1.00
GERADE_DIV     2.000   2.0   2.0  2.0  2.00
COPY_VALUE_1   3.000   2.0   2.0  1.0  4.00
SUB_ERGEBNIS  -1.000  -1.0  -3.0 -1.0  3.00
ROUND          1.333   1.5   2.5  2.0  0.25
POTENZ        60.000  10.0  20.0  0.0  0.00

### b) Allgemeine Datenanalyse von unbekannten Datensätzen

Für die Übung wurde ein Maschine Learning Datensatz "Wine" von sklearn verwendet

In [46]:
from sklearn.datasets import load_wine
# Laden der Externen Daten
wine_data = load_wine()
wine = pd.DataFrame(wine_data.data, columns=wine_data.feature_names)
wine.head(3)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0

- bestimme die Grösse des DataFrames `wine`
- Anzal der rows und der Columns mit einem Standardaufruf

(178, 13)

- gebe alle Columnnamen des Datafranes `wine` an mit einem Standardaufruf

Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline'],
      dtype='object')

- finde heraus welche `Datentypen` und wie viele `NaN` Werte es zu den jeweiligen Columns im Dataframe `wine` gibt

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
dtypes: float64(13)
memory usage: 18.2 KB

- beschreibe den Dataframe `wine` und gebe die verschiedenen mathematischen Funktion wie z.B. `count`, `mmean`,`max`, `min`, `std`, `25%`, `50%` und `75%` für alle Columns wieder

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000

### c) bearbeiten des Datensatzes `wine`
- alle Columnnamen in dem Dataframe `wine` sollen grossgeschrieben werden
    - verwende eine Funktion, dass es automatisch für alle Einträge funktioniert --> es soll nicht **manuell** erstellt werden
- des weiteren sollen die Zeichen `/` soll mittels `_` ersetzt werden

,ALCOHOL,MALIC_ACID,ASH,ALCALINITY_OF_ASH,MAGNESIUM,TOTAL_PHENOLS,FLAVANOIDS,NONFLAVANOID_PHENOLS,PROANTHOCYANINS,COLOR_INTENSITY,HUE,OD280_OD315_OF_DILUTED_WINES,PROLINE
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

- sortiere die Werte der Column `ALCOHOL` in dem Dataframe `wine` 
- Die Sortierung soll absteigend durch geführt werden

,ALCOHOL,MALIC_ACID,ASH,ALCALINITY_OF_ASH,MAGNESIUM,TOTAL_PHENOLS,FLAVANOIDS,NONFLAVANOID_PHENOLS,PROANTHOCYANINS,COLOR_INTENSITY,HUE,OD280_OD315_OF_DILUTED_WINES,PROLINE
8,14.83,1.64,2.17,14.0,97.0,2.80,2.98,0.29,1.98,5.20,1.08,2.85,1045.0
13,14.75,1.73,2.39,11.4,91.0,3.10,3.69,0.43,2.81,5.40,1.25,2.73,1150.0
6,14.39,1.87,2.45,14.6,96.0,2.50,2.52,0.30,1.98,5.25,1.02,3.58,1290.0
46,14.38,3.59,2.28,16.0,102.0,3.25,3.17,0.27,2.19,4.90,1.04,3.44,1065.0
14,14.38,1.87,2.38,12.0,102.0,3.30,3.64,0.29,2.96,7.50,1.20,3.00,1547.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,11.56,2.05,3.23,28.5,119.0,3.18,5.08,0.47,1.87,6.00,0.93,3.69,465.0
110,11.46,3.74,1.82,19.5,107.0,3.18,2.58,0.24,3.58,2.90,0.75,2.81,562.0
120,11.45,2.40,2.42,20.0,96.0,2.90,2.79,0.32,1.83,3.25,0.80,3.39,625.0
113,11.41,0.74,2.50,21.0,88.0,2.48,2.01,0.42,1.44,3.08,1.10,2.31,434.0
115,11.03,1.51,2.20,21.5,85.0,2.46,2.17,0.52,2.01,1.90,1.71,2.87,407.0

- erstelle einen neuen Dataframe `sub_wine` aus dem Dataframe `wine`
- in dem Dataframe `sub_wine` sollen nur `Werte zwischen 12.34 und 13.56` in der Column `ALCOHOL` enthalten sein
<br><br> 84 rows

84

,ALCOHOL,MALIC_ACID,ASH,ALCALINITY_OF_ASH,MAGNESIUM,TOTAL_PHENOLS,FLAVANOIDS,NONFLAVANOID_PHENOLS,PROANTHOCYANINS,COLOR_INTENSITY,HUE,OD280_OD315_OF_DILUTED_WINES,PROLINE
40,13.56,1.71,2.31,16.2,117.0,3.15,3.29,0.34,2.34,6.13,0.95,3.38,795.0
55,13.56,1.73,2.46,20.5,116.0,2.96,2.78,0.20,2.45,6.25,0.98,3.03,1120.0
142,13.52,3.17,2.72,23.5,97.0,1.55,0.52,0.50,0.55,4.35,0.89,2.06,520.0
34,13.51,1.80,2.65,19.0,110.0,2.35,2.53,0.29,1.54,4.20,1.10,2.87,1095.0
150,13.50,3.12,2.62,24.0,123.0,1.40,1.57,0.22,1.25,8.60,0.59,1.30,500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,12.37,1.21,2.56,18.1,98.0,2.42,2.65,0.37,2.08,4.60,1.19,2.30,678.0
63,12.37,1.13,2.16,19.0,87.0,3.50,3.10,0.19,1.87,4.45,1.22,2.87,420.0
98,12.37,1.07,2.10,18.5,88.0,3.52,3.75,0.24,1.95,4.50,1.04,2.77,660.0
160,12.36,3.83,2.38,21.0,88.0,2.30,0.92,0.50,1.04,7.65,0.56,1.58,520.0
102,12.34,2.45,2.46,21.0,98.0,2.56,2.11,0.34,1.31,2.80,0.80,3.38,438.0

In [54]:
# Alternative

84

- erstelle einen neuen Dataframe `sub_wine_alc_color` aus dem Dataframe `sub_wine`
- welcher nur aus den beiden Columns `ALCOHOL` und `COLOR_INTENSITY` bestehen soll

     ALCOHOL  COLOR_INTENSITY
40     13.56             6.13
55     13.56             6.25
142    13.52             4.35
34     13.51             4.20
150    13.50             8.60
..       ...              ...
65     12.37             4.60
63     12.37             4.45
98     12.37             4.50
160    12.36             7.65
102    12.34             2.80

[84 rows x 2 columns]