# Aufgabenblatt 6: Pandas

importiere die folgenden Bibliotheken
- pandas
- numpy
- random
- string

## Aufgabe 1: Erstelle einen eigenen Dataframe
### a) Dataframe erstellen mit manueller Eingabe

erstelle einen DataFrame `data_1a` mit den Kennzahlen:
- Column `column_string_1` mit *'String_1', 'String_2', 'Stirng_3'*
- Column `column_mix` mit *'rot', 'rot', 'blau'*
- Column `column_int` mit *1, 2, 2002*
- Column `column_float` mit *1.5, 1.7, 1.9*

  column_string  column_int  column_float column_mix
0      String_1           1           1.5        rot
1      String_2           2           1.7        rot
2      Stirng_3        2002           1.9       blau

### b) Dateframe erstellen mit zufälligen und automatisch hinzugefügten Werten

Erstelle einen Dataframe `data_1b`
- der Dataframe hat `4` Columns mit jeweils `100` rows
- der Dataframe hat die Column `column_string` mit *2 zufälligen Buchstaben pro Eintrag*
- der Dataframe hat die Column `column_string_2` mit *gebe zufällig den Werten **rot** und **Blau** und 
    - der Wert rot soll 75% der Ausprägungen haben*
- der Dataframe hat die Column `column_int` mit *zufälligen Werte im Bereich von 1 bis 10*
- der Dataframe hat die Column `column_float` mit *zufällige Werte zwischen -100.00 und 100.00*
<br> <br>*Tipp:* 
- random.choice, string.ascii_lowercase, uniform

   column_string column_string_2  column_int  column_float
0             wj             rot           4     12.264240
1             dw             rot           8    -22.338146
2             he             rot           9    -71.349358
3             ya             rot           4    -42.602488
4             mc            blau           1      9.522221
..           ...             ...         ...           ...
95            on            blau           7     96.107823
96            lw             rot           4    -49.719491
97            jk             rot           7    -38.714862
98            pe             rot           7    -70.108214
99            ah             rot           3     58.870703

[100 rows x 4 columns]

## Aufgabe 2: verbinden von DataFrames

führe die beiden Dataframes `data_1a` und `data_1c` (alle Einträge) zusammen:
- die join/merge Parameter Column ist gleich der Column int `column_int`,
- verwende die Funktion `merge` und verwende für die Übungszwecke die verschiedenen Parameter:
    1. gebe an aus welchem Dataframe kommt der Eintrag
    2. wenn Columnnamen in beiden Dataframes vorkommen, sollen diese mit rechts und links erweitert werden

<br> 101 rows × 8 columns

,column_string_left,column_int,column_float_left,column_mix,column_string_right,column_string_2,column_float_right,_merge
0,String_1,1,1.5,rot,mc,blau,9.522221,both
1,String_1,1,1.5,rot,la,rot,-51.431241,both
2,String_1,1,1.5,rot,ko,rot,13.556171,both
3,String_1,1,1.5,rot,ug,blau,62.475491,both
4,String_1,1,1.5,rot,gh,blau,-29.888094,both
...,...,...,...,...,...,...,...,...
96,NaN,6,NaN,NaN,pn,rot,76.958133,right_only
97,NaN,6,NaN,NaN,ic,rot,-50.164764,right_only
98,NaN,6,NaN,NaN,lc,blau,48.630532,right_only
99,NaN,6,NaN,NaN,co,rot,-58.097003,right_only
100,NaN,6,NaN,NaN,cs,rot,-6.214702,right_only

## Aufgabe 3: Datenimport  und Datenaufbereitung
### a) import von csv und excel Datein
- importiere die csv Datei `2023`
- bestimme die folgenden Parameter, sodass die Datei richtig gelesen werden kann:
    - header
    - seperator
    - encoding

,Unnamed: 0,Getränk,Region,Bestellnummer,Rechnungsnummer,Kundennummer,Listenpreis,Rabatt in Prozent,Verkaufspreis,Rabatt Preis,Einkaufpreis,VK Peris in USD
0,205,Whisky,USA,5645.0,RE_2023_5645,16.0,128.95,5.0,128.95,-6.01,n96.71,131.76
1,8920,Whisky,EU,7994.0,RE_2023_7994,193.0,132.81,5.0,n132.81,-6.64,99.61,135.71
2,4116,Whisky,USA,3190.0,RE_2023_3190,126.0,216.21,0.0,216.21,0.00,162.16,232.56
3,1716,Whisky,USA,790.0,RE_2023_790,171.0,172.13,0.0,172.13,0.00,129.1,185.14
4,10901,Rum,USA,9975.0,RE_2023_9975,41.0,128.73,0.0,128.73,0.00,96.55,138.46
...,...,...,...,...,...,...,...,...,...,...,...,...
10922,5585,Whisky,Asien,4659.0,RE_2023_4659,267.0,81.34,0.0,81.34,0.00,61.0,87.49
10923,6251,Wein,EU,5325.0,RE_2023_5325,253.0,224.05,0.0,224.05,0.00,168.04,240.99
10924,10719,Whisky,USA,9793.0,RE_2023_9793,152.0,149.56,0.0,149.56,0.00,112.17,160.87
10925,6407,Wein,EU,5481.0,RE_2023_5481,19.0,213.35,0.0,213.35,0.00,160.01,229.48
10926,3449,Whisky,USA,2523.0,RE_2023_2523,114.0,163.30,0.0,163.3,0.00,122.48,175.65

- importiere alle sheets aus der Excel_Datei Datei `before_2023` und speicher diese in einzelne DatFrames

### b) Datenaufbereitung des Dataframes `2023`
- schaue dir den neuen Datensatz an? 
-   beschreibe die Grösse des Datensatz (rows/records und columns)

(10927, 12)

- bestimme die mathematischen Werte wie z.B. `count`, `mmean`,`max`, `min`, `std`, `25%`, `50%` und `75%` des Datensatzes

,Unnamed: 0,Bestellnummer,Kundennummer,Listenpreis,Rabatt in Prozent,Rabatt Preis,VK Peris in USD
count,10927.00000,10919.000000,10926.000000,10914.000000,10914.000000,10926.000000,10926.000000
mean,5463.00000,5032.738896,149.100037,155.527156,1.273594,-2.014615,165.138933
std,3154.49753,2906.072110,85.848563,43.382146,2.698154,4.491946,46.296567
min,0.00000,0.000000,1.000000,80.020000,0.000000,-44.540000,71.000000
25%,2731.50000,2516.500000,75.000000,118.160000,0.000000,0.000000,125.230000
50%,5463.00000,5033.000000,149.000000,156.480000,0.000000,0.000000,165.845000
75%,8194.50000,7548.500000,223.000000,192.832500,0.000000,0.000000,204.845000
max,10926.00000,10079.000000,299.000000,246.620000,10.000000,0.000000,264.780000

- erhalte die allgemeinen Informationen zum Datensatz wie z.B. Null-Werte, Datentypen, Columnnamen

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10927 entries, 0 to 10926
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         10927 non-null  int64
 1   Getränk            10912 non-null  object
 2   Region             10924 non-null  object
 3   Bestellnummer      10919 non-null  float64
 4   Rechnungsnummer    10918 non-null  object
 5   Kundennummer       10926 non-null  float64
 6   Listenpreis        10914 non-null  float64
 7   Rabatt in Prozent  10914 non-null  float64
 8   Verkaufspreis      10914 non-null  object
 9   Rabatt Preis       10926 non-null  float64
 10  Einkaufpreis       10899 non-null  object
 11  VK Peris in USD    10926 non-null  float64
dtypes: float64(6), int64(1), object(5)
memory usage: 1.0+ MB

- schaue dir nur die esten 5 Einträge an

,Unnamed: 0,Getränk,Region,Bestellnummer,Rechnungsnummer,Kundennummer,Listenpreis,Rabatt in Prozent,Verkaufspreis,Rabatt Preis,Einkaufpreis,VK Peris in USD
0,205,Whisky,USA,5645.0,RE_2023_5645,16.0,128.95,5.0,128.95,-6.01,n96.71,131.76
1,8920,Whisky,EU,7994.0,RE_2023_7994,193.0,132.81,5.0,n132.81,-6.64,99.61,135.71
2,4116,Whisky,USA,3190.0,RE_2023_3190,126.0,216.21,0.0,216.21,0.00,162.16,232.56
3,1716,Whisky,USA,790.0,RE_2023_790,171.0,172.13,0.0,172.13,0.00,129.1,185.14
4,10901,Rum,USA,9975.0,RE_2023_9975,41.0,128.73,0.0,128.73,0.00,96.55,138.46

- die Column `Verkaufspreis` und `Einkaufpreis` sollen nur aus Zahlen bestehen und den Datentyp **float** besitzen
- entferne die Buchstaben und erstelle einen neuen Dataframe mit Float Werten in den beiden Columns
    - Fehler im Datenframe drüber sind: 
        - `Verkaufspreis` - row 1
        - `Einkaufspreis` - row 0
<br><br> **Tipp** manuelle Lösung mittels replace z.B.

,Unnamed: 0,Getränk,Region,Bestellnummer,Rechnungsnummer,Kundennummer,Listenpreis,Rabatt in Prozent,Verkaufspreis,Rabatt Preis,Einkaufpreis,VK Peris in USD
0,205,Whisky,USA,5645.0,RE_2023_5645,16.0,128.95,5.0,128.95,-6.01,96.71,131.76
1,8920,Whisky,EU,7994.0,RE_2023_7994,193.0,132.81,5.0,132.81,-6.64,99.61,135.71

**FORTGESCHRITTEN** 
- löse das Problem aus der Zelle vorher nun jeweils generisch
- sodass die Buchstaben in den beiden Columns `Verkaufspreis` und `Einkaufpreis` entfernen kannst
<br><br>
**Tipp** 
- verwende u.a. regex
    - r'\D' funktioniert nicht, weil es nur Zahlen zurücklässt 
    - '\d+' funktioniert nicht, weil nur Zahlen gelöscht werden

,Unnamed: 0,Getränk,Region,Bestellnummer,Rechnungsnummer,Kundennummer,Listenpreis,Rabatt in Prozent,Verkaufspreis,Rabatt Preis,Einkaufpreis,VK Peris in USD
0,205,Whisky,USA,5645.0,RE_2023_5645,16.0,128.95,5.0,128.95,-6.01,96.71,131.76
1,8920,Whisky,EU,7994.0,RE_2023_7994,193.0,132.81,5.0,132.81,-6.64,99.61,135.71

Verändere alle Columnnamen. Es sollen die Colummnamen wie folgt angepasst werden: 
- Namen bestehen nur aus `Grossbuchtaben`
- Leerzeichen werden durch `_` ersetzt
- Sonderzeichen sollen angepasst werden in z.B. ö zu oe usw.
- die Column `Unnamed: 0` wird gelöscht
<br><br> rows 10.927

10927

- entferne die möglichen Doubletten in den Daten
<br><br> rows 10.303

10303

- entferne alle `null` rows
- also Einträge auf row Ebene, welchen keinen Werte beinhalten -> in der gesamten Reihe
<br><br> rows 10.302

10302

- Gibt es in den Daten Einträge ohne Rechnungsnummer? 
    - Wenn ja wie viele Einträge sind es?

In [17]:
data_2023_neu.RECHNUNGSNUMMER.isna().value_counts()

RECHNUNGSNUMMER
False    10294
True         9
Name: count, dtype: int64

- Können Einträge ohne Rechnungsnummer nachträglich logisch abgeleitet werden aus den Daten
    - wenn ja bitte befülle die Rechnungsnummerngebe die `NaN` Werte in einem eigenen Dataframe an, 
    - um die Frage der Befüllung der Rechnungsnummer besser zu beantworten gebe die `NaN` Werte in einem eigenen Dataframe an

,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD
1208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2171,Whisky,NaN,10078.0,NaN,54.0,NaN,5.0,NaN,-4.82,NaN,98.56
2265,Whisky,Asien,10004.0,NaN,54.0,148.21,5.0,148.21,-7.41,111.16,151.44
2684,Whisky,USA,10026.0,NaN,19.0,82.51,NaN,82.51,-16.50,61.88,71.00
6205,Rum,USA,10074.0,NaN,27.0,131.09,0.0,131.09,0.00,98.32,141.00
6332,Whisky,EU,10039.0,NaN,24.0,150.72,0.0,150.72,0.00,NaN,162.11
6351,NaN,EU,NaN,NaN,49.0,123.67,0.0,123.67,0.00,NaN,133.02
6886,Whisky,EU,10008.0,NaN,42.0,175.61,0.0,175.61,0.00,131.71,188.89
7890,Whisky,EU,10050.0,NaN,42.0,107.43,NaN,107.43,-21.49,80.57,92.44

- Was ist die Logik für die Wertbefüllung der Column `BESTELLNUMMER` und `RECHNUNGSNUMMER`

In [ ]:
"""
text...
"""

- Daten die sowohl einen `NaN` Wert bei der `BESTELLNUMMER` als auch bei der `RECHNUNGSNUMMER` sollen aud dem Datensatz entfernt werden
<br><br> rows 10.301

,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD
0,Whisky,USA,5645.0,RE_2023_5645,16.0,128.95,5.0,128.95,-6.01,96.71,131.76
1,Whisky,EU,7994.0,RE_2023_7994,193.0,132.81,5.0,132.81,-6.64,99.61,135.71
2,Whisky,USA,3190.0,RE_2023_3190,126.0,216.21,0.0,216.21,0.00,162.16,232.56
3,Whisky,USA,790.0,RE_2023_790,171.0,172.13,0.0,172.13,0.00,129.10,185.14
4,Rum,USA,9975.0,RE_2023_9975,41.0,128.73,0.0,128.73,0.00,96.55,138.46
...,...,...,...,...,...,...,...,...,...,...,...
10922,Whisky,Asien,4659.0,RE_2023_4659,267.0,81.34,0.0,81.34,0.00,61.00,87.49
10923,Wein,EU,5325.0,RE_2023_5325,253.0,224.05,0.0,224.05,0.00,168.04,240.99
10924,Whisky,USA,9793.0,RE_2023_9793,152.0,149.56,0.0,149.56,0.00,112.17,160.87
10925,Wein,EU,5481.0,RE_2023_5481,19.0,213.35,0.0,213.35,0.00,160.01,229.48
10926,Whisky,USA,2523.0,RE_2023_2523,114.0,163.30,0.0,163.30,0.00,122.48,175.65

- Befüllen der NaN Werte in der Column `Rechnungsnummer`

,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD
0,Whisky,USA,5645.0,RE_2023_5645,16.0,128.95,5.0,128.95,-6.01,96.71,131.76
1,Whisky,EU,7994.0,RE_2023_7994,193.0,132.81,5.0,132.81,-6.64,99.61,135.71
2,Whisky,USA,3190.0,RE_2023_3190,126.0,216.21,0.0,216.21,0.00,162.16,232.56
3,Whisky,USA,790.0,RE_2023_790,171.0,172.13,0.0,172.13,0.00,129.10,185.14
4,Rum,USA,9975.0,RE_2023_9975,41.0,128.73,0.0,128.73,0.00,96.55,138.46
...,...,...,...,...,...,...,...,...,...,...,...
10922,Whisky,Asien,4659.0,RE_2023_4659,267.0,81.34,0.0,81.34,0.00,61.00,87.49
10923,Wein,EU,5325.0,RE_2023_5325,253.0,224.05,0.0,224.05,0.00,168.04,240.99
10924,Whisky,USA,9793.0,RE_2023_9793,152.0,149.56,0.0,149.56,0.00,112.17,160.87
10925,Wein,EU,5481.0,RE_2023_5481,19.0,213.35,0.0,213.35,0.00,160.01,229.48
10926,Whisky,USA,2523.0,RE_2023_2523,114.0,163.30,0.0,163.30,0.00,122.48,175.65

- Befüllen der NaN Werte in `Bestellnummer`
<br> `TIPP:` apply und lambda

,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD
0,Whisky,USA,5645.0,RE_2023_5645,16.0,128.95,5.0,128.95,-6.01,96.71,131.76
1,Whisky,EU,7994.0,RE_2023_7994,193.0,132.81,5.0,132.81,-6.64,99.61,135.71
2,Whisky,USA,3190.0,RE_2023_3190,126.0,216.21,0.0,216.21,0.00,162.16,232.56
3,Whisky,USA,790.0,RE_2023_790,171.0,172.13,0.0,172.13,0.00,129.10,185.14
4,Rum,USA,9975.0,RE_2023_9975,41.0,128.73,0.0,128.73,0.00,96.55,138.46
...,...,...,...,...,...,...,...,...,...,...,...
10922,Whisky,Asien,4659.0,RE_2023_4659,267.0,81.34,0.0,81.34,0.00,61.00,87.49
10923,Wein,EU,5325.0,RE_2023_5325,253.0,224.05,0.0,224.05,0.00,168.04,240.99
10924,Whisky,USA,9793.0,RE_2023_9793,152.0,149.56,0.0,149.56,0.00,112.17,160.87
10925,Wein,EU,5481.0,RE_2023_5481,19.0,213.35,0.0,213.35,0.00,160.01,229.48
10926,Whisky,USA,2523.0,RE_2023_2523,114.0,163.30,0.0,163.30,0.00,122.48,175.65

`Rechnungsnummern müssen einmalig sein`
- Aus diesem Grund sollen jeweils alle gleichen Rechnungsnummern aus dem Datensatz entfernt werden
- Erstelle hierfür einen neuen Dataframe `data_2023_unique`
<br><br> rows 10.079

10079

- befülle die NaN Werte in `RABATT_IN_PROZENT` mit den richtigen Prozenten
    - Berechnung ergibt sich aus `LISTENPREIS` und `VERKAUFSPREIS`

,RECHNUNGSNUMMER,GETRAENK,REGION,BESTELLNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD
0,10004,Whisky,Asien,10004.0,54.0,148.21,5.0,148.21,-7.41,111.16,151.44
1,10008,Whisky,EU,10008.0,42.0,175.61,0.0,175.61,0.00,131.71,188.89
2,10026,Whisky,USA,10026.0,19.0,82.51,0.0,82.51,-16.50,61.88,71.00
3,10039,Whisky,EU,10039.0,24.0,150.72,0.0,150.72,0.00,NaN,162.11
4,10050,Whisky,EU,10050.0,42.0,107.43,0.0,107.43,-21.49,80.57,92.44
...,...,...,...,...,...,...,...,...,...,...,...
10074,RE_2023_9995,Whisky,EU,9995.0,228.0,206.73,0.0,206.73,0.00,155.05,222.36
10075,RE_2023_9996,Whisky,EU,9996.0,126.0,117.78,0.0,117.78,0.00,88.34,126.68
10076,RE_2023_9997,Wein,EU,9997.0,253.0,105.83,0.0,105.83,0.00,79.37,113.83
10077,RE_2023_9998,Whisky,EU,9998.0,215.0,175.00,0.0,175.00,0.00,131.25,188.23
10078,RE_2023_9999,Whisky,EU,9999.0,141.0,113.73,10.0,113.73,-11.37,85.30,110.10

- befülle die restlichen Werte von `RABATT_IN_PROZENT` mit der Zahl `0`

,RECHNUNGSNUMMER,GETRAENK,REGION,BESTELLNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD
0,10004,Whisky,Asien,10004.0,54.0,148.21,5.0,148.21,-7.41,111.16,151.44
1,10008,Whisky,EU,10008.0,42.0,175.61,0.0,175.61,0.00,131.71,188.89
2,10026,Whisky,USA,10026.0,19.0,82.51,0.0,82.51,-16.50,61.88,71.00
3,10039,Whisky,EU,10039.0,24.0,150.72,0.0,150.72,0.00,NaN,162.11
4,10050,Whisky,EU,10050.0,42.0,107.43,0.0,107.43,-21.49,80.57,92.44
...,...,...,...,...,...,...,...,...,...,...,...
10074,RE_2023_9995,Whisky,EU,9995.0,228.0,206.73,0.0,206.73,0.00,155.05,222.36
10075,RE_2023_9996,Whisky,EU,9996.0,126.0,117.78,0.0,117.78,0.00,88.34,126.68
10076,RE_2023_9997,Wein,EU,9997.0,253.0,105.83,0.0,105.83,0.00,79.37,113.83
10077,RE_2023_9998,Whisky,EU,9998.0,215.0,175.00,0.0,175.00,0.00,131.25,188.23
10078,RE_2023_9999,Whisky,EU,9999.0,141.0,113.73,10.0,113.73,-11.37,85.30,110.10

- befülle die NaN Werte in der Column `LISTENPREIS` mit dem Mittelwert der Column

,RECHNUNGSNUMMER,GETRAENK,REGION,BESTELLNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD
0,10004,Whisky,Asien,10004.0,54.0,148.21,5.0,148.21,-7.41,111.16,151.44
1,10008,Whisky,EU,10008.0,42.0,175.61,0.0,175.61,0.00,131.71,188.89
2,10026,Whisky,USA,10026.0,19.0,82.51,0.0,82.51,-16.50,61.88,71.00
3,10039,Whisky,EU,10039.0,24.0,150.72,0.0,150.72,0.00,NaN,162.11
4,10050,Whisky,EU,10050.0,42.0,107.43,0.0,107.43,-21.49,80.57,92.44
...,...,...,...,...,...,...,...,...,...,...,...
10074,RE_2023_9995,Whisky,EU,9995.0,228.0,206.73,0.0,206.73,0.00,155.05,222.36
10075,RE_2023_9996,Whisky,EU,9996.0,126.0,117.78,0.0,117.78,0.00,88.34,126.68
10076,RE_2023_9997,Wein,EU,9997.0,253.0,105.83,0.0,105.83,0.00,79.37,113.83
10077,RE_2023_9998,Whisky,EU,9998.0,215.0,175.00,0.0,175.00,0.00,131.25,188.23
10078,RE_2023_9999,Whisky,EU,9999.0,141.0,113.73,10.0,113.73,-11.37,85.30,110.10

- befülle die NaN Werte mit dem `vorherigen` nicht NaN-Wert in der Column `VERKAUFSPREIS` --> forward fill verwenden

,RECHNUNGSNUMMER,GETRAENK,REGION,BESTELLNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD
0,10004,Whisky,Asien,10004.0,54.0,148.21,5.0,148.21,-7.41,111.16,151.44
1,10008,Whisky,EU,10008.0,42.0,175.61,0.0,175.61,0.00,131.71,188.89
2,10026,Whisky,USA,10026.0,19.0,82.51,0.0,82.51,-16.50,61.88,71.00
3,10039,Whisky,EU,10039.0,24.0,150.72,0.0,150.72,0.00,NaN,162.11
4,10050,Whisky,EU,10050.0,42.0,107.43,0.0,107.43,-21.49,80.57,92.44
...,...,...,...,...,...,...,...,...,...,...,...
10074,RE_2023_9995,Whisky,EU,9995.0,228.0,206.73,0.0,206.73,0.00,155.05,222.36
10075,RE_2023_9996,Whisky,EU,9996.0,126.0,117.78,0.0,117.78,0.00,88.34,126.68
10076,RE_2023_9997,Wein,EU,9997.0,253.0,105.83,0.0,105.83,0.00,79.37,113.83
10077,RE_2023_9998,Whisky,EU,9998.0,215.0,175.00,0.0,175.00,0.00,131.25,188.23
10078,RE_2023_9999,Whisky,EU,9999.0,141.0,113.73,10.0,113.73,-11.37,85.30,110.10

- befülle die NaN Werte mit dem `nachstehenden` nicht NaN-Wert in der Column `EINKAUFPREIS` --> backward fill verwenden

,RECHNUNGSNUMMER,GETRAENK,REGION,BESTELLNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD
0,10004,Whisky,Asien,10004.0,54.0,148.21,5.0,148.21,-7.41,111.16,151.44
1,10008,Whisky,EU,10008.0,42.0,175.61,0.0,175.61,0.00,131.71,188.89
2,10026,Whisky,USA,10026.0,19.0,82.51,0.0,82.51,-16.50,61.88,71.00
3,10039,Whisky,EU,10039.0,24.0,150.72,0.0,150.72,0.00,80.57,162.11
4,10050,Whisky,EU,10050.0,42.0,107.43,0.0,107.43,-21.49,80.57,92.44
...,...,...,...,...,...,...,...,...,...,...,...
10074,RE_2023_9995,Whisky,EU,9995.0,228.0,206.73,0.0,206.73,0.00,155.05,222.36
10075,RE_2023_9996,Whisky,EU,9996.0,126.0,117.78,0.0,117.78,0.00,88.34,126.68
10076,RE_2023_9997,Wein,EU,9997.0,253.0,105.83,0.0,105.83,0.00,79.37,113.83
10077,RE_2023_9998,Whisky,EU,9998.0,215.0,175.00,0.0,175.00,0.00,131.25,188.23
10078,RE_2023_9999,Whisky,EU,9999.0,141.0,113.73,10.0,113.73,-11.37,85.30,110.10

- schaue dir die Daten mit der help-function `info` an

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10079 entries, 0 to 10078
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   RECHNUNGSNUMMER    10079 non-null  object
 1   GETRAENK           10066 non-null  object
 2   REGION             10077 non-null  object
 3   BESTELLNUMMER      10079 non-null  object
 4   KUNDENNUMMER       10079 non-null  float64
 5   LISTENPREIS        10079 non-null  float64
 6   RABATT_IN_PROZENT  10079 non-null  float64
 7   VERKAUFSPREIS      10079 non-null  float64
 8   RABATT_PREIS       10079 non-null  float64
 9   EINKAUFPREIS       10079 non-null  float64
 10  VK_PERIS_IN_USD    10079 non-null  float64
dtypes: float64(7), object(4)
memory usage: 866.3+ KB

### c) Datenbearbeitung Wiederholung
- setze einen Filter von dem Dataframe `data_2023_neu_unique`
- durch den Filter sollen `alle` Einträge deren `BESTELLNUMMER` zwischen `10` und `20` ist angezeigt werden
<br><br> rows 11

,RECHNUNGSNUMMER,GETRAENK,REGION,BESTELLNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD
9,RE_2023_10,Whisky,EU,10.0,296.0,143.53,5.0,143.53,-7.18,107.65,146.66
192,RE_2023_11,Whisky,USA,11.0,278.0,213.64,5.0,213.64,-10.68,160.23,218.30
303,RE_2023_12,Champagner,EU,12.0,85.0,111.10,0.0,111.10,0.00,83.32,119.50
414,RE_2023_13,Wein,USA,13.0,37.0,182.09,0.0,182.09,0.00,136.57,195.86
525,RE_2023_14,Wein,EU,14.0,279.0,88.18,0.0,88.18,0.00,66.14,94.85
636,RE_2023_15,Whisky,Asien,15.0,137.0,138.20,0.0,138.20,0.00,103.65,148.65
747,RE_2023_16,Whisky,EU,16.0,169.0,100.78,0.0,100.78,0.00,75.59,108.40
858,RE_2023_17,Champagner,Asien,17.0,40.0,157.89,0.0,157.89,0.00,118.42,169.83
969,RE_2023_18,Whisky,EU,18.0,87.0,131.38,0.0,131.38,0.00,98.54,141.31
1080,RE_2023_19,Wein,Asien,19.0,84.0,164.63,0.0,164.63,0.00,123.47,177.08
1192,RE_2023_20,Whisky,USA,20.0,287.0,199.37,0.0,199.37,0.00,149.53,214.44

- entferne alle rows mit den Kundennummern aus der Aufgabe vorher mittels `isin`
<br><br> rows 9.720

9720

- sortiere die Daten einmal nach der `KUNDENNUMMER`

,RECHNUNGSNUMMER,GETRAENK,REGION,BESTELLNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD
1284,RE_2023_2082,Wein,EU,2082.0,1.0,114.36,10.0,114.36,-11.44,85.77,110.70
8088,RE_2023_8206,Champagner,EU,8206.0,1.0,80.40,0.0,80.40,0.00,60.30,86.48
2421,RE_2023_3105,Whisky,USA,3105.0,1.0,82.63,0.0,82.63,0.00,61.97,88.88
2833,RE_2023_3477,Rum,EU,3477.0,1.0,123.01,0.0,123.01,0.00,92.26,132.31
5984,RE_2023_6312,Champagner,USA,6312.0,1.0,166.26,0.0,166.26,0.00,124.70,178.83
...,...,...,...,...,...,...,...,...,...,...,...
9857,RE_2023_98,Whisky,Asien,98.0,299.0,102.48,0.0,102.48,0.00,76.86,110.23
1097,RE_2023_1914,Rum,USA,1914.0,299.0,165.02,10.0,165.02,-16.50,123.77,159.75
8885,RE_2023_8924,Whisky,EU,8924.0,299.0,111.33,0.0,111.33,0.00,83.50,119.75
6257,RE_2023_6559,Whisky,EU,6559.0,299.0,97.67,0.0,97.67,0.00,73.25,105.05
7330,RE_2023_7524,Whisky,Asien,7524.0,299.0,108.93,10.0,108.93,-10.89,81.70,105.45

- sortiere die Daten nach zwei Kriterien (das erste ist `GETRAENK`und das zweite ist `BESTELLNUMMER`) 
    - `GETRAENK` wird **absteigend** und 
    . `BESTELLNUMMER` wird **aufsteigend** sortiert

,RECHNUNGSNUMMER,GETRAENK,REGION,BESTELLNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD
85,RE_2023_10072,Champagner,EU,10072.0,58.0,202.37,10.0,202.37,-20.24,103.55,195.90
77,RE_2023_10065,Champagner,EU,10065.0,6.0,206.31,0.0,206.31,0.00,154.73,221.91
55,RE_2023_10043,Champagner,EU,10043.0,53.0,191.89,0.0,191.89,0.00,143.92,206.40
54,RE_2023_10042,Champagner,EU,10042.0,69.0,224.05,0.0,224.05,0.00,143.92,240.99
44,RE_2023_10032,Champagner,USA,10032.0,25.0,83.25,0.0,83.25,0.00,62.44,89.54
...,...,...,...,...,...,...,...,...,...,...,...
32,RE_2023_10020,None,EU,10020.0,12.0,93.58,0.0,93.58,0.00,70.18,100.65
29,RE_2023_10018,None,EU,10018.0,32.0,93.32,0.0,93.32,0.00,158.59,100.37
28,RE_2023_10017,None,USA,10017.0,61.0,184.30,0.0,184.30,0.00,138.23,198.23
26,RE_2023_10015,None,USA,10015.0,58.0,217.54,10.0,217.54,-21.75,124.30,210.59
17,RE_2023_10006,None,USA,10006.0,10.0,226.41,0.0,226.41,0.00,88.94,243.53

## Aufgabe 4: Datenzusammenführen
### a) führe die Daten `data_2020, data_2021, data_2022 **und** data_2023_neu_unique` zusammen

#### fasse die Daten sinnvoll zusammen (Vorbereitung)
- schreibe eine Funktion um die Datensätze in die gleiche Columns umzuwandeln und erstelle jeweile neue Datframes mit dem Titel:
    - data_2020_n
    - data_2021_n
    - data_2022_n
- Die Einzelteile der Funktion wurden in den vorherigen Aufgaben schon definiert

- benutze für das zusammenführen einmal `concat` und erstelle einen neuen Dataframes `data_all`
<br><br> Lösung *25079 rows × 11 columns*

25079

,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD
0,Rum,Asien,0.0,RE_2020_0,27.0,86.23,0.0,86.23,0.00,64.67,92.75
1,Wein,EU,1.0,RE_2020_1,87.0,182.93,0.0,182.93,0.00,137.20,196.76
2,Wein,Asien,2.0,RE_2020_2,76.0,103.97,0.0,103.97,0.00,77.98,111.83
3,Whisky,USA,3.0,RE_2020_3,44.0,119.95,0.0,119.95,0.00,89.96,129.02
4,Whisky,EU,4.0,RE_2020_4,25.0,217.43,5.0,206.56,-10.87,163.07,222.18

- benutze hierfür einmal `append`
<br><br> Lösung *25079 rows × 11 columns*

data_2020_n.append(data_2021_n).append(data_2022_n).append(data_2023_neu_unique)

# `**ACHTUNG** APPEND NORMALERWEISE NICHT VERWENDEN`
## append wird in zukünftigen Versionen nicht mehr funktionieren

- benutze für das zusammenführen `merge`
<br><br> Lösung *25079 rows × 11 columns*

,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD
0,Rum,Asien,0.0,RE_2020_0,27.0,86.23,0.0,86.23,0.00,64.67,92.75
1,Wein,EU,1.0,RE_2020_1,87.0,182.93,0.0,182.93,0.00,137.20,196.76
2,Wein,Asien,2.0,RE_2020_2,76.0,103.97,0.0,103.97,0.00,77.98,111.83
3,Whisky,USA,3.0,RE_2020_3,44.0,119.95,0.0,119.95,0.00,89.96,129.02
4,Whisky,EU,4.0,RE_2020_4,25.0,217.43,5.0,206.56,-10.87,163.07,222.18
...,...,...,...,...,...,...,...,...,...,...,...
25074,Whisky,EU,9995.0,RE_2023_9995,228.0,206.73,0.0,206.73,0.00,155.05,222.36
25075,Whisky,EU,9996.0,RE_2023_9996,126.0,117.78,0.0,117.78,0.00,88.34,126.68
25076,Wein,EU,9997.0,RE_2023_9997,253.0,105.83,0.0,105.83,0.00,79.37,113.83
25077,Whisky,EU,9998.0,RE_2023_9998,215.0,175.00,0.0,175.00,0.00,131.25,188.23
25078,Whisky,EU,9999.0,RE_2023_9999,141.0,113.73,10.0,113.73,-11.37,85.30,110.10

- benutze für das zusammenführen der Daten `join`
- funktioniert das?

### b) Newsletter Daten
- importiere die Dataframes `news` von den Jahren 2020 bis 2023 jeweils in einer eigenen Variabel

- verändere den Index im Dataframe `news_2020` 
- der neue Index soll die `Kd.Nr` sein

- führe die Newsletter Dataframe aus den Jahren `2020, 2021, 2022` zusammen
- gebe nur die Kunden wieder, welche in allen 3 Datensätzen enthalten sind
<br><br> Lösung *24 rows × 38 columns*

24

- führe die Newsletter Dataframes aus den Jahren `2023, 2022` zusammen
- spiele dabei alle Werte von 2022 an den Dataframe von 2023 dran
- verwende `merge` für das zusammen führen
<br><br> Lösung *240 rows × 25 columns*

,Newsletter_1_Cupon_2023,Newsletter_2_Cupon_2023,Newsletter_3_Cupon_2023,Newsletter_4_Cupon_2023,Newsletter_5_Cupon_2023,Newsletter_6_Cupon_2023,Newsletter_7_Cupon_2023,Newsletter_8_Cupon_2023,Newsletter_9_Cupon_2023,Newsletter_10_Cupon_2023,...,Newsletter_3_Cupon_2022,Newsletter_4_Cupon_2022,Newsletter_5_Cupon_2022,Newsletter_6_Cupon_2022,Newsletter_7_Cupon_2022,Newsletter_8_Cupon_2022,Newsletter_9_Cupon_2022,Newsletter_10_Cupon_2022,Newsletter_11_Cupon_2022,Newsletter_12_Cupon_2022
0,nein,nein,nein,nein,nein,ja,nein,nein,nein,nein,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,nein,nein,nein,nein,ja,ja,nein,ja,nein,nein,...,ja,nein,nein,nein,ja,nein,nein,nein,nein,nein
2,nein,nein,nein,nein,nein,nein,ja,ja,nein,nein,...,nein,nein,nein,ja,nein,nein,nein,nein,ja,ja
3,ja,nein,nein,nein,ja,nein,nein,ja,nein,ja,...,nein,ja,nein,ja,ja,nein,nein,ja,nein,nein
4,nein,nein,nein,nein,nein,nein,nein,nein,nein,nein,...,nein,ja,nein,ja,nein,nein,nein,nein,nein,ja
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,nein,nein,ja,nein,nein,ja,nein,nein,nein,nein,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236,nein,nein,nein,nein,nein,ja,ja,nein,nein,nein,...,nein,ja,nein,ja,nein,nein,ja,nein,nein,nein
237,nein,nein,nein,nein,ja,ja,ja,nein,ja,nein,...,nein,nein,ja,nein,ja,ja,nein,nein,nein,nein
238,nein,nein,nein,nein,ja,nein,ja,ja,nein,nein,...,ja,nein,ja,nein,ja,nein,nein,nein,nein,ja
239,nein,nein,ja,ja,nein,nein,nein,nein,nein,nein,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- schreibe ***alle*** `news_data` in einen neuen Dataframes `news_all_years`
    - was kann ich verwenden, wenn ich `nicht merge` verwenden möchte. Begründe es kurz
- gebe nur eine `Kundennummer` in dem Dataframe als Columnnamen an
- **Tipp** reset index bei dem Dataframe `news_2020`
<br><br> Ergebnis 284 rows × 49 columns

284

284

- füge über die Kundennummern die Daten aus `news_all_years` an die Daten aus `data_all` an
- und speicher diese in dem Datensatz `data_merged_save`
<br><br> Ergebnis 25079 rows × 59 columns

,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,...,Newsletter_3_Cupon_2023,Newsletter_4_Cupon_2023,Newsletter_5_Cupon_2023,Newsletter_6_Cupon_2023,Newsletter_7_Cupon_2023,Newsletter_8_Cupon_2023,Newsletter_9_Cupon_2023,Newsletter_10_Cupon_2023,Newsletter_11_Cupon_2023,Newsletter_12_Cupon_2023
0,Rum,Asien,0.0,RE_2020_0,27.0,86.23,0.0,86.23,0.00,64.67,...,nein,ja,nein,ja,ja,nein,ja,nein,nein,ja
1,Wein,EU,1.0,RE_2020_1,87.0,182.93,0.0,182.93,0.00,137.20,...,nein,nein,ja,nein,nein,ja,nein,nein,nein,nein
2,Wein,Asien,2.0,RE_2020_2,76.0,103.97,0.0,103.97,0.00,77.98,...,nein,nein,nein,nein,ja,ja,ja,nein,nein,ja
3,Whisky,USA,3.0,RE_2020_3,44.0,119.95,0.0,119.95,0.00,89.96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Whisky,EU,4.0,RE_2020_4,25.0,217.43,5.0,206.56,-10.87,163.07,...,nein,ja,ja,ja,ja,nein,nein,nein,nein,ja
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25074,Whisky,EU,9995.0,RE_2023_9995,228.0,206.73,0.0,206.73,0.00,155.05,...,nein,nein,nein,nein,nein,ja,nein,nein,nein,nein
25075,Whisky,EU,9996.0,RE_2023_9996,126.0,117.78,0.0,117.78,0.00,88.34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25076,Wein,EU,9997.0,RE_2023_9997,253.0,105.83,0.0,105.83,0.00,79.37,...,nein,nein,ja,nein,nein,nein,ja,nein,nein,ja
25077,Whisky,EU,9998.0,RE_2023_9998,215.0,175.00,0.0,175.00,0.00,131.25,...,ja,nein,nein,nein,nein,nein,nein,nein,nein,ja
25078,Whisky,EU,9999.0,RE_2023_9999,141.0,113.73,10.0,113.73,-11.37,85.30,...,ja,nein,ja,ja,nein,nein,nein,nein,nein,nein

## Aufgabe 5: Daten in eine CSV und Excel schreiben

- speichere den Dataframe `data_merged_save` in einer Excel Datei
    - erstelle hierfür einen Ordner in der du die Excel speichern willst
    - gebe dem Excel den Sheet Namen `news_2023` mit

- speichere den Dataframe `data_merged_save` äquivalent in einer csv Datei
- gebe den `Seperator` und das `Encoding` verfahren mit

## Aufgabe 6: Datenselektion
### a) selektion mittels Datenzusammenführen
- erstelle `nur` einen Dataframe von allen Kunden aus den Daten `data_2020`, welche auch Produkte in den anderen `data_2021, data_2022 und data_2023_neu_unique` haben
<br><br> Ergebnis 11.653 rows × 11 columns

In [ ]:
# concat

In [ ]:
# merge

,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD,KUNDENNUMMER
0,Rum,Asien,0.0,RE_2020_0,86.23,0.0,86.23,0.00,64.67,92.75,27
0,Rum,EU,308.0,RE_2020_308,190.13,0.0,190.13,0.00,142.60,204.50,27
0,Whisky,EU,357.0,RE_2020_357,126.13,0.0,126.13,0.00,94.60,135.67,27
0,Whisky,EU,482.0,RE_2020_482,197.24,0.0,197.24,0.00,147.93,212.15,27
0,Whisky,EU,531.0,RE_2020_531,185.71,0.0,185.71,0.00,139.28,199.75,27
...,...,...,...,...,...,...,...,...,...,...,...
576,Wein,EU,9096.0,RE_2023_9096,153.09,5.0,153.09,-7.65,114.82,156.44,65
576,Whisky,USA,9490.0,RE_2023_9490,228.05,0.0,228.05,0.00,171.04,245.29,65
576,Whisky,Asien,9561.0,RE_2023_9561,139.66,0.0,139.66,0.00,104.74,150.22,65
576,Rum,EU,9565.0,RE_2023_9565,153.03,0.0,153.03,0.00,114.77,164.60,65
576,Whisky,EU,9948.0,RE_2023_9948,183.85,0.0,183.85,0.00,137.89,197.75,65

### b) nach Selektionskriterien in Dataframes
- selktiere den Dataframe `data_all` nach den folgenden Kriterien
#### Der Dataframe soll endeweder:
- `nur` die `REGION EU oder Asien` und
- nur Kunden mit einer `KUNDENNUMMER grösser/gleich 50` und
- das Getränk darf `nicht gleich Champagner` sein und
- es wurde kein Rabatt gewärt (`= 0`)
<br><br> **oder** <br><br>
- die `BESTELLNUMMER` enthält die Zahl 1 an irgendeiner Stelle z.B. `(1, 10, 21 ..)`
<br><br> Ergebnis 15.772 rows × 11 columns

,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD
1,Wein,EU,1.0,RE_2020_1,87.0,182.93,0.0,182.93,0.0,137.20,196.76
2,Wein,Asien,2.0,RE_2020_2,76.0,103.97,0.0,103.97,0.0,77.98,111.83
9,Whisky,Asien,9.0,RE_2020_9,85.0,229.50,0.0,229.50,0.0,172.12,246.85
10,Rum,EU,10.0,RE_2020_10,41.0,164.81,0.0,164.81,0.0,123.61,177.27
11,Rum,EU,11.0,RE_2020_11,82.0,161.34,0.0,161.34,0.0,121.00,173.54
...,...,...,...,...,...,...,...,...,...,...,...
10073,Whisky,EU,9994.0,RE_2023_9994,116.0,155.83,0.0,155.83,0.0,116.87,167.61
10074,Whisky,EU,9995.0,RE_2023_9995,228.0,206.73,0.0,206.73,0.0,155.05,222.36
10075,Whisky,EU,9996.0,RE_2023_9996,126.0,117.78,0.0,117.78,0.0,88.34,126.68
10076,Wein,EU,9997.0,RE_2023_9997,253.0,105.83,0.0,105.83,0.0,79.37,113.83
10077,Whisky,EU,9998.0,RE_2023_9998,215.0,175.00,0.0,175.00,0.0,131.25,188.23

#### selktiere den Dataframe `data_2023`
- es sollen nur rows angezeigt werden, welche
    - `kein Wert` in der Rechnungsnummer haben **`und`**
    - `ein Wert` in der Kundennummer haben
<br><br> Ergebnis 8 rows

,Unnamed: 0,Getränk,Region,Bestellnummer,Rechnungsnummer,Kundennummer,Listenpreis,Rabatt in Prozent,Verkaufspreis,Rabatt Preis,Einkaufpreis,VK Peris in USD
2171,72,Whisky,NaN,10078.0,NaN,54.0,NaN,5.0,NaN,-4.82,NaN,98.56
2265,66,Whisky,Asien,10004.0,NaN,54.0,148.21,5.0,148.21,-7.41,111.16,151.44
2684,67,Whisky,USA,10026.0,NaN,19.0,82.51,NaN,82.51,-16.50,61.88,71.00
6205,69,Rum,USA,10074.0,NaN,27.0,131.09,0.0,131.09,0.00,98.32,141.00
6332,70,Whisky,EU,10039.0,NaN,24.0,150.72,0.0,150.72,0.00,NaN,162.11
6351,79,NaN,EU,NaN,NaN,49.0,123.67,0.0,123.67,0.00,NaN,133.02
6886,71,Whisky,EU,10008.0,NaN,42.0,175.61,0.0,175.61,0.00,131.71,188.89
7890,68,Whisky,EU,10050.0,NaN,42.0,107.43,NaN,107.43,-21.49,80.57,92.44

- es sollen nur rows angezeigt werden, welche
    - `ein Wert` in der Rabattcolumn haben **`oder`** 
    - `kein Wert` in der Verkaufspreis
<br><br> Ergebnis 10.920 rows × 12 columns

,Unnamed: 0,Getränk,Region,Bestellnummer,Rechnungsnummer,Kundennummer,Listenpreis,Rabatt in Prozent,Verkaufspreis,Rabatt Preis,Einkaufpreis,VK Peris in USD
0,205,Whisky,USA,5645.0,RE_2023_5645,16.0,128.95,5.0,128.95,-6.01,n96.71,131.76
1,8920,Whisky,EU,7994.0,RE_2023_7994,193.0,132.81,5.0,n132.81,-6.64,99.61,135.71
2,4116,Whisky,USA,3190.0,RE_2023_3190,126.0,216.21,0.0,216.21,0.00,162.16,232.56
3,1716,Whisky,USA,790.0,RE_2023_790,171.0,172.13,0.0,172.13,0.00,129.1,185.14
4,10901,Rum,USA,9975.0,RE_2023_9975,41.0,128.73,0.0,128.73,0.00,96.55,138.46
...,...,...,...,...,...,...,...,...,...,...,...,...
10922,5585,Whisky,Asien,4659.0,RE_2023_4659,267.0,81.34,0.0,81.34,0.00,61.0,87.49
10923,6251,Wein,EU,5325.0,RE_2023_5325,253.0,224.05,0.0,224.05,0.00,168.04,240.99
10924,10719,Whisky,USA,9793.0,RE_2023_9793,152.0,149.56,0.0,149.56,0.00,112.17,160.87
10925,6407,Wein,EU,5481.0,RE_2023_5481,19.0,213.35,0.0,213.35,0.00,160.01,229.48
10926,3449,Whisky,USA,2523.0,RE_2023_2523,114.0,163.30,0.0,163.3,0.00,122.48,175.65