# Aufgabenblatt 8:

## Aufgabe 1: 

Durch die zufälligen Werte in dem Dataframes `data_np` werden die angezeigten Lösungen nicht mit euren Lösungen identisch sein. Die angezeigten Lösungen sollen euch nur einen Indikator anzeigen, was bei den Aufgaben gemacht werden soll.

In [138]:
import pandas as pd
import numpy as np
import random
import string

data_np = {'column_int': np.random.randint(1,10, size=100)
        , 'column_int_1': np.random.randint(1,10, size=100)
        , 'column_float': np.random.uniform(low=-100, high=100, size=(100))
       }

data_np = pd.DataFrame(data_np)
data_np.head()

   column_int  column_int_1  column_float
0           2             3    -50.649770
1           1             6    -21.422160
2           9             5     69.077213
3           5             6     70.899272
4           6             7    -29.421952

- ersetze in dem Dataframes `data_np` in der Column `column_int_1` die Werte `6 und 7`  mit `NaN-Werten`
<br><br>**Tipp** verwende replace und gebe beide Elemente in einer Liste wieder

In [139]:
data_np['column_int_1'] = data_np['column_int_1'].replace([6, 7], np.nan)
data_np

    column_int  column_int_1  column_float
0            2           3.0    -50.649770
1            1           NaN    -21.422160
2            9           5.0     69.077213
3            5           NaN     70.899272
4            6           NaN    -29.421952
..         ...           ...           ...
95           1           NaN    -60.003459
96           3           3.0     49.778136
97           1           NaN      2.973273
98           5           NaN     95.083008
99           8           9.0     83.680535

[100 rows x 3 columns]

- bestimme die Grösse (columns und records) von dem Dataframes `data_np`

In [140]:
data_np.shape

(100, 3)

- berechne für alle `Column` aus dem Dataframes `data_np` den dazugehörigen mean pro Column

In [141]:
col_list = data_np.columns

for col in col_list:
    print(col + ":",data_np[col].mean())

column_int: 4.71
column_int_1: 4.853658536585366
column_float: 11.67455037555495

- berechne nun den mean pro `Row` für den Dataframe `data_np`
- Was muss sich ändern in den Parametern von mean?

In [142]:
data_np.mean(axis=1)

0    -15.216590
1    -10.211080
2     27.692404
3     37.949636
4    -11.710976
        ...
95   -29.501730
96    18.592712
97     1.986637
98    50.041504
99    33.560178
Length: 100, dtype: float64

- füge dem Dataframe `data_np` eine neue `Column` mir dem Namen `mean_row` hinzu 
- Die Column `mean_row` wird der durchschnitts Wert pro row übergeben

In [143]:
data_np["mean_row"] = data_np.mean(axis=1)
data_np

    column_int  column_int_1  column_float   mean_row
0            2           3.0    -50.649770 -15.216590
1            1           NaN    -21.422160 -10.211080
2            9           5.0     69.077213  27.692404
3            5           NaN     70.899272  37.949636
4            6           NaN    -29.421952 -11.710976
..         ...           ...           ...        ...
95           1           NaN    -60.003459 -29.501730
96           3           3.0     49.778136  18.592712
97           1           NaN      2.973273   1.986637
98           5           NaN     95.083008  50.041504
99           8           9.0     83.680535  33.560178

[100 rows x 4 columns]

- füge dem Dataframe `data_np` eine neue Column mit dem Namen `column_sum` hinzu
- Der Column `column_sum` soll die Summe pro row `mittels apply` übergeben werden

In [144]:
data_np["column_sum"] = data_np.apply(func=lambda row: row.sum(), axis=1)
data_np

    column_int  column_int_1  column_float   mean_row  column_sum
0            2           3.0    -50.649770 -15.216590  -60.866360
1            1           NaN    -21.422160 -10.211080  -30.633240
2            9           5.0     69.077213  27.692404  110.769617
3            5           NaN     70.899272  37.949636  113.848908
4            6           NaN    -29.421952 -11.710976  -35.132928
..         ...           ...           ...        ...         ...
95           1           NaN    -60.003459 -29.501730  -88.505189
96           3           3.0     49.778136  18.592712   74.370849
97           1           NaN      2.973273   1.986637    5.959910
98           5           NaN     95.083008  50.041504  150.124512
99           8           9.0     83.680535  33.560178  134.240713

[100 rows x 5 columns]

- füge dem Dataframes `data_np` eine neue row hinzu
- übergebe der neuen row die Summe pro Column mittels loc

In [145]:
sum_row = data_np.sum(axis=0, numeric_only=True)

data_np.loc[len(data_np)] = sum_row
data_np

     column_int  column_int_1  column_float    mean_row   column_sum
0           2.0           3.0    -50.649770  -15.216590   -60.866360
1           1.0           NaN    -21.422160  -10.211080   -30.633240
2           9.0           5.0     69.077213   27.692404   110.769617
3           5.0           NaN     70.899272   37.949636   113.848908
4           6.0           NaN    -29.421952  -11.710976   -35.132928
..          ...           ...           ...         ...          ...
96          3.0           3.0     49.778136   18.592712    74.370849
97          1.0           NaN      2.973273    1.986637     5.959910
98          5.0           NaN     95.083008   50.041504   150.124512
99          8.0           9.0     83.680535   33.560178   134.240713
100       471.0         398.0   1167.455038  770.870844  2807.325881

[101 rows x 5 columns]

## Aufgabe 2: numpy Funktionen

### a) allgemeine Funktionen

- Was ist der cosinuns von 1?

In [146]:
print(np.cos(1))

0.5403023058681398

- erstelle ein Array mit 12 Elementen, welche alle den gleichen Wert haben z.B. 0
- unterteile das erstellte Array in `drei` unter Listen, welche jeweils aus `vier` Elementen besteht

In [147]:
arr = np.zeros(12, dtype=int)
arr = arr.reshape(3,4)
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

- erstelle nun ein Attay mit unterschiedlichen Zahlen, nachden gleichen Zahlen bereichen

In [148]:
counting_array = np.resize(np.arange(1, 10), (3, 4))
counting_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

### b) Slicing
- bilde ein 1-dimensionales Array aus 6 Zahlen (1,2, usw.) mit dem Namen `arr`

In [149]:
arr = np.arange(1,7)
arr

array([1, 2, 3, 4, 5, 6])

- verwende die Slicing-Notation um die `letzten 4 Elemente` aus dem Array `arr` anzuzeigen

In [150]:
arr[-4:]

array([3, 4, 5, 6])

- verwende die Slicing-Notation, sodass `jedes zweites Element` ab der `zweiten` Zahl bis zur `fünften` Zahl ausgegeben wird aus dem Array `arr`

In [151]:
arr[1:5:2]

array([2, 4])

- bilde ein neues 2-dimensionales Array mit dem Namen `arr2` mit jeweils `drei` unter Listen, welche jeweils aus `vier` Elementen besteht
- [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]

In [152]:
arr2 = np.arange(1,13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- verwende die Slicing-Notation, um aus dem Array `arr2` dir die aus der ersten Dimension, die ersten beiden Elementen anzuzeigen

In [153]:
arr2[0, 0:2]

array([1, 2])

- zeige aus dem Array `arr2` 
    - aus den beiden ersten Dimensionen (1. Dimension und 2. Dimension) 
    - jeweils das dritte Element an

In [154]:
arr2[0:2, 2]

array([3, 7])

- wähle aus dem Array `arr2` 
    - aus den beiden ersten Dimensionen 
    - jeweils das zweite Element und alle Elemente ab dem zweiten Element aus

In [155]:
#vllt ist die aufgabe anders gemeint aber seine lösung ergibt mit der aufgabe keinen sinn
arr2[0:2, 1:]

array([[2, 3, 4],
       [6, 7, 8]])

### c) Weitere Aspekte
- itteriere über das Array `arr2` und gebe jedes Element **einzelend** aus
- mittels fo-loops

In [156]:
for list_element in arr2:
    for element in list_element:
        print(element)

1
2
3
4
5
6
7
8
9
10
11
12

- verwende eine numpy funktion zum lösen 
<br><br> **Tipp** es geht Richtung `iter`

In [157]:
for element in np.nditer(arr2):
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12

- bestimme mittels einer Standard Funktion in numpy den Datentyp des Arrays

In [158]:
arr2.dtype

dtype('int64')

- splitte das Array mittels einer Standard Funktion in numpy nachdem zweiten Element auf

In [159]:
left, right = np.split(arr2, 2, axis=1)
print(left)
print(right)

[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]

- bestimme die Position des Elements = 6 in dem Array mittels einer Standard Funktion in numpy
- where

In [160]:
print(np.where(arr2 == 6))

(array([1]), array([1]))

- erstelle ein Array mittels einer Standard Funktion in numpy bei dem jedes `zweite Element` angezeigt wird beginnend bei `1` und endet bei `20`

In [161]:
last_arr = np.arange(1, 21, 2)
last_arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])