# Aufgabenblatt 9: Transformieren

importiere die relevanten Bibliotheken
- pandas
- random

In [1]:
import pandas as pd
import random

## Aufgabe 1: lambda
### a) Basis - Subtraktion 
- subtrahiere `42` von dem Basiswert `100` mit einer `Lambda Funktion`
- gebe in einem print statement und mittels format
    - sowohl den Basiswert 
    - als auch subtahtionswert 
    - und das Ergebnis aus

lambda_minus(100-42)=58

### b) Basis - Durchschnittsberechnung 
- berechne den Durchschnitt aus der Liste `1,2,3,4,5,6,7,8,9` mit einer `Lambda Funktion` 
- erstelle eine Liste mittels for loop
- erstelle eine Lambda Funktion
     - Durchschnitt ist die Summe durch die Anzahl der Elemente
- gebe sowohl die Liste als auch das Durchschnittsrgebnis mittels print aus

lambda_average([1, 2, 3, 4, 5, 6, 7, 8, 9])=5.0

### c) Basis - positiv Zahl
- prüfe generisch, ob die einzelne Listeneintäge `[-1, 0, 1, True]` positiv sind mit einer `Lambda Funktion`
- gebe mit print mittels `format` aus, welche Zahl überprüft wurde ob diese positiv ist
<br><br> **Tipp:** Lambda_Function wird in einem for-loop aufgerufen

lambda_positive(-1)=False
lambda_positive(0)=False
lambda_positive(1)=True
lambda_positive(True)=True

## Aufgabe 2: map
### a) Listenelement * 4
- erstelle eine Liste von `1 bis 20` in der aber nur jedes `zweite Element` erstellt wird
- multipliziere jeden einzelnen Listenwert mit 4
- erstelle eine Liste mit einem for Loop

[4, 12, 20, 28, 36, 44, 52, 60, 68, 76]

- nun `löse` die Aufgabenstellung aus der Celle vorher mit einer `lambda Funktion`
- **Tipp:** map muss auch verwendet werden

[4, 12, 20, 28, 36, 44, 52, 60, 68, 76]

### b) Bestimme die Abweichung zum Durchschnittswert
- berechne den Durchschnitt aus der Liste `1,2,3,4,5,6,7,8,9` und gebe für jedes Element die Abweichung zum Durchschnittswert in einer Liste wieder
- programmiere die Lösung mittels for loop
- erstelle eine Variable average
- gebe es mit der print Funktion aus

neue Daten= [-4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, 4.0]

- `Exkurs` verkürzte Schreibweise mittels List-Comprehension

neue Daten = [-4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, 4.0]

- nutze für die Aufgabe die kombination aus `map und lambda` Funktion

map und filter= [-4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, 4.0]

### c) Basis lambda auf 2 Variablen
- addiere die jeweiligen gleichen Listenelemente aus den beiden Listen `list_one und list_two` mittels der map-lambda-Kombination
<br><br> list_one = 1, 2, 3
<br> list_two = 4, 5, 6, 7

[5, 7, 9]

- Warum funktioniert es nicht, wenn z.B. nicht in beiden Listen ein Listenelement vorhanden ist

In [ ]:
# dein Text...

### d) bearbeiten eines 2-dimensionalem Array
arr_2d = (1, 'a'), (2, 'b'), (3, 'c')
- erstelle als erstes das 2-dimensionale Array `arr_2d`
- gebe nur die Buchstaben aus dem Array wieder (a,b,c)

['a', 'b', 'c']

- multipliziere jeweils das `erste` Element aus dem `arr_2d` mitdem Faktor 3

[3, 6, 9]

### e) konvertiere eine Temperatur von celsius in Farenheit mittels lambda
- rechne die Werte aus der Temperaturliste (`14.0, 32.0, 50.0, 68.0`) von Fahrneheit in Celsius um
<br><br>  **Tipp** 
    - `Celsius = 9/5 * Fahrneheit+32` 
    - 14 Fahrenheit entsprechen -10 Grad Celsius

[-10.0, 0.0, 10.0, 20.0]

## Aufgabe 3: filter
### a) Basis
- erstelle eine Liste mit dem Namen `random_list` 
    - mit 20 zufälligen Werten im Wertebereich `-4 bis 10` 
    - Durch die zufälligen Werte in Liste `random_list` werden die angezeigten Lösungen nicht mit euren Lösungen identisch sein. Die angezeigten Lösungen sollen euch nur einen Indikator anzeigen, was bei den Aufgaben gemacht werden soll <br><br>
- gebe alle Werte aus der Liste `random_list` welche zwischen `1 und 6` aus
    - speichere die Werte zwischen `1 und 6` in einer neuen Liste mit dem Namen `neue_liste`
    - **Tipp:** erstelle die Liste `neue_liste` mit einem for Loop, welche diese Werte angibt

Random_Liste= [10, 0, 1, -4, -1, 4, -4, 10, 9, 6, 1, 3, 7, 2, 10, -4, -2, 1, 0, 2]
Neue_Liste= [1, 4, 6, 1, 3, 2, 1, 2]

- verkürzte Schreibweise mit einer list-comprehension für die Aufgabe aus der Celle davor

[1, 4, 6, 1, 3, 2, 1, 2]

- nutze für die Aufgabe aus der Celle davor eine Kombination aus der `filter-lambda` Funktion

map&filter transformed= [1, 4, 6, 1, 3, 2, 1, 2]

### b)
- importiere die Datei data_merged_save unter dem Variabelnnamen `data_groupby`
    - es soll keine Column welche den Namen `Unnamend` erhält importiert werden
    - bestimmt den richtigen `Seperator`
    - gebe eine `Encoding` Function mit an

- gebe alle Records/rows an, welche eine 1 in ihrem Index haben
- benutze hierfür die `filter` Funktion
<br><br> 15540 rows × 59 columns

,RECHNUNGSNUMMER,GETRAENK,REGION,BESTELLNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,...,Newsletter_3_Cupon_2023,Newsletter_4_Cupon_2023,Newsletter_5_Cupon_2023,Newsletter_6_Cupon_2023,Newsletter_7_Cupon_2023,Newsletter_8_Cupon_2023,Newsletter_9_Cupon_2023,Newsletter_10_Cupon_2023,Newsletter_11_Cupon_2023,Newsletter_12_Cupon_2023
1,RE_2020_1,Whisky,EU,1,35.0,111.97,0.0,111.97,0.00,83.98,...,nein,nein,nein,nein,nein,nein,ja,nein,nein,ja
10,RE_2020_1006,Whisky,EU,1006,77.0,116.93,0.0,116.93,0.00,87.70,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,RE_2020_1007,Wein,EU,1007,44.0,193.94,5.0,184.24,-9.70,145.45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,RE_2020_1008,Whisky,EU,1008,36.0,88.82,10.0,79.94,-8.88,66.61,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,RE_2020_1009,Whisky,USA,1009,8.0,219.38,0.0,219.38,0.00,164.54,...,ja,ja,nein,ja,ja,ja,nein,ja,ja,nein
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25031,RE_2023_9956,Whisky,EU,9956,82.0,196.73,0.0,196.73,0.00,147.55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25041,RE_2023_9965,Champagner,USA,9965,289.0,203.34,0.0,203.34,0.00,152.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25051,RE_2023_9974,Whisky,EU,9974,264.0,107.45,5.0,102.08,-5.37,80.59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25061,RE_2023_9983,Whisky,EU,9983,9.0,145.54,5.0,138.26,-7.28,109.16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25071,RE_2023_9992,Whisky,EU,9992,219.0,209.29,0.0,209.29,0.00,156.97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- gebe alle Columns an, welche eine 5 in ihrem Columnnamen haben
- Was verändert sich zu der Aufgabe davor?

,Newsletter_5_Cupon_2020,Newsletter_5_Cupon_2021,Newsletter_5_Cupon_2022,Newsletter_5_Cupon_2023
0,nein,NaN,nein,NaN
1,NaN,ja,nein,nein
2,nein,nein,nein,NaN
3,NaN,nein,nein,ja
4,ja,NaN,ja,nein
...,...,...,...,...
25074,NaN,NaN,NaN,NaN
25075,nein,nein,nein,ja
25076,NaN,NaN,NaN,NaN
25077,NaN,NaN,ja,NaN
25078,NaN,NaN,ja,ja

## Aufgabe 4: kombiniere die Function map, filter, lambda
- erstelle eine Liste mit dem Namen `map_filter` welche die Werte `-50,20,-45,25,-42` enthält
- addiere den Wert 42 zu den jeweiligen Listenelementen aus `map_filter` 
- gebe anschliessend nur die Werte aus, welche durch 6 dividierbar sind und keinen Rest haben

map&filter= [-8, 62, 0]

## Aufgabe 5: groupby
- Datenbasis ist der Dateframe `data_groupby`
- gebe das summierte Ergebnis für die Regionen aus `data_groupby` an für alle Columns

,BESTELLNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD
REGION,,,,,,,,
Asien,18969260.0,590378.0,7.769392e+05,6245.0,771262.88,-9796.34,582691.90,825146.40
EU,48861183.0,1511512.0,1.956457e+06,15810.0,1941764.08,-24634.30,1467342.45,2078032.50
USA,29430009.0,897042.0,1.163693e+06,9135.0,1155610.28,-14262.37,872839.56,1236465.95

- gebe das summierte Ergebnis für die Regionen an
- für die  Spalten wie `LISTENPREIS, VERKAUFSPREIS, RABATT_PREIS, EINKAUFPREIS, VK_PERIS_IN_USD`

,LISTENPREIS,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD
REGION,,,,,
Asien,7.781273e+05,768484.19,-9746.48,583730.23,826582.12
EU,1.945383e+06,1919909.87,-25380.93,1459224.01,2065144.40
USA,1.152012e+06,1137868.15,-14011.30,864148.55,1223932.32

- zähle alle Bestellungen, welche ein Kunde getätigt hat 
- speicher das Ergebnis ist der Variabel data_groupby_count
<br> length: 299

KUNDENNUMMER
1.0      123
2.0      112
3.0      119
4.0      118
5.0      144
        ...
295.0     24
296.0     36
297.0     39
298.0     29
299.0     24
Name: BESTELLNUMMER, Length: 299, dtype: int64

- summiere die Verkaufpreise pro Kunden und Getränkeart
- speicher diese unter der Variabel `data_groupby_verkauf`
<br> 1195 rows

KUNDENNUMMER  GETRAENK
1.0           Champagner     1266.89
              Rum            1784.16
              Wein           5162.93
              Whisky        10783.60
2.0           Champagner     2108.10
                              ...
298.0         Whisky         2966.21
299.0         Champagner      120.63
              Rum             329.86
              Wein            907.68
              Whisky         2553.16
Name: VERKAUFSPREIS, Length: 1195, dtype: float64

- füge die beiden Variabeln `data_groupby_verkauf und data_groupby_count` in einen neuen Dataframe `data` zusammen 
- verändere anschliessend den Columnnamen `BESTELLNUMMER` in `Count`
<br><br>
1195 rows × 4 columns

      KUNDENNUMMER    GETRAENK  VERKAUFSPREIS  Count
0              1.0  Champagner        1266.89    123
1              1.0         Rum        1784.16    123
2              1.0        Wein        5162.93    123
3              1.0      Whisky       10783.60    123
4              2.0  Champagner        2108.10    112
...            ...         ...            ...    ...
1190         298.0      Whisky        2966.21     29
1191         299.0  Champagner         120.63     24
1192         299.0         Rum         329.86     24
1193         299.0        Wein         907.68     24
1194         299.0      Whisky        2553.16     24

[1195 rows x 4 columns]

- bestimme den median pro GETRAENK 
- füge diesen an den Dataframe `data` unter den Columnnamen `MEDIAN` an <br><br>
- Tipp: nutze transform
<br><br>1195 rows × 5 columns

      KUNDENNUMMER    GETRAENK  VERKAUFSPREIS  Count  MEDIAN
0              1.0  Champagner        1266.89    123    88.5
1              1.0         Rum        1784.16    123    88.0
2              1.0        Wein        5162.93    123    88.0
3              1.0      Whisky       10783.60    123    88.0
4              2.0  Champagner        2108.10    112    88.5
...            ...         ...            ...    ...     ...
1190         298.0      Whisky        2966.21     29    88.0
1191         299.0  Champagner         120.63     24    88.5
1192         299.0         Rum         329.86     24    88.0
1193         299.0        Wein         907.68     24    88.0
1194         299.0      Whisky        2553.16     24    88.0

[1195 rows x 5 columns]

- gebe den minimalen `VERKAUFSPREIS pro KUNDENNUMMER` in einer neuen Column wieder
<br><br>
1195 rows × 5 columns

      KUNDENNUMMER    GETRAENK  VERKAUFSPREIS  Count  MINIMAL_WERT
0              1.0  Champagner        1266.89    123       1266.89
1              1.0         Rum        1784.16    123       1266.89
2              1.0        Wein        5162.93    123       1266.89
3              1.0      Whisky       10783.60    123       1266.89
4              2.0  Champagner        2108.10    112       2108.10
...            ...         ...            ...    ...           ...
1190         298.0      Whisky        2966.21     29        265.67
1191         299.0  Champagner         120.63     24        120.63
1192         299.0         Rum         329.86     24        120.63
1193         299.0        Wein         907.68     24        120.63
1194         299.0      Whisky        2553.16     24        120.63

[1195 rows x 5 columns]

- sortiere den Dataframe `data_groupby`
    - wobei die `KUNDENNUMMER` als erstes sortiert werden soll und zwar `aufsteigend` 
    - die zweite Sortiercolumn soll der `VERKAUFSPREIS` sein, diese soll `absteigend` sortiert werden soll
- erstelle einen sortierten Sub-Dataframes `data_sort` mit den Columns `KUNDENNUMMER, VERKAUFSPREIS, GETRAENK und REGION`
- erstelle eine neue Column `Kundenbestellungen_count`
    - in der Column soll pro Kundennummer fortlaufend alle zuvor sortierten Bstellungen gezählt werden beginnend bei 1
<br><br> **Tipp: cumcount()**
<br> 25079 rows × 5 columns

,KUNDENNUMMER,VERKAUFSPREIS,GETRAENK,REGION,Kundenbestellungen_count
6019,1.0,229.27,Wein,USA,1
5018,1.0,227.85,Champagner,EU,2
2930,1.0,227.33,Wein,EU,3
1192,1.0,226.52,Wein,EU,4
18809,1.0,222.08,Whisky,EU,5
...,...,...,...,...,...
17474,299.0,109.64,Wein,Asien,20
24184,299.0,108.71,Whisky,USA,21
17542,299.0,103.54,Wein,EU,22
17332,299.0,94.29,Whisky,Asien,23
20044,299.0,86.97,Whisky,USA,24

- erstelle einen neuen Dataframes mit einem beliebigen namen
    - Die Bedingung für den neuen Dataframes ist, dass nur pro Kunde die 60 grössten Verkaufpreise beinhaltet sind
    <br>
<br> 16459 rows × 5 columns

,KUNDENNUMMER,VERKAUFSPREIS,GETRAENK,REGION,Kundenbestellungen_count
6019,1.0,229.27,Wein,USA,1
5018,1.0,227.85,Champagner,EU,2
2930,1.0,227.33,Wein,EU,3
1192,1.0,226.52,Wein,EU,4
18809,1.0,222.08,Whisky,EU,5
...,...,...,...,...,...
17474,299.0,109.64,Wein,Asien,20
24184,299.0,108.71,Whisky,USA,21
17542,299.0,103.54,Wein,EU,22
17332,299.0,94.29,Whisky,Asien,23
20044,299.0,86.97,Whisky,USA,24

## Aufgabe 6: pivot_table
- summiere die `Verkaufpreise` pro `Kunde` und `Getränkeart` aus dem DataFrame data_groupby mittels pivot_table

KUNDENNUMMER       1.0                                   2.0             \
GETRAENK      Champagner      Rum     Wein   Whisky Champagner      Rum
VERKAUFSPREIS    1266.89  1784.16  5162.93  10783.6     2108.1  2156.23

KUNDENNUMMER                        3.0             ...    297.0           \
GETRAENK          Wein  Whisky Champagner      Rum  ...     Wein   Whisky
VERKAUFSPREIS  4201.89  8961.7    1496.53  2307.32  ...  1445.59  2759.91

KUNDENNUMMER       298.0                               299.0                  \
GETRAENK      Champagner     Rum    Wein   Whisky Champagner     Rum    Wein
VERKAUFSPREIS     297.75  265.67  729.55  2966.21     120.63  329.86  907.68

KUNDENNUMMER
GETRAENK        Whisky
VERKAUFSPREIS  2553.16

[1 rows x 1195 columns]

erstelle einen Pivot_table
- indem jede Kundennummer einmalig ist (299 rows)
- die Rechnungsnummern neben einander stehen (25709 col)
- und befülle die NaN werte mit 0

KUNDENNUMMER           1.0                                           \
RECHNUNGSNUMMER RE_2020_1125 RE_2020_1207 RE_2020_1243 RE_2020_1306
KUNDENNUMMER
1.0                   200.27       115.44       111.16       191.92
2.0                     0.00         0.00         0.00         0.00
3.0                     0.00         0.00         0.00         0.00
4.0                     0.00         0.00         0.00         0.00
5.0                     0.00         0.00         0.00         0.00
...                      ...          ...          ...          ...
295.0                   0.00         0.00         0.00         0.00
296.0                   0.00         0.00         0.00         0.00
297.0                   0.00         0.00         0.00         0.00
298.0                   0.00         0.00         0.00         0.00
299.0                   0.00         0.00         0.00         0.00

KUNDENNUMMER                                                        \
RECHNUNGSNUMMER RE_2020_145 RE_2020_1498 RE_2020_1601 RE_2020_1809
KUNDENNUMMER
1.0                   82.93       118.47       174.85       194.08
2.0                    0.00         0.00         0.00         0.00
3.0                    0.00         0.00         0.00         0.00
4.0                    0.00         0.00         0.00         0.00
5.0                    0.00         0.00         0.00         0.00
...                     ...          ...          ...          ...
295.0                  0.00         0.00         0.00         0.00
296.0                  0.00         0.00         0.00         0.00
297.0                  0.00         0.00         0.00         0.00
298.0                  0.00         0.00         0.00         0.00
299.0                  0.00         0.00         0.00         0.00

KUNDENNUMMER                              ...        299.0              \
RECHNUNGSNUMMER RE_2020_1851 RE_2020_256  ... RE_2023_5939 RE_2023_673
KUNDENNUMMER                              ...
1.0                   187.03      219.57  ...         0.00        0.00
2.0                     0.00        0.00  ...         0.00        0.00
3.0                     0.00        0.00  ...         0.00        0.00
4.0                     0.00        0.00  ...         0.00        0.00
5.0                     0.00        0.00  ...         0.00        0.00
...                      ...         ...  ...          ...         ...
295.0                   0.00        0.00  ...         0.00        0.00
296.0                   0.00        0.00  ...         0.00        0.00
297.0                   0.00        0.00  ...         0.00        0.00
298.0                   0.00        0.00  ...         0.00        0.00
299.0                   0.00        0.00  ...       179.08      164.94

KUNDENNUMMER                                                         \
RECHNUNGSNUMMER RE_2023_7109 RE_2023_7408 RE_2023_8228 RE_2023_8402
KUNDENNUMMER
1.0                     0.00         0.00         0.00         0.00
2.0                     0.00         0.00         0.00         0.00
3.0                     0.00         0.00         0.00         0.00
4.0                     0.00         0.00         0.00         0.00
5.0                     0.00         0.00         0.00         0.00
...                      ...          ...          ...          ...
295.0                   0.00         0.00         0.00         0.00
296.0                   0.00         0.00         0.00         0.00
297.0                   0.00         0.00         0.00         0.00
298.0                   0.00         0.00         0.00         0.00
299.0                 210.95       154.93       120.63       173.64

KUNDENNUMMER
RECHNUNGSNUMMER RE_2023_919 RE_2023_9193 RE_2023_965 RE_2023_9720
KUNDENNUMMER
1.0                    0.00         0.00        0.00         0.00
2.0                    0.00         0.00        0.00         0.00
3.0                    0.00         0.00        0.00         0.00
4.0                    0.00         0.00        0.00         0.00
5.0                    0.00         0.00        0.00         0.00
...                     ...          ...         ...          ...
295.0                  0.00         0.00        0.00         0.00
296.0                  0.00         0.00        0.00         0.00
297.0                  0.00         0.00        0.00         0.00
298.0                  0.00         0.00        0.00         0.00
299.0                201.04       108.71      215.35       221.94

[299 rows x 25079 columns]

- erstelle einen Dataframes mittels pivot_table, 
    - welcher muti_columns besitzt `'KUNDENNUMMER','RECHNUNGSNUMMER'`
- füge die Multi_Columns zusammen in eine Cloumn mittels map <br><br>
**Tipp:** Kundennummer sollte den Datentyp String enthalten

KUNDENNUMMER             1.0                                         \
RECHNUNGSNUMMER RE_2020_1125 RE_2020_1207 RE_2020_1243 RE_2020_1306
KUNDENNUMMER
1.0                   200.27       115.44       111.16       191.92
10.0                    0.00         0.00         0.00         0.00
100.0                   0.00         0.00         0.00         0.00
101.0                   0.00         0.00         0.00         0.00
102.0                   0.00         0.00         0.00         0.00
...                      ...          ...          ...          ...
95.0                    0.00         0.00         0.00         0.00
96.0                    0.00         0.00         0.00         0.00
97.0                    0.00         0.00         0.00         0.00
98.0                    0.00         0.00         0.00         0.00
99.0                    0.00         0.00         0.00         0.00

KUNDENNUMMER                                                        \
RECHNUNGSNUMMER RE_2020_145 RE_2020_1498 RE_2020_1601 RE_2020_1809
KUNDENNUMMER
1.0                   82.93       118.47       174.85       194.08
10.0                   0.00         0.00         0.00         0.00
100.0                  0.00         0.00         0.00         0.00
101.0                  0.00         0.00         0.00         0.00
102.0                  0.00         0.00         0.00         0.00
...                     ...          ...          ...          ...
95.0                   0.00         0.00         0.00         0.00
96.0                   0.00         0.00         0.00         0.00
97.0                   0.00         0.00         0.00         0.00
98.0                   0.00         0.00         0.00         0.00
99.0                   0.00         0.00         0.00         0.00

KUNDENNUMMER                              ...         99.0               \
RECHNUNGSNUMMER RE_2020_1851 RE_2020_256  ... RE_2023_7572 RE_2023_7833
KUNDENNUMMER                              ...
1.0                   187.03      219.57  ...         0.00         0.00
10.0                    0.00        0.00  ...         0.00         0.00
100.0                   0.00        0.00  ...         0.00         0.00
101.0                   0.00        0.00  ...         0.00         0.00
102.0                   0.00        0.00  ...         0.00         0.00
...                      ...         ...  ...          ...          ...
95.0                    0.00        0.00  ...         0.00         0.00
96.0                    0.00        0.00  ...         0.00         0.00
97.0                    0.00        0.00  ...         0.00         0.00
98.0                    0.00        0.00  ...         0.00         0.00
99.0                    0.00        0.00  ...        85.23       112.11

KUNDENNUMMER                                                       \
RECHNUNGSNUMMER RE_2023_7866 RE_2023_7918 RE_2023_80 RE_2023_8249
KUNDENNUMMER
1.0                     0.00         0.00       0.00         0.00
10.0                    0.00         0.00       0.00         0.00
100.0                   0.00         0.00       0.00         0.00
101.0                   0.00         0.00       0.00         0.00
102.0                   0.00         0.00       0.00         0.00
...                      ...          ...        ...          ...
95.0                    0.00         0.00       0.00         0.00
96.0                    0.00         0.00       0.00         0.00
97.0                    0.00         0.00       0.00         0.00
98.0                    0.00         0.00       0.00         0.00
99.0                  124.57       206.73     229.58       159.96

KUNDENNUMMER
RECHNUNGSNUMMER RE_2023_8448 RE_2023_8849 RE_2023_9548 RE_2023_984
KUNDENNUMMER
1.0                     0.00         0.00         0.00        0.00
10.0                    0.00         0.00         0.00        0.00
100.0                   0.00         0.00         0.00        0.00
101.0                   0.00         0.00         0.00        0.00
102.0                   0.00         0.00         0.00        0.00
...                      ...          ...          ...         ...
95.0                    0.00         0.00         0.00        0.00
96.0                    0.00         0.00         0.00        0.00
97.0                    0.00         0.00         0.00        0.00
98.0                    0.00         0.00         0.00        0.00
99.0                  227.54       152.19       167.82      159.17

[299 rows x 25079 columns]

,1.0_RE_2020_1125,1.0_RE_2020_1207,1.0_RE_2020_1243,1.0_RE_2020_1306,1.0_RE_2020_145,1.0_RE_2020_1498,1.0_RE_2020_1601,1.0_RE_2020_1809,1.0_RE_2020_1851,1.0_RE_2020_256,...,99.0_RE_2023_7572,99.0_RE_2023_7833,99.0_RE_2023_7866,99.0_RE_2023_7918,99.0_RE_2023_80,99.0_RE_2023_8249,99.0_RE_2023_8448,99.0_RE_2023_8849,99.0_RE_2023_9548,99.0_RE_2023_984
KUNDENNUMMER,,,,,,,,,,,,,,,,,,,,,
1.0,200.27,115.44,111.16,191.92,82.93,118.47,174.85,194.08,187.03,219.57,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
10.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
100.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
101.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
102.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
96.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
97.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
98.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
99.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,85.23,112.11,124.57,206.73,229.58,159.96,227.54,152.19,167.82,159.17