# Aufgabenblatt 9: Transformieren

importiere die relevanten Bibliotheken
- pandas
- random

In [223]:
import numpy as np
import pandas as pd
import random

## Aufgabe 1: lambda
### a) Basis - Subtraktion 
- subtrahiere `42` von dem Basiswert `100` mit einer `Lambda Funktion`
- gebe in einem print statement und mittels format
    - sowohl den Basiswert 
    - als auch subtahtionswert 
    - und das Ergebnis aus

In [224]:
subtract = lambda x, y: x - y

minuend = 100
subtrahend = 42

# Ausgabe mit format
print(f"lambda_minus({minuend} - {subtrahend}) = {subtract(minuend, subtrahend)})")

lambda_minus(100 - 42) = 58)

### b) Basis - Durchschnittsberechnung 
- berechne den Durchschnitt aus der Liste `1,2,3,4,5,6,7,8,9` mit einer `Lambda Funktion` 
- erstelle eine Liste mittels for loop
- erstelle eine Lambda Funktion
     - Durchschnitt ist die Summe durch die Anzahl der Elemente
- gebe sowohl die Liste als auch das Durchschnittsrgebnis mittels print aus

In [225]:
average_list = []
for i in range(1,10):
    average_list.append(i)

average = lambda x: sum(x) / len(x)

print(f"lambda_average({average_list}) = {average(average_list)}")

lambda_average([1, 2, 3, 4, 5, 6, 7, 8, 9]) = 5.0

### c) Basis - positiv Zahl
- prüfe generisch, ob die einzelne Listeneintäge `[-1, 0, 1, True]` positiv sind mit einer `Lambda Funktion`
- gebe mit print mittels `format` aus, welche Zahl überprüft wurde ob diese positiv ist
<br><br> **Tipp:** Lambda_Function wird in einem for-loop aufgerufen

In [226]:
positive_list = [-1, 0, 1, True]

lambda_positive = lambda x: x > 0

for item in positive_list:
    print(f"lambda_positive({item}) = {lambda_positive(item)}")

lambda_positive(-1) = False
lambda_positive(0) = False
lambda_positive(1) = True
lambda_positive(True) = True

## Aufgabe 2: map
### a) Listenelement * 4
- erstelle eine Liste von `1 bis 20` in der aber nur jedes `zweite Element` erstellt wird
- multipliziere jeden einzelnen Listenwert mit 4
- erstelle eine Liste mit einem for Loop

In [227]:
list_times_four = []

for i in range(1,21,2):
    list_times_four.append(i)

result = [x * 4 for x in list_times_four]

for item in result:
    item *= 4

print(result)

[4, 12, 20, 28, 36, 44, 52, 60, 68, 76]

- nun `löse` die Aufgabenstellung aus der Celle vorher mit einer `lambda Funktion`
- **Tipp:** map muss auch verwendet werden

In [228]:
result = list(map(lambda x: x *4, list_times_four))

print(result)

[4, 12, 20, 28, 36, 44, 52, 60, 68, 76]

### b) Bestimme die Abweichung zum Durchschnittswert
- berechne den Durchschnitt aus der Liste `1,2,3,4,5,6,7,8,9` und gebe für jedes Element die Abweichung zum Durchschnittswert in einer Liste wieder
- programmiere die Lösung mittels for loop
- erstelle eine Variable average
- gebe es mit der print Funktion aus

In [229]:
my_list = []

for i in range(1,10):
    my_list.append(i)

list_average = sum(my_list) / len(my_list)

list_delta = []
for value in my_list:
    list_delta.append(value - list_average)

print(f"neue Daten = {list_delta}")

neue Daten = [-4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, 4.0]

- `Exkurs` verkürzte Schreibweise mittels List-Comprehension

In [230]:
my_list = []

for i in range(1,10):
    my_list.append(i)

list_average = sum(my_list) / len(my_list)

list_delta = [value - list_average for value in my_list]

print(f"neue Daten = {list_delta}")

neue Daten = [-4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, 4.0]

- nutze für die Aufgabe die kombination aus `map und lambda` Funktion

In [231]:
my_list = []

for i in range(1,10):
    my_list.append(i)

list_average = average(my_list)

list_delta = list(map(lambda x: x - list_average, my_list))
print(f"map und filter = {list_delta}")

map und filter = [-4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, 4.0]

### c) Basis lambda auf 2 Variablen
- addiere die jeweiligen gleichen Listenelemente aus den beiden Listen `list_one und list_two` mittels der map-lambda-Kombination
<br><br> list_one = 1, 2, 3
<br> list_two = 4, 5, 6, 7

In [232]:
list_one = [1,2,3]
list_two = [4,5,6,7]

print(list(map(lambda x,y: x + y, list_one, list_two)))

[5, 7, 9]

- Warum funktioniert es nicht, wenn z.B. nicht in beiden Listen ein Listenelement vorhanden ist

In [233]:
# Map geht solange durch die listenelemente solange es die nötigen parameter bekommt: Liste ist zu Ende -> iteriert nicht weiter durch

### d) bearbeiten eines 2-dimensionalem Array
arr_2d = (1, 'a'), (2, 'b'), (3, 'c')
- erstelle als erstes das 2-dimensionale Array `arr_2d`
- gebe nur die Buchstaben aus dem Array wieder (a,b,c)

In [234]:
arr_2d = np.array([[1,"a"], [2,"b"], [3,"c"]], dtype=object)
print(arr_2d[:, 1])

['a' 'b' 'c']

- multipliziere jeweils das `erste` Element aus dem `arr_2d` mitdem Faktor 3

In [235]:
arr_2d[:,0] = list(map(lambda x: x*3, arr_2d[:,0]))
print(arr_2d[:,0])

[3 6 9]

### e) konvertiere eine Temperatur von celsius in Farenheit mittels lambda
- rechne die Werte aus der Temperaturliste (`14.0, 32.0, 50.0, 68.0`) von Fahrneheit in Celsius um
<br><br>  **Tipp** 
    - `Celsius = 9/5 * Fahrneheit+32` 
    - 14 Fahrenheit entsprechen -10 Grad Celsius

In [236]:
temperature_list = [14.0, 32.0, 50.0, 68.0]

temperature_list = list(map(lambda x: (x-32) * 5/9 , temperature_list))
print(temperature_list)

[-10.0, 0.0, 10.0, 20.0]

## Aufgabe 3: filter
### a) Basis
- erstelle eine Liste mit dem Namen `random_list` 
    - mit 20 zufälligen Werten im Wertebereich `-4 bis 10` 
    - Durch die zufälligen Werte in Liste `random_list` werden die angezeigten Lösungen nicht mit euren Lösungen identisch sein. Die angezeigten Lösungen sollen euch nur einen Indikator anzeigen, was bei den Aufgaben gemacht werden soll <br><br>
- gebe alle Werte aus der Liste `random_list` welche zwischen `1 und 6` aus
    - speichere die Werte zwischen `1 und 6` in einer neuen Liste mit dem Namen `neue_liste`
    - **Tipp:** erstelle die Liste `neue_liste` mit einem for Loop, welche diese Werte angibt

In [237]:
random_list = [random.randint(-4,10) for i in range(20)]
new_list = []
for i in random_list:
    if 1 <= i <= 6:
        new_list.append(i)
print(random_list)
print(new_list)

[2, -3, -4, 1, 3, 10, 1, -3, 8, 5, -1, 1, 2, 6, 10, 9, 2, -1, 3, 7]
[2, 1, 3, 1, 5, 1, 2, 6, 2, 3]

- verkürzte Schreibweise mit einer list-comprehension für die Aufgabe aus der Celle davor

In [238]:
new_list = [x for x in random_list if 1 <= x <= 6]
print(new_list)

[2, 1, 3, 1, 5, 1, 2, 6, 2, 3]

- nutze für die Aufgabe aus der Celle davor eine Kombination aus der `filter-lambda` Funktion

In [239]:
new_list = list(filter(lambda x: 1 <= x <= 6, random_list))
print(new_list)

[2, 1, 3, 1, 5, 1, 2, 6, 2, 3]

### b)
- importiere die Datei data_merged_save unter dem Variabelnnamen `data_groupby`
    - es soll keine Column welche den Namen `Unnamend` erhält importiert werden
    - bestimmt den richtigen `Seperator`
    - gebe eine `Encoding` Function mit an

In [240]:
# ich denke mal, dass die csv datei gemeint ist
data_groupby = pd.read_csv("ressources/data_merged_save.csv", sep="\t", encoding="utf-8")
data_groupby = data_groupby.loc[:, ~data_groupby.columns.str.contains("unnamed", case=False)]
data_groupby

,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,...,Newsletter_3_Cupon_2023,Newsletter_4_Cupon_2023,Newsletter_5_Cupon_2023,Newsletter_6_Cupon_2023,Newsletter_7_Cupon_2023,Newsletter_8_Cupon_2023,Newsletter_9_Cupon_2023,Newsletter_10_Cupon_2023,Newsletter_11_Cupon_2023,Newsletter_12_Cupon_2023
0,Rum,Asien,0.0,RE_2020_0,27.0,86.23,0.0,86.23,0.00,64.67,...,nein,ja,nein,ja,ja,nein,ja,nein,nein,ja
1,Wein,EU,1.0,RE_2020_1,87.0,182.93,0.0,182.93,0.00,137.20,...,nein,nein,ja,nein,nein,ja,nein,nein,nein,nein
2,Wein,Asien,2.0,RE_2020_2,76.0,103.97,0.0,103.97,0.00,77.98,...,nein,nein,nein,nein,ja,ja,ja,nein,nein,ja
3,Whisky,USA,3.0,RE_2020_3,44.0,119.95,0.0,119.95,0.00,89.96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Whisky,EU,4.0,RE_2020_4,25.0,217.43,5.0,206.56,-10.87,163.07,...,nein,ja,ja,ja,ja,nein,nein,nein,nein,ja
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25074,Whisky,EU,9995.0,RE_2023_9995,228.0,206.73,0.0,206.73,0.00,155.05,...,nein,nein,nein,nein,nein,ja,nein,nein,nein,nein
25075,Whisky,EU,9996.0,RE_2023_9996,126.0,117.78,0.0,117.78,0.00,88.34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25076,Wein,EU,9997.0,RE_2023_9997,253.0,105.83,0.0,105.83,0.00,79.37,...,nein,nein,ja,nein,nein,nein,ja,nein,nein,ja
25077,Whisky,EU,9998.0,RE_2023_9998,215.0,175.00,0.0,175.00,0.00,131.25,...,ja,nein,nein,nein,nein,nein,nein,nein,nein,ja
25078,Whisky,EU,9999.0,RE_2023_9999,141.0,113.73,10.0,113.73,-11.37,85.30,...,ja,nein,ja,ja,nein,nein,nein,nein,nein,nein

- gebe alle Records/rows an, welche eine 1 in ihrem Index haben
- benutze hierfür die `filter` Funktion
<br><br> 15540 rows × 59 columns

In [241]:
temp = data_groupby.filter(regex="1", axis=0)
temp

,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,...,Newsletter_3_Cupon_2023,Newsletter_4_Cupon_2023,Newsletter_5_Cupon_2023,Newsletter_6_Cupon_2023,Newsletter_7_Cupon_2023,Newsletter_8_Cupon_2023,Newsletter_9_Cupon_2023,Newsletter_10_Cupon_2023,Newsletter_11_Cupon_2023,Newsletter_12_Cupon_2023
1,Wein,EU,1.0,RE_2020_1,87.0,182.93,0.0,182.93,0.00,137.20,...,nein,nein,ja,nein,nein,ja,nein,nein,nein,nein
10,Rum,EU,10.0,RE_2020_10,41.0,164.81,0.0,164.81,0.00,123.61,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Rum,EU,11.0,RE_2020_11,82.0,161.34,0.0,161.34,0.00,121.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Whisky,USA,12.0,RE_2020_12,70.0,97.09,0.0,97.09,0.00,72.82,...,nein,nein,nein,nein,nein,ja,nein,nein,ja,ja
13,Whisky,USA,13.0,RE_2020_13,75.0,203.63,0.0,203.63,0.00,152.72,...,ja,nein,ja,nein,ja,ja,ja,nein,ja,ja
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25031,Whisky,EU,9956.0,RE_2023_9956,256.0,130.80,0.0,130.80,0.00,98.10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25041,Wein,EU,9965.0,RE_2023_9965,26.0,231.32,0.0,231.32,0.00,173.49,...,ja,ja,nein,nein,ja,nein,ja,ja,nein,nein
25051,Whisky,EU,9974.0,RE_2023_9974,136.0,183.17,0.0,183.17,0.00,137.38,...,nein,nein,nein,ja,nein,nein,nein,ja,ja,ja
25061,Whisky,Asien,9983.0,RE_2023_9983,119.0,167.59,0.0,167.59,0.00,125.69,...,nein,nein,nein,ja,ja,ja,nein,nein,ja,nein
25071,Whisky,EU,9992.0,RE_2023_9992,131.0,95.83,5.0,95.83,-4.79,71.87,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- gebe alle Columns an, welche eine 5 in ihrem Columnnamen haben
- Was verändert sich zu der Aufgabe davor?

In [242]:
# man ändert die suche von Spaltenindex auf Columnnamen

In [243]:
temp = data_groupby.filter(regex="5", axis=1)
temp

,Newsletter_5_Cupon_2020,Newsletter_5_Cupon_2021,Newsletter_5_Cupon_2022,Newsletter_5_Cupon_2023
0,ja,nein,nein,nein
1,NaN,NaN,ja,ja
2,NaN,NaN,nein,nein
3,NaN,NaN,NaN,NaN
4,nein,NaN,nein,ja
...,...,...,...,...
25074,NaN,NaN,nein,nein
25075,NaN,NaN,nein,NaN
25076,NaN,NaN,ja,ja
25077,NaN,NaN,ja,nein
25078,NaN,NaN,ja,ja

## Aufgabe 4: kombiniere die Function map, filter, lambda
- erstelle eine Liste mit dem Namen `map_filter` welche die Werte `-50,20,-45,25,-42` enthält
- addiere den Wert 42 zu den jeweiligen Listenelementen aus `map_filter` 
- gebe anschliessend nur die Werte aus, welche durch 6 dividierbar sind und keinen Rest haben

In [244]:
map_filter = [-50, 20, -45, 25, -42]
map_filter = list(map(lambda x: x + 42, map_filter))
print(map_filter)
print(list(filter(lambda x: x % 6 == 0, map_filter)))

# ka wie seine Lösung [-8, 62, 0] sein kann wenn 0 clearly die einzige zahl ist die einen rest von 0 hat wenn sie durch 6 geteilt wird

[-8, 62, -3, 67, 0]
[0]

## Aufgabe 5: groupby
- Datenbasis ist der Dateframe `data_groupby`
- gebe das summierte Ergebnis für die Regionen aus `data_groupby` an für alle Columns

In [245]:
# numeric only, weil die summe von strings keinen Sinn ergibt, man könnte es aber auch machen
temp = data_groupby.groupby("REGION").sum(numeric_only=True)
temp

,BESTELLNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD
REGION,,,,,,,,
Asien,18969260.0,590378.0,7.769392e+05,6245.0,771262.88,-9796.34,582691.90,825146.40
EU,48861183.0,1511512.0,1.956457e+06,15810.0,1941764.08,-24634.30,1467342.45,2078032.50
USA,29430009.0,897042.0,1.163693e+06,9135.0,1155610.28,-14262.37,872839.56,1236465.95

- gebe das summierte Ergebnis für die Regionen an
- für die  Spalten wie `LISTENPREIS, VERKAUFSPREIS, RABATT_PREIS, EINKAUFPREIS, VK_PERIS_IN_USD`

In [246]:
temp = (data_groupby[["LISTENPREIS","VERKAUFSPREIS","RABATT_PREIS","EINKAUFPREIS","VK_PERIS_IN_USD","REGION"]]
        .groupby("REGION")
        .sum(numeric_only=True))

temp

,LISTENPREIS,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD
REGION,,,,,
Asien,7.769392e+05,771262.88,-9796.34,582691.90,825146.40
EU,1.956457e+06,1941764.08,-24634.30,1467342.45,2078032.50
USA,1.163693e+06,1155610.28,-14262.37,872839.56,1236465.95

- zähle alle Bestellungen, welche ein Kunde getätigt hat 
- speicher das Ergebnis ist der Variabel data_groupby_count
<br> length: 299

In [247]:
data_groupby_count = data_groupby.groupby("KUNDENNUMMER").size()
data_groupby_count

KUNDENNUMMER
1.0      132
2.0      115
3.0      119
4.0      118
5.0      120
        ...
295.0     27
296.0     19
297.0     32
298.0     35
299.0     29
Length: 299, dtype: int64

- summiere die Verkaufpreise pro Kunden und Getränkeart
- speicher diese unter der Variabel `data_groupby_verkauf`
<br> 1195 rows

In [248]:
data_groupby_verkauf = data_groupby.groupby(["KUNDENNUMMER", "GETRAENK"])["VERKAUFSPREIS"].sum()
data_groupby_verkauf

KUNDENNUMMER  GETRAENK
1.0           Champagner     1451.92
              Rum            1292.42
              Wein           4317.29
              Whisky        13474.89
2.0           Champagner     2027.52
                              ...
298.0         Whisky         2752.52
299.0         Champagner      290.19
              Rum             827.67
              Wein            669.77
              Whisky         2435.85
Name: VERKAUFSPREIS, Length: 1196, dtype: float64

- füge die beiden Variabeln `data_groupby_verkauf und data_groupby_count` in einen neuen Dataframe `data` zusammen 
- verändere anschliessend den Columnnamen `BESTELLNUMMER` in `Count`
<br><br>
1195 rows × 4 columns

In [249]:
# erstmal die Series objekte in dataframes wandeln indem man den index resetted
data_groupby_count = data_groupby_count.reset_index(name="BESTELLNUMMER")
data_groupby_verkauf = data_groupby_verkauf.reset_index()

# dann mergen
data = data_groupby_verkauf.merge(
    data_groupby_count,
    on="KUNDENNUMMER",
    how="left"
)
data = data.rename(columns={"BESTELLNUMMER": "Count"})
data

      KUNDENNUMMER    GETRAENK  VERKAUFSPREIS  Count
0              1.0  Champagner        1451.92    132
1              1.0         Rum        1292.42    132
2              1.0        Wein        4317.29    132
3              1.0      Whisky       13474.89    132
4              2.0  Champagner        2027.52    115
...            ...         ...            ...    ...
1191         298.0      Whisky        2752.52     35
1192         299.0  Champagner         290.19     29
1193         299.0         Rum         827.67     29
1194         299.0        Wein         669.77     29
1195         299.0      Whisky        2435.85     29

[1196 rows x 4 columns]

- bestimme den median pro GETRAENK 
- füge diesen an den Dataframe `data` unter den Columnnamen `MEDIAN` an <br><br>
- Tipp: nutze transform
<br><br>1195 rows × 5 columns

In [250]:
data["MEDIAN"] = (
    data
        .groupby("GETRAENK")["VERKAUFSPREIS"]
        .transform("median")
)
data

      KUNDENNUMMER    GETRAENK  VERKAUFSPREIS  Count   MEDIAN
0              1.0  Champagner        1451.92    132  1326.68
1              1.0         Rum        1292.42    132  1272.90
2              1.0        Wein        4317.29    132  3255.14
3              1.0      Whisky       13474.89    132  7176.06
4              2.0  Champagner        2027.52    115  1326.68
...            ...         ...            ...    ...      ...
1191         298.0      Whisky        2752.52     35  7176.06
1192         299.0  Champagner         290.19     29  1326.68
1193         299.0         Rum         827.67     29  1272.90
1194         299.0        Wein         669.77     29  3255.14
1195         299.0      Whisky        2435.85     29  7176.06

[1196 rows x 5 columns]

- gebe den minimalen `VERKAUFSPREIS pro KUNDENNUMMER` in einer neuen Column wieder
<br><br>
1195 rows × 5 columns

In [251]:
data["MIN_VERKAUFSPREIS"] = data.groupby("KUNDENNUMMER")["VERKAUFSPREIS"].transform("min")
data

,KUNDENNUMMER,GETRAENK,VERKAUFSPREIS,Count,MEDIAN,MIN_VERKAUFSPREIS
0,1.0,Champagner,1451.92,132,1326.68,1292.42
1,1.0,Rum,1292.42,132,1272.90,1292.42
2,1.0,Wein,4317.29,132,3255.14,1292.42
3,1.0,Whisky,13474.89,132,7176.06,1292.42
4,2.0,Champagner,2027.52,115,1326.68,1668.02
...,...,...,...,...,...,...
1191,298.0,Whisky,2752.52,35,7176.06,218.99
1192,299.0,Champagner,290.19,29,1326.68,290.19
1193,299.0,Rum,827.67,29,1272.90,290.19
1194,299.0,Wein,669.77,29,3255.14,290.19
1195,299.0,Whisky,2435.85,29,7176.06,290.19

- sortiere den Dataframe `data_groupby`
    - wobei die `KUNDENNUMMER` als erstes sortiert werden soll und zwar `aufsteigend` 
    - die zweite Sortiercolumn soll der `VERKAUFSPREIS` sein, diese soll `absteigend` sortiert werden soll
- erstelle einen sortierten Sub-Dataframes `data_sort` mit den Columns `KUNDENNUMMER, VERKAUFSPREIS, GETRAENK und REGION`
- erstelle eine neue Column `Kundenbestellungen_count`
    - in der Column soll pro Kundennummer fortlaufend alle zuvor sortierten Bstellungen gezählt werden beginnend bei 1
<br><br> **Tipp: cumcount()**
<br> 25079 rows × 5 columns

In [254]:
data_sort = data_groupby[["KUNDENNUMMER", "VERKAUFSPREIS", "GETRAENK", "REGION"]].sort_values(["KUNDENNUMMER", "VERKAUFSPREIS"], ascending=[True, False])

data_sort["KUNDENBESTELLUNGEN_COUNT"] = (
    data_sort
        .groupby("KUNDENNUMMER")
        .cumcount()
        + 1
)

data_sort

       KUNDENNUMMER  VERKAUFSPREIS GETRAENK REGION  KUNDENBESTELLUNGEN_COUNT
5515            1.0         228.04     Wein  Asien                         1
8982            1.0         225.84   Whisky    USA                         2
2597            1.0         225.54   Whisky    USA                         3
1774            1.0         224.96   Whisky     EU                         4
13154           1.0         223.81   Whisky     EU                         5
...             ...            ...      ...    ...                       ...
17587         299.0         101.32   Whisky     EU                        25
21257         299.0          97.67   Whisky     EU                        26
23047         299.0          92.42   Whisky    USA                        27
18520         299.0          91.12      Rum     EU                        28
23703         299.0          83.44   Whisky     EU                        29

[25079 rows x 5 columns]

- erstelle einen neuen Dataframes mit einem beliebigen namen
    - Die Bedingung für den neuen Dataframes ist, dass nur pro Kunde die 60 grössten Verkaufpreise beinhaltet sind
    <br>
<br> 16459 rows × 5 columns

In [256]:
data_top60 = data_sort[
    data_sort["KUNDENBESTELLUNGEN_COUNT"] <= 60
]

data_top60

       KUNDENNUMMER  VERKAUFSPREIS GETRAENK REGION  KUNDENBESTELLUNGEN_COUNT
5515            1.0         228.04     Wein  Asien                         1
8982            1.0         225.84   Whisky    USA                         2
2597            1.0         225.54   Whisky    USA                         3
1774            1.0         224.96   Whisky     EU                         4
13154           1.0         223.81   Whisky     EU                         5
...             ...            ...      ...    ...                       ...
17587         299.0         101.32   Whisky     EU                        25
21257         299.0          97.67   Whisky     EU                        26
23047         299.0          92.42   Whisky    USA                        27
18520         299.0          91.12      Rum     EU                        28
23703         299.0          83.44   Whisky     EU                        29

[16482 rows x 5 columns]

## Aufgabe 6: pivot_table
- summiere die `Verkaufpreise` pro `Kunde` und `Getränkeart` aus dem DataFrame data_groupby mittels pivot_table

In [260]:
# Ich checke die ganze aufgabe 6 straight up nicht

pivot_verkauf = pd.pivot_table(
    data_groupby,
    index="KUNDENNUMMER",
    columns="GETRAENK",
    values="VERKAUFSPREIS",
    aggfunc="sum",
    fill_value=0
)

pivot_verkauf

GETRAENK      Champagner      Rum     Wein    Whisky
KUNDENNUMMER
1.0              1451.92  1292.42  4317.29  13474.89
2.0              2027.52  1668.02  4911.15   8667.67
3.0              1808.25  1647.14  5053.57   9278.62
4.0              1599.09  1988.64  4322.36  10096.37
5.0              1571.85  1176.98  5435.56  10535.60
...                  ...      ...      ...       ...
295.0            1078.05   116.08   520.59   2399.55
296.0             449.01   155.09   829.69   1558.61
297.0             624.29   402.42  1416.37   2861.38
298.0             218.99   466.16  1868.52   2752.52
299.0             290.19   827.67   669.77   2435.85

[299 rows x 4 columns]

erstelle einen Pivot_table
- indem jede Kundennummer einmalig ist (299 rows)
- die Rechnungsnummern neben einander stehen (25709 col)
- und befülle die NaN werte mit 0

In [258]:
pivot_rechnung = pd.pivot_table(
    data_groupby,
    index="KUNDENNUMMER",
    columns="RECHNUNGSNUMMER",
    values="VERKAUFSPREIS",
    aggfunc="sum",
    fill_value=0
)

pivot_rechnung

RECHNUNGSNUMMER,10004,10008,10026,10039,10050,10074,10078,RE_2020_0,RE_2020_1,RE_2020_10,...,RE_2023_9990,RE_2023_9991,RE_2023_9992,RE_2023_9993,RE_2023_9994,RE_2023_9995,RE_2023_9996,RE_2023_9997,RE_2023_9998,RE_2023_9999
KUNDENNUMMER,,,,,,,,,,,,,,,,,,,,,
1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
296.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
297.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
298.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
299.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

- erstelle einen Dataframes mittels pivot_table, 
    - welcher muti_columns besitzt `'KUNDENNUMMER','RECHNUNGSNUMMER'`
- füge die Multi_Columns zusammen in eine Cloumn mittels map <br><br>
**Tipp:** Kundennummer sollte den Datentyp String enthalten

In [259]:
pivot_multi = pd.pivot_table(
    data_groupby,
    index=["KUNDENNUMMER", "RECHNUNGSNUMMER"],
    values="VERKAUFSPREIS",
    aggfunc="sum",
    fill_value=0
)

pivot_multi

                              VERKAUFSPREIS
KUNDENNUMMER RECHNUNGSNUMMER
1.0          RE_2020_1139            112.65
             RE_2020_1215            159.64
             RE_2020_1221            161.46
             RE_2020_1307            117.14
             RE_2020_1364             91.32
...                                     ...
299.0        RE_2023_8924            111.33
             RE_2023_9231            228.97
             RE_2023_9703            137.71
             RE_2023_98              102.48
             RE_2023_9894            149.86

[25079 rows x 1 columns]