# Arbeitsaufgaben 10:

## Aufgabe 1:

- importiere die Bibliothek `pandas`
- lade die Datei `data_merged_save.csv` als Variable `data_basis` ein

In [11]:
def sub_func(value_a:int=0, value_b:int=0, value_c:int=0):
    summ = value_a - value_b - value_c
    return summ
# 0,5 Punkt
sub_func("10",4,3)

TypeError: unsupported operand type(s) for -: 'str' and 'int'

,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD,Newsletter_1_Cupon_2020,Newsletter_2_Cupon_2020,Newsletter_3_Cupon_2020,Newsletter_4_Cupon_2020,...,Newsletter_10_Cupon_2022,Newsletter_11_Cupon_2022,Newsletter_12_Cupon_2022,Newsletter_1_Cupon_2023,Newsletter_2_Cupon_2023,Newsletter_3_Cupon_2023,Newsletter_4_Cupon_2023,Newsletter_5_Cupon_2023,Newsletter_6_Cupon_2023,Newsletter_7_Cupon_2023,Newsletter_8_Cupon_2023,Newsletter_9_Cupon_2023,Newsletter_10_Cupon_2023,Newsletter_11_Cupon_2023,Newsletter_12_Cupon_2023
0,Rum,Asien,0.0,RE_2020_0,27.0,86.23,0.0,86.23,0.00,64.67,92.75,nein,nein,ja,ja,...,nein,nein,ja,nein,nein,nein,ja,nein,ja,ja,nein,ja,nein,nein,ja
1,Wein,EU,1.0,RE_2020_1,87.0,182.93,0.0,182.93,0.00,137.20,196.76,NaN,NaN,NaN,NaN,...,nein,ja,ja,nein,nein,nein,nein,ja,nein,nein,ja,nein,nein,nein,nein
2,Wein,Asien,2.0,RE_2020_2,76.0,103.97,0.0,103.97,0.00,77.98,111.83,NaN,NaN,NaN,NaN,...,nein,nein,ja,nein,nein,nein,nein,nein,nein,ja,ja,ja,nein,nein,ja
3,Whisky,USA,3.0,RE_2020_3,44.0,119.95,0.0,119.95,0.00,89.96,129.02,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Whisky,EU,4.0,RE_2020_4,25.0,217.43,5.0,206.56,-10.87,163.07,222.18,nein,nein,nein,nein,...,nein,nein,nein,nein,ja,nein,ja,ja,ja,ja,nein,nein,nein,nein,ja

Verändere die Ausgabengrösse des Dataframes (also die angezeigten Rows und Columns)auf:
- 10 rows und 30 columns
<br><br>**Tipp** benutze pandas set option

### a) Basis Categorie^
- erstelle eine Series `cat_task` aus den Buchstaben `q, w, e, r` und alle Buchstaben sollen dreimal vorkommen
- wandele den Datentyp anschliessend in eine Categorie

0     q
1     w
2     e
3     r
4     q
     ..
7     r
8     q
9     w
10    e
11    r
Length: 12, dtype: category
Categories (4, object): ['e', 'q', 'r', 'w']

- zeige die umgewandelten Werte (numerische) von `cat_task` an

0     1
1     3
2     0
3     2
4     1
     ..
7     2
8     1
9     3
10    0
11    2
Length: 12, dtype: int8

- zeige alle Kategorien von `cat_task` an

Index(['e', 'q', 'r', 'w'], dtype='object')

- sortiere die Kategorien aufsteigend aus `cat_task`
<br><br>
*Tipp:* nutze sort_values()

2     e
6     e
10    e
0     q
4     q
     ..
7     r
11    r
1     w
5     w
9     w
Length: 12, dtype: category
Categories (4, object): ['e' < 'q' < 'r' < 'w']

- bennen die Kategorie aus `cat_task` von `w` in `z` um 
- speichere die neuen Kategroien in der Variable `cat_task_2`

0     q
1     z
2     e
3     r
4     q
     ..
7     r
8     q
9     z
10    e
11    r
Length: 12, dtype: category
Categories (4, object): ['e', 'q', 'r', 'z']

- füge eine zusätzliche Kategorie `d` zu der Variabel `cat_task_2` hinzu 
- und zähle, wie oft die verschiedenen Ausprägungen vorkommen

e    3
q    3
r    3
z    3
d    0
Name: count, dtype: int64

- gebe alle Kategorien aus `cat_task_2` wieder, welche die Kategorie q, w, e haben
- speichere das neue Ergebenis in einer neuen Variable `cat_task_3`

0     q
2     e
4     q
6     e
8     q
10    e
dtype: category
Categories (4, object): ['e', 'q', 'r', 'z']

- entferne die nicht genutzten Kategorien aus `cat_task_3`

0     q
2     e
4     q
6     e
8     q
10    e
dtype: category
Categories (2, object): ['e', 'q']

### b) Categorie für `data_basis`
- erstelle einen Subframe aus dem Dataframes `data_basis` und aus den Columns: `RECHNUNGSNUMMER, KUNDENNUMMER, GETRAENK, REGION`
- erstelle die Categorie CAT_GETRAENK in einer neuen Column von GETRAENK

      RECHNUNGSNUMMER  KUNDENNUMMER GETRAENK REGION CAT_GETRAENK
0           RE_2020_0          27.0      Rum  Asien          Rum
1           RE_2020_1          87.0     Wein     EU         Wein
2           RE_2020_2          76.0     Wein  Asien         Wein
3           RE_2020_3          44.0   Whisky    USA       Whisky
4           RE_2020_4          25.0   Whisky     EU       Whisky
...               ...           ...      ...    ...          ...
25074    RE_2023_9995         228.0   Whisky     EU       Whisky
25075    RE_2023_9996         126.0   Whisky     EU       Whisky
25076    RE_2023_9997         253.0     Wein     EU         Wein
25077    RE_2023_9998         215.0   Whisky     EU       Whisky
25078    RE_2023_9999         141.0   Whisky     EU       Whisky

[25079 rows x 5 columns]

- schreibe den jeweiligen Integer Wert zu den Kategorien von GETRAENKE in eine neue Column (CAT_GETRAENK_NEW)

- erstelle sogenannte dummie Varibalen für GETRAENK und stelle den jeweiligen Columns GETRAENK_ONE_HOT_ voran und füge diese den URsprungsdaten hinzu
<br><br> **Tipp:** verwende die Funktion get_dummies

,RECHNUNGSNUMMER,KUNDENNUMMER,GETRAENK,REGION,CAT_GETRAENK,CAT_GETRAENK_NEW,GETRAENK_GETRAENK_ONE_HOT__Champagner,GETRAENK_GETRAENK_ONE_HOT__Rum,GETRAENK_GETRAENK_ONE_HOT__Wein,GETRAENK_GETRAENK_ONE_HOT__Whisky
0,RE_2020_0,27.0,Rum,Asien,Rum,1,False,True,False,False
1,RE_2020_1,87.0,Wein,EU,Wein,2,False,False,True,False
2,RE_2020_2,76.0,Wein,Asien,Wein,2,False,False,True,False
3,RE_2020_3,44.0,Whisky,USA,Whisky,3,False,False,False,True
4,RE_2020_4,25.0,Whisky,EU,Whisky,3,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...
25074,RE_2023_9995,228.0,Whisky,EU,Whisky,3,False,False,False,True
25075,RE_2023_9996,126.0,Whisky,EU,Whisky,3,False,False,False,True
25076,RE_2023_9997,253.0,Wein,EU,Wein,2,False,False,True,False
25077,RE_2023_9998,215.0,Whisky,EU,Whisky,3,False,False,False,True
25078,RE_2023_9999,141.0,Whisky,EU,Whisky,3,False,False,False,True

# Aufgabe 2: weitere Datenbearbeitung
- bestimme aus dem Dataframe data_basis in einer neuen Spalte das jeweilige Jahr aus der RECHNUNGSNUMMER

,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD,Newsletter_1_Cupon_2020,Newsletter_2_Cupon_2020,Newsletter_3_Cupon_2020,Newsletter_4_Cupon_2020,...,Newsletter_11_Cupon_2022,Newsletter_12_Cupon_2022,Newsletter_1_Cupon_2023,Newsletter_2_Cupon_2023,Newsletter_3_Cupon_2023,Newsletter_4_Cupon_2023,Newsletter_5_Cupon_2023,Newsletter_6_Cupon_2023,Newsletter_7_Cupon_2023,Newsletter_8_Cupon_2023,Newsletter_9_Cupon_2023,Newsletter_10_Cupon_2023,Newsletter_11_Cupon_2023,Newsletter_12_Cupon_2023,JAHR
0,Rum,Asien,0.0,RE_2020_0,27.0,86.23,0.0,86.23,0.00,64.67,92.75,nein,nein,ja,ja,...,nein,ja,nein,nein,nein,ja,nein,ja,ja,nein,ja,nein,nein,ja,2020
1,Wein,EU,1.0,RE_2020_1,87.0,182.93,0.0,182.93,0.00,137.20,196.76,NaN,NaN,NaN,NaN,...,ja,ja,nein,nein,nein,nein,ja,nein,nein,ja,nein,nein,nein,nein,2020
2,Wein,Asien,2.0,RE_2020_2,76.0,103.97,0.0,103.97,0.00,77.98,111.83,NaN,NaN,NaN,NaN,...,nein,ja,nein,nein,nein,nein,nein,nein,ja,ja,ja,nein,nein,ja,2020
3,Whisky,USA,3.0,RE_2020_3,44.0,119.95,0.0,119.95,0.00,89.96,129.02,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
4,Whisky,EU,4.0,RE_2020_4,25.0,217.43,5.0,206.56,-10.87,163.07,222.18,nein,nein,nein,nein,...,nein,nein,nein,ja,nein,ja,ja,ja,ja,nein,nein,nein,nein,ja,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25074,Whisky,EU,9995.0,RE_2023_9995,228.0,206.73,0.0,206.73,0.00,155.05,222.36,NaN,NaN,NaN,NaN,...,nein,nein,nein,nein,nein,nein,nein,nein,nein,ja,nein,nein,nein,nein,2023
25075,Whisky,EU,9996.0,RE_2023_9996,126.0,117.78,0.0,117.78,0.00,88.34,126.68,NaN,NaN,NaN,NaN,...,nein,ja,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023
25076,Wein,EU,9997.0,RE_2023_9997,253.0,105.83,0.0,105.83,0.00,79.37,113.83,NaN,NaN,NaN,NaN,...,nein,nein,ja,nein,nein,nein,ja,nein,nein,nein,ja,nein,nein,ja,2023
25077,Whisky,EU,9998.0,RE_2023_9998,215.0,175.00,0.0,175.00,0.00,131.25,188.23,NaN,NaN,NaN,NaN,...,nein,ja,nein,nein,ja,nein,nein,nein,nein,nein,nein,nein,nein,ja,2023
25078,Whisky,EU,9999.0,RE_2023_9999,141.0,113.73,10.0,113.73,-11.37,85.30,110.10,NaN,NaN,NaN,NaN,...,nein,ja,ja,nein,ja,nein,ja,ja,nein,nein,nein,nein,nein,nein,2023

## Aufgabe 3: erstelle eine Funktion column_auswahl, welche einen Dataframe mit allen bestimmten Columnnamen erstellt
- Was sind die einzelnen Schritte welche ich hierfür brauche?
### a) Der neue Dataframe soll nur mit den Columns Newsletter enthalten sein
- in der Parameterliste soll zum einen der Dataframe und der Variablenname enthalten sein nach welchen Column gefiltert werden soll
- die KUNDENNUMMER ist der INDEX für den neuen Dataframes
- es soll keine Doubletten im neuen Dataframes enthalten sein
<br>
*299 rows × 48 columns*

,Newsletter_1_Cupon_2020,Newsletter_2_Cupon_2020,Newsletter_3_Cupon_2020,Newsletter_4_Cupon_2020,Newsletter_5_Cupon_2020,Newsletter_6_Cupon_2020,Newsletter_7_Cupon_2020,Newsletter_8_Cupon_2020,Newsletter_9_Cupon_2020,Newsletter_10_Cupon_2020,Newsletter_11_Cupon_2020,Newsletter_12_Cupon_2020,Newsletter_1_Cupon_2021,Newsletter_2_Cupon_2021,Newsletter_3_Cupon_2021,...,Newsletter_10_Cupon_2022,Newsletter_11_Cupon_2022,Newsletter_12_Cupon_2022,Newsletter_1_Cupon_2023,Newsletter_2_Cupon_2023,Newsletter_3_Cupon_2023,Newsletter_4_Cupon_2023,Newsletter_5_Cupon_2023,Newsletter_6_Cupon_2023,Newsletter_7_Cupon_2023,Newsletter_8_Cupon_2023,Newsletter_9_Cupon_2023,Newsletter_10_Cupon_2023,Newsletter_11_Cupon_2023,Newsletter_12_Cupon_2023
KUNDENNUMMER,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
27.0,nein,nein,ja,ja,ja,nein,ja,nein,ja,nein,ja,ja,nein,nein,nein,...,nein,nein,ja,nein,nein,nein,ja,nein,ja,ja,nein,ja,nein,nein,ja
87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,nein,ja,ja,nein,nein,nein,nein,ja,nein,nein,ja,nein,nein,nein,nein
76.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,nein,nein,ja,nein,nein,nein,nein,nein,nein,ja,ja,ja,nein,nein,ja
44.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25.0,nein,nein,nein,nein,nein,ja,nein,nein,nein,nein,ja,ja,NaN,NaN,NaN,...,nein,nein,nein,nein,ja,nein,ja,ja,ja,ja,nein,nein,nein,nein,ja
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### b) erweitere bzw passe die Funktion column_auswahl
- um den Parameter in_out --> dieser gibt an ob ein Dataframes erstellt wir nur mit Newslettern oder alle anderen 
<br>
out = 25079 rows × 11 columns
<br>
in = 299 rows × 48 columns

- schreibe in einen neuen Dataframes data_news_out. indem Dataframes sollen die Daten ohne Newslettercolumns

,BESTELLNUMMER,EINKAUFPREIS,GETRAENK,JAHR,LISTENPREIS,RABATT_IN_PROZENT,RABATT_PREIS,RECHNUNGSNUMMER,REGION,VERKAUFSPREIS,VK_PERIS_IN_USD
KUNDENNUMMER,,,,,,,,,,,
27.0,0.0,64.67,Rum,2020,86.23,0.0,0.00,RE_2020_0,Asien,86.23,92.75
87.0,1.0,137.20,Wein,2020,182.93,0.0,0.00,RE_2020_1,EU,182.93,196.76
76.0,2.0,77.98,Wein,2020,103.97,0.0,0.00,RE_2020_2,Asien,103.97,111.83
44.0,3.0,89.96,Whisky,2020,119.95,0.0,0.00,RE_2020_3,USA,119.95,129.02
25.0,4.0,163.07,Whisky,2020,217.43,5.0,-10.87,RE_2020_4,EU,206.56,222.18
...,...,...,...,...,...,...,...,...,...,...,...
228.0,9995.0,155.05,Whisky,2023,206.73,0.0,0.00,RE_2023_9995,EU,206.73,222.36
126.0,9996.0,88.34,Whisky,2023,117.78,0.0,0.00,RE_2023_9996,EU,117.78,126.68
253.0,9997.0,79.37,Wein,2023,105.83,0.0,0.00,RE_2023_9997,EU,105.83,113.83
215.0,9998.0,131.25,Whisky,2023,175.00,0.0,0.00,RE_2023_9998,EU,175.00,188.23
141.0,9999.0,85.30,Whisky,2023,113.73,10.0,-11.37,RE_2023_9999,EU,113.73,110.10

## Aufgabe 4: insert column by condition

- erstelle die Funktion insert_columns_after_condition
- nach Newsletter_12_Cupon_20 soll eine Column mit dem dem gleichen Columnnamen wie davor mit dem Zusatz _count hinzugefügt werden
- ändere die Variablen in dem Dataframes von ja zu 1.0 und von nein zu 0.

,Newsletter_1_Cupon_2020,Newsletter_2_Cupon_2020,Newsletter_3_Cupon_2020,Newsletter_4_Cupon_2020,Newsletter_5_Cupon_2020,Newsletter_6_Cupon_2020,Newsletter_7_Cupon_2020,Newsletter_8_Cupon_2020,Newsletter_9_Cupon_2020,Newsletter_10_Cupon_2020,Newsletter_11_Cupon_2020,Newsletter_12_Cupon_2020,Newsletter_12_Cupon_2020_count,Newsletter_1_Cupon_2021,Newsletter_2_Cupon_2021,...,Newsletter_12_Cupon_2022,Newsletter_12_Cupon_2022_count,Newsletter_1_Cupon_2023,Newsletter_2_Cupon_2023,Newsletter_3_Cupon_2023,Newsletter_4_Cupon_2023,Newsletter_5_Cupon_2023,Newsletter_6_Cupon_2023,Newsletter_7_Cupon_2023,Newsletter_8_Cupon_2023,Newsletter_9_Cupon_2023,Newsletter_10_Cupon_2023,Newsletter_11_Cupon_2023,Newsletter_12_Cupon_2023,Newsletter_12_Cupon_2023_count
KUNDENNUMMER,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,...,0.0,NaN,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN
5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- schriebe eine Funktion fill_sum, welche die Summen der Werte in de Count Spalte berechnet pro Jahr

,Newsletter_1_Cupon_2020,Newsletter_2_Cupon_2020,Newsletter_3_Cupon_2020,Newsletter_4_Cupon_2020,Newsletter_5_Cupon_2020,Newsletter_6_Cupon_2020,Newsletter_7_Cupon_2020,Newsletter_8_Cupon_2020,Newsletter_9_Cupon_2020,Newsletter_10_Cupon_2020,Newsletter_11_Cupon_2020,Newsletter_12_Cupon_2020,Newsletter_12_Cupon_2020_count,Newsletter_1_Cupon_2021,Newsletter_2_Cupon_2021,...,Newsletter_12_Cupon_2022,Newsletter_12_Cupon_2022_count,Newsletter_1_Cupon_2023,Newsletter_2_Cupon_2023,Newsletter_3_Cupon_2023,Newsletter_4_Cupon_2023,Newsletter_5_Cupon_2023,Newsletter_6_Cupon_2023,Newsletter_7_Cupon_2023,Newsletter_8_Cupon_2023,Newsletter_9_Cupon_2023,Newsletter_10_Cupon_2023,Newsletter_11_Cupon_2023,Newsletter_12_Cupon_2023,Newsletter_12_Cupon_2023_count
KUNDENNUMMER,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,...,0.0,NaN,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN
5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
296.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
298.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Newsletter_1_Cupon_2020,Newsletter_2_Cupon_2020,Newsletter_3_Cupon_2020,Newsletter_4_Cupon_2020,Newsletter_5_Cupon_2020,Newsletter_6_Cupon_2020,Newsletter_7_Cupon_2020,Newsletter_8_Cupon_2020,Newsletter_9_Cupon_2020,Newsletter_10_Cupon_2020,Newsletter_11_Cupon_2020,Newsletter_12_Cupon_2020,Newsletter_12_Cupon_2020_count,Newsletter_1_Cupon_2021,Newsletter_2_Cupon_2021,...,Newsletter_12_Cupon_2022,Newsletter_12_Cupon_2022_count,Newsletter_1_Cupon_2023,Newsletter_2_Cupon_2023,Newsletter_3_Cupon_2023,Newsletter_4_Cupon_2023,Newsletter_5_Cupon_2023,Newsletter_6_Cupon_2023,Newsletter_7_Cupon_2023,Newsletter_8_Cupon_2023,Newsletter_9_Cupon_2023,Newsletter_10_Cupon_2023,Newsletter_11_Cupon_2023,Newsletter_12_Cupon_2023,Newsletter_12_Cupon_2023_count
KUNDENNUMMER,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,5.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,...,0.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0
5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,3.0
250.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,4.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0
252.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,5.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0
253.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,4.0
257.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Aufgabe 5: Anpassungen des Dataframes
### a) delete_col_string
- Schreibe eine Funktion, welche aus allen Columns die Bezeichnung Newsletter_ entfernt und speichere diese in einem neuen Dataframes new_cols_data

,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD,1_Cupon_2020,2_Cupon_2020,3_Cupon_2020,4_Cupon_2020,...,11_Cupon_2022,12_Cupon_2022,1_Cupon_2023,2_Cupon_2023,3_Cupon_2023,4_Cupon_2023,5_Cupon_2023,6_Cupon_2023,7_Cupon_2023,8_Cupon_2023,9_Cupon_2023,10_Cupon_2023,11_Cupon_2023,12_Cupon_2023,JAHR
0,Rum,Asien,0.0,RE_2020_0,27.0,86.23,0.0,86.23,0.00,64.67,92.75,nein,nein,ja,ja,...,nein,ja,nein,nein,nein,ja,nein,ja,ja,nein,ja,nein,nein,ja,2020
1,Wein,EU,1.0,RE_2020_1,87.0,182.93,0.0,182.93,0.00,137.20,196.76,NaN,NaN,NaN,NaN,...,ja,ja,nein,nein,nein,nein,ja,nein,nein,ja,nein,nein,nein,nein,2020
2,Wein,Asien,2.0,RE_2020_2,76.0,103.97,0.0,103.97,0.00,77.98,111.83,NaN,NaN,NaN,NaN,...,nein,ja,nein,nein,nein,nein,nein,nein,ja,ja,ja,nein,nein,ja,2020
3,Whisky,USA,3.0,RE_2020_3,44.0,119.95,0.0,119.95,0.00,89.96,129.02,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
4,Whisky,EU,4.0,RE_2020_4,25.0,217.43,5.0,206.56,-10.87,163.07,222.18,nein,nein,nein,nein,...,nein,nein,nein,ja,nein,ja,ja,ja,ja,nein,nein,nein,nein,ja,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25074,Whisky,EU,9995.0,RE_2023_9995,228.0,206.73,0.0,206.73,0.00,155.05,222.36,NaN,NaN,NaN,NaN,...,nein,nein,nein,nein,nein,nein,nein,nein,nein,ja,nein,nein,nein,nein,2023
25075,Whisky,EU,9996.0,RE_2023_9996,126.0,117.78,0.0,117.78,0.00,88.34,126.68,NaN,NaN,NaN,NaN,...,nein,ja,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023
25076,Wein,EU,9997.0,RE_2023_9997,253.0,105.83,0.0,105.83,0.00,79.37,113.83,NaN,NaN,NaN,NaN,...,nein,nein,ja,nein,nein,nein,ja,nein,nein,nein,ja,nein,nein,ja,2023
25077,Whisky,EU,9998.0,RE_2023_9998,215.0,175.00,0.0,175.00,0.00,131.25,188.23,NaN,NaN,NaN,NaN,...,nein,ja,nein,nein,ja,nein,nein,nein,nein,nein,nein,nein,nein,ja,2023
25078,Whisky,EU,9999.0,RE_2023_9999,141.0,113.73,10.0,113.73,-11.37,85.30,110.10,NaN,NaN,NaN,NaN,...,nein,ja,ja,nein,ja,nein,ja,ja,nein,nein,nein,nein,nein,nein,2023

### b) add Columnbezeichnung
- füge an alle Columns am Ende _end und zu Beginn start_ an

,start_GETRAENK_end,start_REGION_end,start_BESTELLNUMMER_end,start_RECHNUNGSNUMMER_end,start_KUNDENNUMMER_end,start_LISTENPREIS_end,start_RABATT_IN_PROZENT_end,start_VERKAUFSPREIS_end,start_RABATT_PREIS_end,start_EINKAUFPREIS_end,start_VK_PERIS_IN_USD_end,start_1_Cupon_2020_end,start_2_Cupon_2020_end,start_3_Cupon_2020_end,start_4_Cupon_2020_end,...,start_11_Cupon_2022_end,start_12_Cupon_2022_end,start_1_Cupon_2023_end,start_2_Cupon_2023_end,start_3_Cupon_2023_end,start_4_Cupon_2023_end,start_5_Cupon_2023_end,start_6_Cupon_2023_end,start_7_Cupon_2023_end,start_8_Cupon_2023_end,start_9_Cupon_2023_end,start_10_Cupon_2023_end,start_11_Cupon_2023_end,start_12_Cupon_2023_end,start_JAHR_end
0,Rum,Asien,0.0,RE_2020_0,27.0,86.23,0.0,86.23,0.00,64.67,92.75,nein,nein,ja,ja,...,nein,ja,nein,nein,nein,ja,nein,ja,ja,nein,ja,nein,nein,ja,2020
1,Wein,EU,1.0,RE_2020_1,87.0,182.93,0.0,182.93,0.00,137.20,196.76,NaN,NaN,NaN,NaN,...,ja,ja,nein,nein,nein,nein,ja,nein,nein,ja,nein,nein,nein,nein,2020
2,Wein,Asien,2.0,RE_2020_2,76.0,103.97,0.0,103.97,0.00,77.98,111.83,NaN,NaN,NaN,NaN,...,nein,ja,nein,nein,nein,nein,nein,nein,ja,ja,ja,nein,nein,ja,2020
3,Whisky,USA,3.0,RE_2020_3,44.0,119.95,0.0,119.95,0.00,89.96,129.02,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
4,Whisky,EU,4.0,RE_2020_4,25.0,217.43,5.0,206.56,-10.87,163.07,222.18,nein,nein,nein,nein,...,nein,nein,nein,ja,nein,ja,ja,ja,ja,nein,nein,nein,nein,ja,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25074,Whisky,EU,9995.0,RE_2023_9995,228.0,206.73,0.0,206.73,0.00,155.05,222.36,NaN,NaN,NaN,NaN,...,nein,nein,nein,nein,nein,nein,nein,nein,nein,ja,nein,nein,nein,nein,2023
25075,Whisky,EU,9996.0,RE_2023_9996,126.0,117.78,0.0,117.78,0.00,88.34,126.68,NaN,NaN,NaN,NaN,...,nein,ja,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023
25076,Wein,EU,9997.0,RE_2023_9997,253.0,105.83,0.0,105.83,0.00,79.37,113.83,NaN,NaN,NaN,NaN,...,nein,nein,ja,nein,nein,nein,ja,nein,nein,nein,ja,nein,nein,ja,2023
25077,Whisky,EU,9998.0,RE_2023_9998,215.0,175.00,0.0,175.00,0.00,131.25,188.23,NaN,NaN,NaN,NaN,...,nein,ja,nein,nein,ja,nein,nein,nein,nein,nein,nein,nein,nein,ja,2023
25078,Whisky,EU,9999.0,RE_2023_9999,141.0,113.73,10.0,113.73,-11.37,85.30,110.10,NaN,NaN,NaN,NaN,...,nein,ja,ja,nein,ja,nein,ja,ja,nein,nein,nein,nein,nein,nein,2023

### c) prepare_every_second_column
schriebe eine Funktion prepare_every_second_column
- welche am Ende _ungerade anfügt, wenn zu Beginn des Columnnamens eine ungerade Zahl steht

,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD,1_Cupon_2020_ungerade,2_Cupon_2020,3_Cupon_2020_ungerade,4_Cupon_2020,...,11_Cupon_2022_ungerade,12_Cupon_2022,1_Cupon_2023_ungerade,2_Cupon_2023,3_Cupon_2023_ungerade,4_Cupon_2023,5_Cupon_2023_ungerade,6_Cupon_2023,7_Cupon_2023_ungerade,8_Cupon_2023,9_Cupon_2023_ungerade,10_Cupon_2023,11_Cupon_2023_ungerade,12_Cupon_2023,JAHR
0,Rum,Asien,0.0,RE_2020_0,27.0,86.23,0.0,86.23,0.00,64.67,92.75,nein,nein,ja,ja,...,nein,ja,nein,nein,nein,ja,nein,ja,ja,nein,ja,nein,nein,ja,2020
1,Wein,EU,1.0,RE_2020_1,87.0,182.93,0.0,182.93,0.00,137.20,196.76,NaN,NaN,NaN,NaN,...,ja,ja,nein,nein,nein,nein,ja,nein,nein,ja,nein,nein,nein,nein,2020
2,Wein,Asien,2.0,RE_2020_2,76.0,103.97,0.0,103.97,0.00,77.98,111.83,NaN,NaN,NaN,NaN,...,nein,ja,nein,nein,nein,nein,nein,nein,ja,ja,ja,nein,nein,ja,2020
3,Whisky,USA,3.0,RE_2020_3,44.0,119.95,0.0,119.95,0.00,89.96,129.02,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
4,Whisky,EU,4.0,RE_2020_4,25.0,217.43,5.0,206.56,-10.87,163.07,222.18,nein,nein,nein,nein,...,nein,nein,nein,ja,nein,ja,ja,ja,ja,nein,nein,nein,nein,ja,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25074,Whisky,EU,9995.0,RE_2023_9995,228.0,206.73,0.0,206.73,0.00,155.05,222.36,NaN,NaN,NaN,NaN,...,nein,nein,nein,nein,nein,nein,nein,nein,nein,ja,nein,nein,nein,nein,2023
25075,Whisky,EU,9996.0,RE_2023_9996,126.0,117.78,0.0,117.78,0.00,88.34,126.68,NaN,NaN,NaN,NaN,...,nein,ja,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023
25076,Wein,EU,9997.0,RE_2023_9997,253.0,105.83,0.0,105.83,0.00,79.37,113.83,NaN,NaN,NaN,NaN,...,nein,nein,ja,nein,nein,nein,ja,nein,nein,nein,ja,nein,nein,ja,2023
25077,Whisky,EU,9998.0,RE_2023_9998,215.0,175.00,0.0,175.00,0.00,131.25,188.23,NaN,NaN,NaN,NaN,...,nein,ja,nein,nein,ja,nein,nein,nein,nein,nein,nein,nein,nein,ja,2023
25078,Whisky,EU,9999.0,RE_2023_9999,141.0,113.73,10.0,113.73,-11.37,85.30,110.10,NaN,NaN,NaN,NaN,...,nein,ja,ja,nein,ja,nein,ja,ja,nein,nein,nein,nein,nein,nein,2023

### d) Datenobjekte in dem Dataframe ändern
- ändere die float Werte aus data_news_out in int Werte
- verwende hierfür einen for loop und select_dtypes

<class 'pandas.core.frame.DataFrame'>
Index: 25079 entries, 27.0 to 141.0
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   BESTELLNUMMER      25079 non-null  int64
 1   EINKAUFPREIS       25079 non-null  int64
 2   GETRAENK           25066 non-null  object
 3   JAHR               25072 non-null  object
 4   LISTENPREIS        25079 non-null  int64
 5   RABATT_IN_PROZENT  25079 non-null  int64
 6   RABATT_PREIS       25079 non-null  int64
 7   RECHNUNGSNUMMER    25079 non-null  object
 8   REGION             25077 non-null  object
 9   VERKAUFSPREIS      25079 non-null  int64
 10  VK_PERIS_IN_USD    25079 non-null  int64
dtypes: int64(7), object(4)
memory usage: 2.3+ MB

- ändere nun alle int Columns to float Columns

<class 'pandas.core.frame.DataFrame'>
Index: 25079 entries, 27.0 to 141.0
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   BESTELLNUMMER      25079 non-null  float64
 1   EINKAUFPREIS       25079 non-null  float64
 2   GETRAENK           25066 non-null  object
 3   JAHR               25072 non-null  object
 4   LISTENPREIS        25079 non-null  float64
 5   RABATT_IN_PROZENT  25079 non-null  float64
 6   RABATT_PREIS       25079 non-null  float64
 7   RECHNUNGSNUMMER    25079 non-null  object
 8   REGION             25077 non-null  object
 9   VERKAUFSPREIS      25079 non-null  float64
 10  VK_PERIS_IN_USD    25079 non-null  float64
dtypes: float64(7), object(4)
memory usage: 2.3+ MB

### e) Verteilung der verschiedenen Ausprägungen der Columns
- Zähle die verschiedenen Ausprägungen der Column GETRAENK

GETRAENK
Whisky        13747
Wein           6287
Champagner     2554
Rum            2478
Name: count, dtype: int64

- die prozentuale Verteilung der Ausprägungen der Column REGION

REGION
EU       0.501376
USA      0.299159
Asien    0.199466
Name: proportion, dtype: float64

### f) Wertevergleich von zwei Columns
- führe den unteren Code aus, um eine neue Column mit zufälligen Werten zuerhalten

- erstele eine neue Column mit dem Namen Difference 
- überprufe in jedem Record, ob in der Column GETRAENK und GETRAENK_2 die gleichen Werte bestehen
- wenn identisch soll GETRAENK in die Column Difference ansonsten JA
**Tipp** apply und lambda

- erstelle einen Sub-Dataframes, welcher nur die beiden Columns GETRAENK und GETRAENK_2 identisch haben

,BESTELLNUMMER,EINKAUFPREIS,GETRAENK,JAHR,LISTENPREIS,RABATT_IN_PROZENT,RABATT_PREIS,RECHNUNGSNUMMER,REGION,VERKAUFSPREIS,VK_PERIS_IN_USD,GETRAENK_2,Difference
KUNDENNUMMER,,,,,,,,,,,,,
44.0,3.0,89.96,Whisky,2020,119.95,0.0,0.00,RE_2020_3,USA,119.95,129.02,Whisky,Whisky
20.0,6.0,115.33,Whisky,2020,153.77,0.0,0.00,RE_2020_6,USA,153.77,165.40,Whisky,Whisky
97.0,7.0,151.73,Champagner,2020,202.31,0.0,0.00,RE_2020_7,Asien,202.31,217.60,Champagner,Champagner
43.0,8.0,137.60,Champagner,2020,183.47,0.0,0.00,RE_2020_8,EU,183.47,197.34,Champagner,Champagner
85.0,9.0,172.12,Whisky,2020,229.50,0.0,0.00,RE_2020_9,Asien,229.50,246.85,Whisky,Whisky
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21.0,9988.0,100.64,Whisky,2023,134.18,0.0,0.00,RE_2023_9988,USA,134.18,144.32,Whisky,Whisky
131.0,9992.0,71.87,Whisky,2023,95.83,5.0,-4.79,RE_2023_9992,EU,95.83,97.92,Whisky,Whisky
228.0,9995.0,155.05,Whisky,2023,206.73,0.0,0.00,RE_2023_9995,EU,206.73,222.36,Whisky,Whisky
126.0,9996.0,88.34,Whisky,2023,117.78,0.0,0.00,RE_2023_9996,EU,117.78,126.68,Whisky,Whisky
215.0,9998.0,131.25,Whisky,2023,175.00,0.0,0.00,RE_2023_9998,EU,175.00,188.23,Whisky,Whisky

- Bestimme in einer neuen Column ob der LISTENPREIS über 130 ist

,BESTELLNUMMER,EINKAUFPREIS,GETRAENK,JAHR,LISTENPREIS,RABATT_IN_PROZENT,RABATT_PREIS,RECHNUNGSNUMMER,REGION,VERKAUFSPREIS,VK_PERIS_IN_USD,GETRAENK_2,Difference,Listenpreis_über_130
KUNDENNUMMER,,,,,,,,,,,,,,
27.0,0.0,64.67,Rum,2020,86.23,0.0,0.00,RE_2020_0,Asien,86.23,92.75,Whisky,JA,0
87.0,1.0,137.20,Wein,2020,182.93,0.0,0.00,RE_2020_1,EU,182.93,196.76,Rum,JA,1
76.0,2.0,77.98,Wein,2020,103.97,0.0,0.00,RE_2020_2,Asien,103.97,111.83,Whisky,JA,0
44.0,3.0,89.96,Whisky,2020,119.95,0.0,0.00,RE_2020_3,USA,119.95,129.02,Whisky,Whisky,0
25.0,4.0,163.07,Whisky,2020,217.43,5.0,-10.87,RE_2020_4,EU,206.56,222.18,Champagner,JA,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228.0,9995.0,155.05,Whisky,2023,206.73,0.0,0.00,RE_2023_9995,EU,206.73,222.36,Whisky,Whisky,1
126.0,9996.0,88.34,Whisky,2023,117.78,0.0,0.00,RE_2023_9996,EU,117.78,126.68,Whisky,Whisky,0
253.0,9997.0,79.37,Wein,2023,105.83,0.0,0.00,RE_2023_9997,EU,105.83,113.83,Whisky,JA,0
215.0,9998.0,131.25,Whisky,2023,175.00,0.0,0.00,RE_2023_9998,EU,175.00,188.23,Whisky,Whisky,1
141.0,9999.0,85.30,Whisky,2023,113.73,10.0,-11.37,RE_2023_9999,EU,113.73,110.10,Wein,JA,0

### g) isin
- verändere den Datentyp der Column JAHR in int
- bilde jeweils einen Sub-Dataframes für die Jahre 2021 und 2020 und den Rechnungen aus diesen Jahren

,KUNDENNUMMER,BESTELLNUMMER,EINKAUFPREIS,GETRAENK,JAHR,LISTENPREIS,RABATT_IN_PROZENT,RABATT_PREIS,RECHNUNGSNUMMER,REGION,VERKAUFSPREIS,VK_PERIS_IN_USD
0,1.0,244.0,149.05,Whisky,2021,198.73,0.0,0.00,RE_2021_244,EU,198.73,213.75
1,1.0,1735.0,92.75,Rum,2021,123.67,0.0,0.00,RE_2021_1735,EU,123.67,133.02
2,1.0,1253.0,120.80,Wein,2021,161.06,0.0,0.00,RE_2021_1253,Asien,161.06,173.24
3,1.0,4689.0,62.16,Whisky,2021,82.88,0.0,0.00,RE_2021_4689,Asien,82.88,89.15
4,1.0,3943.0,141.70,Whisky,2021,188.94,0.0,0.00,RE_2021_3943,Asien,188.94,203.22
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,159.0,1429.0,107.22,Whisky,2021,142.96,0.0,0.00,RE_2021_1429,EU,142.96,153.77
4996,159.0,3586.0,95.33,Whisky,2021,127.11,0.0,0.00,RE_2021_3586,EU,127.11,136.72
4997,159.0,2456.0,110.87,Whisky,2021,147.83,5.0,-7.39,RE_2021_2456,EU,140.44,151.06
4998,159.0,969.0,112.28,Whisky,2021,149.71,0.0,0.00,RE_2021_969,USA,149.71,161.03
4999,159.0,1725.0,159.26,Whisky,2021,212.35,5.0,-10.62,RE_2021_1725,USA,201.73,216.98

- finde alle Records in 2021, welche auch in 2020 enthalten sind

,KUNDENNUMMER,BESTELLNUMMER,EINKAUFPREIS,GETRAENK,JAHR,LISTENPREIS,RABATT_IN_PROZENT,RABATT_PREIS,RECHNUNGSNUMMER,REGION,VERKAUFSPREIS,VK_PERIS_IN_USD
0,1.0,244.0,149.05,Whisky,2021,198.73,0.0,0.0,RE_2021_244,EU,198.73,213.75
1,1.0,1735.0,92.75,Rum,2021,123.67,0.0,0.0,RE_2021_1735,EU,123.67,133.02
2,1.0,1253.0,120.80,Wein,2021,161.06,0.0,0.0,RE_2021_1253,Asien,161.06,173.24
3,1.0,4689.0,62.16,Whisky,2021,82.88,0.0,0.0,RE_2021_4689,Asien,82.88,89.15
4,1.0,3943.0,141.70,Whisky,2021,188.94,0.0,0.0,RE_2021_3943,Asien,188.94,203.22
...,...,...,...,...,...,...,...,...,...,...,...,...
3108,99.0,2130.0,112.47,Whisky,2021,149.96,0.0,0.0,RE_2021_2130,Asien,149.96,161.30
3109,99.0,2379.0,136.64,Whisky,2021,182.18,0.0,0.0,RE_2021_2379,USA,182.18,195.95
3110,99.0,630.0,122.24,Wein,2021,162.99,0.0,0.0,RE_2021_630,EU,162.99,175.31
3111,99.0,2080.0,120.27,Whisky,2021,160.36,0.0,0.0,RE_2021_2080,EU,160.36,172.48
3112,99.0,54.0,66.47,Whisky,2021,88.63,0.0,0.0,RE_2021_54,EU,88.63,95.33

- finde alle Records im Dataframes 2021, welche nicht im Dataframes 2020 enthalten sind

,KUNDENNUMMER,BESTELLNUMMER,EINKAUFPREIS,GETRAENK,JAHR,LISTENPREIS,RABATT_IN_PROZENT,RABATT_PREIS,RECHNUNGSNUMMER,REGION,VERKAUFSPREIS,VK_PERIS_IN_USD
3113,100.0,3383.0,101.26,Wein,2021,135.01,0.0,0.00,RE_2021_3383,EU,135.01,145.22
3114,100.0,443.0,154.53,Whisky,2021,206.04,0.0,0.00,RE_2021_443,EU,206.04,221.62
3115,100.0,819.0,97.72,Whisky,2021,130.29,0.0,0.00,RE_2021_819,USA,130.29,140.14
3116,100.0,175.0,110.44,Rum,2021,147.26,0.0,0.00,RE_2021_175,EU,147.26,158.39
3117,100.0,4881.0,140.18,Whisky,2021,186.90,0.0,0.00,RE_2021_4881,Asien,186.90,201.03
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,159.0,1429.0,107.22,Whisky,2021,142.96,0.0,0.00,RE_2021_1429,EU,142.96,153.77
4996,159.0,3586.0,95.33,Whisky,2021,127.11,0.0,0.00,RE_2021_3586,EU,127.11,136.72
4997,159.0,2456.0,110.87,Whisky,2021,147.83,5.0,-7.39,RE_2021_2456,EU,140.44,151.06
4998,159.0,969.0,112.28,Whisky,2021,149.71,0.0,0.00,RE_2021_969,USA,149.71,161.03
4999,159.0,1725.0,159.26,Whisky,2021,212.35,5.0,-10.62,RE_2021_1725,USA,201.73,216.98

- erstelle zwei Dataframes in dem ersten Dataframe sollen die ersten 6 Columns enthalten sein und dem anderen Dataframes die anderen Columns
- probiere dies in einer Reihe zu schrieben

      KUNDENNUMMER  BESTELLNUMMER  EINKAUFPREIS GETRAENK  JAHR  LISTENPREIS
3113         100.0         3383.0        101.26     Wein  2021       135.01
3114         100.0          443.0        154.53   Whisky  2021       206.04
3115         100.0          819.0         97.72   Whisky  2021       130.29
3116         100.0          175.0        110.44      Rum  2021       147.26
3117         100.0         4881.0        140.18   Whisky  2021       186.90
...            ...            ...           ...      ...   ...          ...
4995         159.0         1429.0        107.22   Whisky  2021       142.96
4996         159.0         3586.0         95.33   Whisky  2021       127.11
4997         159.0         2456.0        110.87   Whisky  2021       147.83
4998         159.0          969.0        112.28   Whisky  2021       149.71
4999         159.0         1725.0        159.26   Whisky  2021       212.35

[1887 rows x 6 columns]

,RABATT_IN_PROZENT,RABATT_PREIS,RECHNUNGSNUMMER,REGION,VERKAUFSPREIS,VK_PERIS_IN_USD
3113,0.0,0.00,RE_2021_3383,EU,135.01,145.22
3114,0.0,0.00,RE_2021_443,EU,206.04,221.62
3115,0.0,0.00,RE_2021_819,USA,130.29,140.14
3116,0.0,0.00,RE_2021_175,EU,147.26,158.39
3117,0.0,0.00,RE_2021_4881,Asien,186.90,201.03
...,...,...,...,...,...,...
4995,0.0,0.00,RE_2021_1429,EU,142.96,153.77
4996,0.0,0.00,RE_2021_3586,EU,127.11,136.72
4997,5.0,-7.39,RE_2021_2456,EU,140.44,151.06
4998,0.0,0.00,RE_2021_969,USA,149.71,161.03
4999,5.0,-10.62,RE_2021_1725,USA,201.73,216.98