# Arbeitsaufgaben 10:

## Aufgabe 1:

- importiere die Bibliothek `pandas`
- lade die Datei `data_merged_save.csv` als Variable `data_basis` ein

In [146]:
import random

import pandas as pd
from parso.python.tree import Lambda

In [115]:
data_basis = pd.read_csv("ressources/data_merged_save.csv", sep="\t", encoding="utf-8")
data_basis

,Unnamed: 0,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD,Newsletter_1_Cupon_2020,Newsletter_2_Cupon_2020,Newsletter_3_Cupon_2020,...,Newsletter_10_Cupon_2022,Newsletter_11_Cupon_2022,Newsletter_12_Cupon_2022,Newsletter_1_Cupon_2023,Newsletter_2_Cupon_2023,Newsletter_3_Cupon_2023,Newsletter_4_Cupon_2023,Newsletter_5_Cupon_2023,Newsletter_6_Cupon_2023,Newsletter_7_Cupon_2023,Newsletter_8_Cupon_2023,Newsletter_9_Cupon_2023,Newsletter_10_Cupon_2023,Newsletter_11_Cupon_2023,Newsletter_12_Cupon_2023
0,0,Rum,Asien,0.0,RE_2020_0,27.0,86.23,0.0,86.23,0.00,64.67,92.75,nein,nein,ja,...,nein,nein,ja,nein,nein,nein,ja,nein,ja,ja,nein,ja,nein,nein,ja
1,1,Wein,EU,1.0,RE_2020_1,87.0,182.93,0.0,182.93,0.00,137.20,196.76,NaN,NaN,NaN,...,nein,ja,ja,nein,nein,nein,nein,ja,nein,nein,ja,nein,nein,nein,nein
2,2,Wein,Asien,2.0,RE_2020_2,76.0,103.97,0.0,103.97,0.00,77.98,111.83,NaN,NaN,NaN,...,nein,nein,ja,nein,nein,nein,nein,nein,nein,ja,ja,ja,nein,nein,ja
3,3,Whisky,USA,3.0,RE_2020_3,44.0,119.95,0.0,119.95,0.00,89.96,129.02,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Whisky,EU,4.0,RE_2020_4,25.0,217.43,5.0,206.56,-10.87,163.07,222.18,nein,nein,nein,...,nein,nein,nein,nein,ja,nein,ja,ja,ja,ja,nein,nein,nein,nein,ja
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25074,25074,Whisky,EU,9995.0,RE_2023_9995,228.0,206.73,0.0,206.73,0.00,155.05,222.36,NaN,NaN,NaN,...,nein,nein,nein,nein,nein,nein,nein,nein,nein,nein,ja,nein,nein,nein,nein
25075,25075,Whisky,EU,9996.0,RE_2023_9996,126.0,117.78,0.0,117.78,0.00,88.34,126.68,NaN,NaN,NaN,...,ja,nein,ja,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25076,25076,Wein,EU,9997.0,RE_2023_9997,253.0,105.83,0.0,105.83,0.00,79.37,113.83,NaN,NaN,NaN,...,nein,nein,nein,ja,nein,nein,nein,ja,nein,nein,nein,ja,nein,nein,ja
25077,25077,Whisky,EU,9998.0,RE_2023_9998,215.0,175.00,0.0,175.00,0.00,131.25,188.23,NaN,NaN,NaN,...,nein,nein,ja,nein,nein,ja,nein,nein,nein,nein,nein,nein,nein,nein,ja
25078,25078,Whisky,EU,9999.0,RE_2023_9999,141.0,113.73,10.0,113.73,-11.37,85.30,110.10,NaN,NaN,NaN,...,nein,nein,ja,ja,nein,ja,nein,ja,ja,nein,nein,nein,nein,nein,nein

Verändere die Ausgabengrösse des Dataframes (also die angezeigten Rows und Columns)auf:
- 10 rows und 30 columns
<br><br>**Tipp** benutze pandas set option

In [116]:
pd.options.display.max_rows = 10
pd.options.display.max_columns = 30

data_basis

,Unnamed: 0,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD,Newsletter_1_Cupon_2020,Newsletter_2_Cupon_2020,Newsletter_3_Cupon_2020,...,Newsletter_10_Cupon_2022,Newsletter_11_Cupon_2022,Newsletter_12_Cupon_2022,Newsletter_1_Cupon_2023,Newsletter_2_Cupon_2023,Newsletter_3_Cupon_2023,Newsletter_4_Cupon_2023,Newsletter_5_Cupon_2023,Newsletter_6_Cupon_2023,Newsletter_7_Cupon_2023,Newsletter_8_Cupon_2023,Newsletter_9_Cupon_2023,Newsletter_10_Cupon_2023,Newsletter_11_Cupon_2023,Newsletter_12_Cupon_2023
0,0,Rum,Asien,0.0,RE_2020_0,27.0,86.23,0.0,86.23,0.00,64.67,92.75,nein,nein,ja,...,nein,nein,ja,nein,nein,nein,ja,nein,ja,ja,nein,ja,nein,nein,ja
1,1,Wein,EU,1.0,RE_2020_1,87.0,182.93,0.0,182.93,0.00,137.20,196.76,NaN,NaN,NaN,...,nein,ja,ja,nein,nein,nein,nein,ja,nein,nein,ja,nein,nein,nein,nein
2,2,Wein,Asien,2.0,RE_2020_2,76.0,103.97,0.0,103.97,0.00,77.98,111.83,NaN,NaN,NaN,...,nein,nein,ja,nein,nein,nein,nein,nein,nein,ja,ja,ja,nein,nein,ja
3,3,Whisky,USA,3.0,RE_2020_3,44.0,119.95,0.0,119.95,0.00,89.96,129.02,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Whisky,EU,4.0,RE_2020_4,25.0,217.43,5.0,206.56,-10.87,163.07,222.18,nein,nein,nein,...,nein,nein,nein,nein,ja,nein,ja,ja,ja,ja,nein,nein,nein,nein,ja
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25074,25074,Whisky,EU,9995.0,RE_2023_9995,228.0,206.73,0.0,206.73,0.00,155.05,222.36,NaN,NaN,NaN,...,nein,nein,nein,nein,nein,nein,nein,nein,nein,nein,ja,nein,nein,nein,nein
25075,25075,Whisky,EU,9996.0,RE_2023_9996,126.0,117.78,0.0,117.78,0.00,88.34,126.68,NaN,NaN,NaN,...,ja,nein,ja,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25076,25076,Wein,EU,9997.0,RE_2023_9997,253.0,105.83,0.0,105.83,0.00,79.37,113.83,NaN,NaN,NaN,...,nein,nein,nein,ja,nein,nein,nein,ja,nein,nein,nein,ja,nein,nein,ja
25077,25077,Whisky,EU,9998.0,RE_2023_9998,215.0,175.00,0.0,175.00,0.00,131.25,188.23,NaN,NaN,NaN,...,nein,nein,ja,nein,nein,ja,nein,nein,nein,nein,nein,nein,nein,nein,ja
25078,25078,Whisky,EU,9999.0,RE_2023_9999,141.0,113.73,10.0,113.73,-11.37,85.30,110.10,NaN,NaN,NaN,...,nein,nein,ja,ja,nein,ja,nein,ja,ja,nein,nein,nein,nein,nein,nein

### a) Basis Categorie^
- erstelle eine Series `cat_task` aus den Buchstaben `q, w, e, r` und alle Buchstaben sollen dreimal vorkommen
- wandele den Datentyp anschliessend in eine Categorie

In [117]:
cat_task = pd.Series(
    ["q", "w", "e", "r"] * 3,
    dtype="category"
)

cat_task

0     q
1     w
2     e
3     r
4     q
     ..
7     r
8     q
9     w
10    e
11    r
Length: 12, dtype: category
Categories (4, str): ['e', 'q', 'r', 'w']

- zeige die umgewandelten Werte (numerische) von `cat_task` an

In [118]:
cat_task.cat.codes

0     1
1     3
2     0
3     2
4     1
     ..
7     2
8     1
9     3
10    0
11    2
Length: 12, dtype: int8

- zeige alle Kategorien von `cat_task` an

In [119]:
cat_task.cat.categories

Index(['e', 'q', 'r', 'w'], dtype='str')

- sortiere die Kategorien aufsteigend aus `cat_task`
<br><br>
*Tipp:* nutze sort_values()

In [120]:
cat_task.sort_values(ascending=True)

2     e
6     e
10    e
0     q
4     q
     ..
7     r
11    r
1     w
5     w
9     w
Length: 12, dtype: category
Categories (4, str): ['e', 'q', 'r', 'w']

- bennen die Kategorie aus `cat_task` von `w` in `z` um 
- speichere die neuen Kategroien in der Variable `cat_task_2`

In [121]:
cat_task_2 = cat_task.cat.rename_categories({"w": "z"})
cat_task_2

0     q
1     z
2     e
3     r
4     q
     ..
7     r
8     q
9     z
10    e
11    r
Length: 12, dtype: category
Categories (4, str): ['e', 'q', 'r', 'z']

- füge eine zusätzliche Kategorie `d` zu der Variabel `cat_task_2` hinzu 
- und zähle, wie oft die verschiedenen Ausprägungen vorkommen

In [122]:
cat_task_2 = cat_task_2.cat.add_categories(["d"])
cat_task_2.value_counts()

e    3
q    3
r    3
z    3
d    0
Name: count, dtype: int64

- gebe alle Kategorien aus `cat_task_2` wieder, welche die Kategorie q, w, e haben
- speichere das neue Ergebenis in einer neuen Variable `cat_task_3`

In [123]:
cat_task_3 = cat_task_2[cat_task_2.isin(["q", "w", "e"])]
cat_task_3

0     q
2     e
4     q
6     e
8     q
10    e
dtype: category
Categories (5, str): ['e', 'q', 'r', 'z', 'd']

- entferne die nicht genutzten Kategorien aus `cat_task_3`

In [124]:
cat_task_3.cat = cat_task_3.cat.remove_unused_categories()

### b) Categorie für `data_basis`
- erstelle einen Subframe aus dem Dataframes `data_basis` und aus den Columns: `RECHNUNGSNUMMER, KUNDENNUMMER, GETRAENK, REGION`
- erstelle die Categorie CAT_GETRAENK in einer neuen Column von GETRAENK

In [125]:
sub_frame = data_basis[["RECHNUNGSNUMMER", "KUNDENNUMMER", "GETRAENK", "REGION"]]
sub_frame["CAT_GETRAENK"] = pd.Categorical(sub_frame["GETRAENK"])

#oder
#sub_frame["CAT_GETRAENK"] = sub_frame["GETRAENK"].astype("category")

sub_frame

      RECHNUNGSNUMMER  KUNDENNUMMER GETRAENK REGION CAT_GETRAENK
0           RE_2020_0          27.0      Rum  Asien          Rum
1           RE_2020_1          87.0     Wein     EU         Wein
2           RE_2020_2          76.0     Wein  Asien         Wein
3           RE_2020_3          44.0   Whisky    USA       Whisky
4           RE_2020_4          25.0   Whisky     EU       Whisky
...               ...           ...      ...    ...          ...
25074    RE_2023_9995         228.0   Whisky     EU       Whisky
25075    RE_2023_9996         126.0   Whisky     EU       Whisky
25076    RE_2023_9997         253.0     Wein     EU         Wein
25077    RE_2023_9998         215.0   Whisky     EU       Whisky
25078    RE_2023_9999         141.0   Whisky     EU       Whisky

[25079 rows x 5 columns]

- schreibe den jeweiligen Integer Wert zu den Kategorien von GETRAENKE in eine neue Column (CAT_GETRAENK_NEW)

In [126]:
sub_frame["CAT_GETRAENK_NEW"] = sub_frame["CAT_GETRAENK"].cat.codes
sub_frame

,RECHNUNGSNUMMER,KUNDENNUMMER,GETRAENK,REGION,CAT_GETRAENK,CAT_GETRAENK_NEW
0,RE_2020_0,27.0,Rum,Asien,Rum,1
1,RE_2020_1,87.0,Wein,EU,Wein,2
2,RE_2020_2,76.0,Wein,Asien,Wein,2
3,RE_2020_3,44.0,Whisky,USA,Whisky,3
4,RE_2020_4,25.0,Whisky,EU,Whisky,3
...,...,...,...,...,...,...
25074,RE_2023_9995,228.0,Whisky,EU,Whisky,3
25075,RE_2023_9996,126.0,Whisky,EU,Whisky,3
25076,RE_2023_9997,253.0,Wein,EU,Wein,2
25077,RE_2023_9998,215.0,Whisky,EU,Whisky,3
25078,RE_2023_9999,141.0,Whisky,EU,Whisky,3

- erstelle sogenannte dummie Varibalen für GETRAENK und stelle den jeweiligen Columns GETRAENK_ONE_HOT_ voran und füge diese den URsprungsdaten hinzu
<br><br> **Tipp:** verwende die Funktion get_dummies

In [127]:
# erst dummiespalten erstellen
getraenk_dummies = pd.get_dummies(
    sub_frame["GETRAENK"],
    prefix="GETRAENK_ONE_HOT"
)

# dann beide frames zusammenfügen
sub_frame = pd.concat(
    [getraenk_dummies, sub_frame],
    axis=1
)

sub_frame

,GETRAENK_ONE_HOT_Champagner,GETRAENK_ONE_HOT_Rum,GETRAENK_ONE_HOT_Wein,GETRAENK_ONE_HOT_Whisky,RECHNUNGSNUMMER,KUNDENNUMMER,GETRAENK,REGION,CAT_GETRAENK,CAT_GETRAENK_NEW
0,False,True,False,False,RE_2020_0,27.0,Rum,Asien,Rum,1
1,False,False,True,False,RE_2020_1,87.0,Wein,EU,Wein,2
2,False,False,True,False,RE_2020_2,76.0,Wein,Asien,Wein,2
3,False,False,False,True,RE_2020_3,44.0,Whisky,USA,Whisky,3
4,False,False,False,True,RE_2020_4,25.0,Whisky,EU,Whisky,3
...,...,...,...,...,...,...,...,...,...,...
25074,False,False,False,True,RE_2023_9995,228.0,Whisky,EU,Whisky,3
25075,False,False,False,True,RE_2023_9996,126.0,Whisky,EU,Whisky,3
25076,False,False,True,False,RE_2023_9997,253.0,Wein,EU,Wein,2
25077,False,False,False,True,RE_2023_9998,215.0,Whisky,EU,Whisky,3
25078,False,False,False,True,RE_2023_9999,141.0,Whisky,EU,Whisky,3

# Aufgabe 2: weitere Datenbearbeitung
- bestimme aus dem Dataframe data_basis in einer neuen Spalte das jeweilige Jahr aus der RECHNUNGSNUMMER

In [128]:
data_basis["YEAR"] = data_basis["RECHNUNGSNUMMER"].str.extract(r"(\d{4})")
data_basis

,Unnamed: 0,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD,Newsletter_1_Cupon_2020,Newsletter_2_Cupon_2020,Newsletter_3_Cupon_2020,...,Newsletter_11_Cupon_2022,Newsletter_12_Cupon_2022,Newsletter_1_Cupon_2023,Newsletter_2_Cupon_2023,Newsletter_3_Cupon_2023,Newsletter_4_Cupon_2023,Newsletter_5_Cupon_2023,Newsletter_6_Cupon_2023,Newsletter_7_Cupon_2023,Newsletter_8_Cupon_2023,Newsletter_9_Cupon_2023,Newsletter_10_Cupon_2023,Newsletter_11_Cupon_2023,Newsletter_12_Cupon_2023,YEAR
0,0,Rum,Asien,0.0,RE_2020_0,27.0,86.23,0.0,86.23,0.00,64.67,92.75,nein,nein,ja,...,nein,ja,nein,nein,nein,ja,nein,ja,ja,nein,ja,nein,nein,ja,2020
1,1,Wein,EU,1.0,RE_2020_1,87.0,182.93,0.0,182.93,0.00,137.20,196.76,NaN,NaN,NaN,...,ja,ja,nein,nein,nein,nein,ja,nein,nein,ja,nein,nein,nein,nein,2020
2,2,Wein,Asien,2.0,RE_2020_2,76.0,103.97,0.0,103.97,0.00,77.98,111.83,NaN,NaN,NaN,...,nein,ja,nein,nein,nein,nein,nein,nein,ja,ja,ja,nein,nein,ja,2020
3,3,Whisky,USA,3.0,RE_2020_3,44.0,119.95,0.0,119.95,0.00,89.96,129.02,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
4,4,Whisky,EU,4.0,RE_2020_4,25.0,217.43,5.0,206.56,-10.87,163.07,222.18,nein,nein,nein,...,nein,nein,nein,ja,nein,ja,ja,ja,ja,nein,nein,nein,nein,ja,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25074,25074,Whisky,EU,9995.0,RE_2023_9995,228.0,206.73,0.0,206.73,0.00,155.05,222.36,NaN,NaN,NaN,...,nein,nein,nein,nein,nein,nein,nein,nein,nein,ja,nein,nein,nein,nein,2023
25075,25075,Whisky,EU,9996.0,RE_2023_9996,126.0,117.78,0.0,117.78,0.00,88.34,126.68,NaN,NaN,NaN,...,nein,ja,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023
25076,25076,Wein,EU,9997.0,RE_2023_9997,253.0,105.83,0.0,105.83,0.00,79.37,113.83,NaN,NaN,NaN,...,nein,nein,ja,nein,nein,nein,ja,nein,nein,nein,ja,nein,nein,ja,2023
25077,25077,Whisky,EU,9998.0,RE_2023_9998,215.0,175.00,0.0,175.00,0.00,131.25,188.23,NaN,NaN,NaN,...,nein,ja,nein,nein,ja,nein,nein,nein,nein,nein,nein,nein,nein,ja,2023
25078,25078,Whisky,EU,9999.0,RE_2023_9999,141.0,113.73,10.0,113.73,-11.37,85.30,110.10,NaN,NaN,NaN,...,nein,ja,ja,nein,ja,nein,ja,ja,nein,nein,nein,nein,nein,nein,2023

## Aufgabe 3: erstelle eine Funktion column_auswahl, welche einen Dataframe mit allen bestimmten Columnnamen erstellt
- Was sind die einzelnen Schritte welche ich hierfür brauche?
### a) Der neue Dataframe soll nur mit den Columns Newsletter enthalten sein
- in der Parameterliste soll zum einen der Dataframe und der Variablenname enthalten sein nach welchen Column gefiltert werden soll
- die KUNDENNUMMER ist der INDEX für den neuen Dataframes
- es soll keine Doubletten im neuen Dataframes enthalten sein
<br>
*299 rows × 48 columns*

In [129]:
def column_auswahl(df: pd.DataFrame, column_name: str) -> pd.DataFrame:
    df = df.copy()
    # 1. Spalten auswählen, die den Suchbegriff enthalten
    columns = [col for col in df.columns if column_name in col]

    # 2. Subframe erstellen
    result = df[columns + ["KUNDENNUMMER"]]

    # 3. KUNDENNUMMER als Index setzen
    result = result.set_index("KUNDENNUMMER")

    # 4. Duplikate entfernen
    result = result[~result.index.duplicated()]

    return result

test = column_auswahl(data_basis, "Newsletter")
test

,Newsletter_1_Cupon_2020,Newsletter_2_Cupon_2020,Newsletter_3_Cupon_2020,Newsletter_4_Cupon_2020,Newsletter_5_Cupon_2020,Newsletter_6_Cupon_2020,Newsletter_7_Cupon_2020,Newsletter_8_Cupon_2020,Newsletter_9_Cupon_2020,Newsletter_10_Cupon_2020,Newsletter_11_Cupon_2020,Newsletter_12_Cupon_2020,Newsletter_1_Cupon_2021,Newsletter_2_Cupon_2021,Newsletter_3_Cupon_2021,...,Newsletter_10_Cupon_2022,Newsletter_11_Cupon_2022,Newsletter_12_Cupon_2022,Newsletter_1_Cupon_2023,Newsletter_2_Cupon_2023,Newsletter_3_Cupon_2023,Newsletter_4_Cupon_2023,Newsletter_5_Cupon_2023,Newsletter_6_Cupon_2023,Newsletter_7_Cupon_2023,Newsletter_8_Cupon_2023,Newsletter_9_Cupon_2023,Newsletter_10_Cupon_2023,Newsletter_11_Cupon_2023,Newsletter_12_Cupon_2023
KUNDENNUMMER,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
27.0,nein,nein,ja,ja,ja,nein,ja,nein,ja,nein,ja,ja,nein,nein,nein,...,nein,nein,ja,nein,nein,nein,ja,nein,ja,ja,nein,ja,nein,nein,ja
87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,nein,ja,ja,nein,nein,nein,nein,ja,nein,nein,ja,nein,nein,nein,nein
76.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,nein,nein,ja,nein,nein,nein,nein,nein,nein,ja,ja,ja,nein,nein,ja
44.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25.0,nein,nein,nein,nein,nein,ja,nein,nein,nein,nein,ja,ja,NaN,NaN,NaN,...,nein,nein,nein,nein,ja,nein,ja,ja,ja,ja,nein,nein,nein,nein,ja
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### b) erweitere bzw passe die Funktion column_auswahl
- um den Parameter in_out --> dieser gibt an ob ein Dataframes erstellt wir nur mit Newslettern oder alle anderen 
<br>
out = 25079 rows × 11 columns
<br>
in = 299 rows × 48 columns

In [130]:
# True für bleibt drin, False für fällt raus
def column_auswahl2(df: pd.DataFrame, column_name: str, in_out: bool) -> pd.DataFrame:
    df = df.copy()
    columns: list

    if in_out:
        # Newsletter rein
        columns = [c for c in df.columns if column_name in c]
    else:
        # Newsletter raus
        columns = [c for c in df.columns if column_name not in c and c != "KUNDENNUMMER"]


    # 2. Subframe erstellen
    result = df[columns + ["KUNDENNUMMER"]]

    # 3. KUNDENNUMMER als Index setzen
    result = result.set_index("KUNDENNUMMER")

    # 4. Duplikate entfernen
    result = result[~result.index.duplicated()]

    # 5 Unnamed entfernen
    result = result.loc[:, ~result.columns.str.startswith("Unnamed")]

    return result

test = column_auswahl2(data_basis, "Newsletter", False)
test

,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD,YEAR
KUNDENNUMMER,,,,,,,,,,,
27.0,Rum,Asien,0.0,RE_2020_0,86.23,0.0,86.23,0.00,64.67,92.75,2020
87.0,Wein,EU,1.0,RE_2020_1,182.93,0.0,182.93,0.00,137.20,196.76,2020
76.0,Wein,Asien,2.0,RE_2020_2,103.97,0.0,103.97,0.00,77.98,111.83,2020
44.0,Whisky,USA,3.0,RE_2020_3,119.95,0.0,119.95,0.00,89.96,129.02,2020
25.0,Whisky,EU,4.0,RE_2020_4,217.43,5.0,206.56,-10.87,163.07,222.18,2020
...,...,...,...,...,...,...,...,...,...,...,...
269.0,Wein,EU,1478.0,RE_2023_1478,102.06,5.0,102.06,-5.10,76.54,104.29,2023
268.0,Rum,Asien,1545.0,RE_2023_1545,207.47,0.0,207.47,0.00,155.60,223.15,2023
290.0,Whisky,USA,1557.0,RE_2023_1557,95.49,0.0,95.49,0.00,71.62,102.71,2023
283.0,Whisky,Asien,1652.0,RE_2023_1652,226.86,0.0,226.86,0.00,170.14,244.01,2023
262.0,Whisky,Asien,2372.0,RE_2023_2372,140.62,0.0,140.62,0.00,105.46,151.25,2023

- schreibe in einen neuen Dataframes data_news_out. indem Dataframes sollen die Daten ohne Newslettercolumns

In [131]:
data_news_out = column_auswahl2(data_basis, "Newsletter", False)
data_news_out

,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD,YEAR
KUNDENNUMMER,,,,,,,,,,,
27.0,Rum,Asien,0.0,RE_2020_0,86.23,0.0,86.23,0.00,64.67,92.75,2020
87.0,Wein,EU,1.0,RE_2020_1,182.93,0.0,182.93,0.00,137.20,196.76,2020
76.0,Wein,Asien,2.0,RE_2020_2,103.97,0.0,103.97,0.00,77.98,111.83,2020
44.0,Whisky,USA,3.0,RE_2020_3,119.95,0.0,119.95,0.00,89.96,129.02,2020
25.0,Whisky,EU,4.0,RE_2020_4,217.43,5.0,206.56,-10.87,163.07,222.18,2020
...,...,...,...,...,...,...,...,...,...,...,...
269.0,Wein,EU,1478.0,RE_2023_1478,102.06,5.0,102.06,-5.10,76.54,104.29,2023
268.0,Rum,Asien,1545.0,RE_2023_1545,207.47,0.0,207.47,0.00,155.60,223.15,2023
290.0,Whisky,USA,1557.0,RE_2023_1557,95.49,0.0,95.49,0.00,71.62,102.71,2023
283.0,Whisky,Asien,1652.0,RE_2023_1652,226.86,0.0,226.86,0.00,170.14,244.01,2023
262.0,Whisky,Asien,2372.0,RE_2023_2372,140.62,0.0,140.62,0.00,105.46,151.25,2023

## Aufgabe 4: insert column by condition

- erstelle die Funktion insert_columns_after_condition
- nach Newsletter_12_Cupon_20 soll eine Column mit dem dem gleichen Columnnamen wie davor mit dem Zusatz _count hinzugefügt werden
- ändere die Variablen in dem Dataframes von ja zu 1.0 und von nein zu 0.

In [132]:
def insert_columns_after_condition(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    target_col = "Newsletter_12_Cupon_2020"

    df = df.replace({"ja": 1.0, "nein": 0.0})

    idx = df.columns.get_loc(target_col)

    # 3. neue Spalte erzeugen (z. B. identischer Inhalt)
    new_col_name = f"{target_col}_count"
    new_col_values = df[target_col]

    # 4. Spalte exakt nach target_col einfügen
    df.insert(idx + 1, new_col_name, new_col_values)

    return df

insert_columns_after_condition(column_auswahl2(data_basis, "Newsletter", True))

,Newsletter_1_Cupon_2020,Newsletter_2_Cupon_2020,Newsletter_3_Cupon_2020,Newsletter_4_Cupon_2020,Newsletter_5_Cupon_2020,Newsletter_6_Cupon_2020,Newsletter_7_Cupon_2020,Newsletter_8_Cupon_2020,Newsletter_9_Cupon_2020,Newsletter_10_Cupon_2020,Newsletter_11_Cupon_2020,Newsletter_12_Cupon_2020,Newsletter_12_Cupon_2020_count,Newsletter_1_Cupon_2021,Newsletter_2_Cupon_2021,...,Newsletter_10_Cupon_2022,Newsletter_11_Cupon_2022,Newsletter_12_Cupon_2022,Newsletter_1_Cupon_2023,Newsletter_2_Cupon_2023,Newsletter_3_Cupon_2023,Newsletter_4_Cupon_2023,Newsletter_5_Cupon_2023,Newsletter_6_Cupon_2023,Newsletter_7_Cupon_2023,Newsletter_8_Cupon_2023,Newsletter_9_Cupon_2023,Newsletter_10_Cupon_2023,Newsletter_11_Cupon_2023,Newsletter_12_Cupon_2023
KUNDENNUMMER,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
27.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0
87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
76.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0
44.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,NaN,NaN,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- schriebe eine Funktion fill_sum, welche die Summen der Werte in de Count Spalte berechnet pro Jahr

In [133]:
#bro was?`??????????????????

## Aufgabe 5: Anpassungen des Dataframes
### a) delete_col_string
- Schreibe eine Funktion, welche aus allen Columns die Bezeichnung Newsletter_ entfernt und speichere diese in einem neuen Dataframes new_cols_data

In [134]:
def delete_col_string(df: pd.DataFrame) -> pd.DataFrame:
    result = df.copy()

    result.columns = result.columns.str.replace("Newsletter_", "")
    return result

test = delete_col_string(data_basis)
test

,Unnamed: 0,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD,1_Cupon_2020,2_Cupon_2020,3_Cupon_2020,...,11_Cupon_2022,12_Cupon_2022,1_Cupon_2023,2_Cupon_2023,3_Cupon_2023,4_Cupon_2023,5_Cupon_2023,6_Cupon_2023,7_Cupon_2023,8_Cupon_2023,9_Cupon_2023,10_Cupon_2023,11_Cupon_2023,12_Cupon_2023,YEAR
0,0,Rum,Asien,0.0,RE_2020_0,27.0,86.23,0.0,86.23,0.00,64.67,92.75,nein,nein,ja,...,nein,ja,nein,nein,nein,ja,nein,ja,ja,nein,ja,nein,nein,ja,2020
1,1,Wein,EU,1.0,RE_2020_1,87.0,182.93,0.0,182.93,0.00,137.20,196.76,NaN,NaN,NaN,...,ja,ja,nein,nein,nein,nein,ja,nein,nein,ja,nein,nein,nein,nein,2020
2,2,Wein,Asien,2.0,RE_2020_2,76.0,103.97,0.0,103.97,0.00,77.98,111.83,NaN,NaN,NaN,...,nein,ja,nein,nein,nein,nein,nein,nein,ja,ja,ja,nein,nein,ja,2020
3,3,Whisky,USA,3.0,RE_2020_3,44.0,119.95,0.0,119.95,0.00,89.96,129.02,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
4,4,Whisky,EU,4.0,RE_2020_4,25.0,217.43,5.0,206.56,-10.87,163.07,222.18,nein,nein,nein,...,nein,nein,nein,ja,nein,ja,ja,ja,ja,nein,nein,nein,nein,ja,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25074,25074,Whisky,EU,9995.0,RE_2023_9995,228.0,206.73,0.0,206.73,0.00,155.05,222.36,NaN,NaN,NaN,...,nein,nein,nein,nein,nein,nein,nein,nein,nein,ja,nein,nein,nein,nein,2023
25075,25075,Whisky,EU,9996.0,RE_2023_9996,126.0,117.78,0.0,117.78,0.00,88.34,126.68,NaN,NaN,NaN,...,nein,ja,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023
25076,25076,Wein,EU,9997.0,RE_2023_9997,253.0,105.83,0.0,105.83,0.00,79.37,113.83,NaN,NaN,NaN,...,nein,nein,ja,nein,nein,nein,ja,nein,nein,nein,ja,nein,nein,ja,2023
25077,25077,Whisky,EU,9998.0,RE_2023_9998,215.0,175.00,0.0,175.00,0.00,131.25,188.23,NaN,NaN,NaN,...,nein,ja,nein,nein,ja,nein,nein,nein,nein,nein,nein,nein,nein,ja,2023
25078,25078,Whisky,EU,9999.0,RE_2023_9999,141.0,113.73,10.0,113.73,-11.37,85.30,110.10,NaN,NaN,NaN,...,nein,ja,ja,nein,ja,nein,ja,ja,nein,nein,nein,nein,nein,nein,2023

### b) add Columnbezeichnung
- füge an alle Columns am Ende _end und zu Beginn start_ an

In [135]:
def add_start_end(df: pd.DataFrame) -> pd.DataFrame:
    result = df.copy()

    result.columns = "start_" + result.columns + "_end"
    return result

test = add_start_end(data_basis)
test

,start_Unnamed: 0_end,start_GETRAENK_end,start_REGION_end,start_BESTELLNUMMER_end,start_RECHNUNGSNUMMER_end,start_KUNDENNUMMER_end,start_LISTENPREIS_end,start_RABATT_IN_PROZENT_end,start_VERKAUFSPREIS_end,start_RABATT_PREIS_end,start_EINKAUFPREIS_end,start_VK_PERIS_IN_USD_end,start_Newsletter_1_Cupon_2020_end,start_Newsletter_2_Cupon_2020_end,start_Newsletter_3_Cupon_2020_end,...,start_Newsletter_11_Cupon_2022_end,start_Newsletter_12_Cupon_2022_end,start_Newsletter_1_Cupon_2023_end,start_Newsletter_2_Cupon_2023_end,start_Newsletter_3_Cupon_2023_end,start_Newsletter_4_Cupon_2023_end,start_Newsletter_5_Cupon_2023_end,start_Newsletter_6_Cupon_2023_end,start_Newsletter_7_Cupon_2023_end,start_Newsletter_8_Cupon_2023_end,start_Newsletter_9_Cupon_2023_end,start_Newsletter_10_Cupon_2023_end,start_Newsletter_11_Cupon_2023_end,start_Newsletter_12_Cupon_2023_end,start_YEAR_end
0,0,Rum,Asien,0.0,RE_2020_0,27.0,86.23,0.0,86.23,0.00,64.67,92.75,nein,nein,ja,...,nein,ja,nein,nein,nein,ja,nein,ja,ja,nein,ja,nein,nein,ja,2020
1,1,Wein,EU,1.0,RE_2020_1,87.0,182.93,0.0,182.93,0.00,137.20,196.76,NaN,NaN,NaN,...,ja,ja,nein,nein,nein,nein,ja,nein,nein,ja,nein,nein,nein,nein,2020
2,2,Wein,Asien,2.0,RE_2020_2,76.0,103.97,0.0,103.97,0.00,77.98,111.83,NaN,NaN,NaN,...,nein,ja,nein,nein,nein,nein,nein,nein,ja,ja,ja,nein,nein,ja,2020
3,3,Whisky,USA,3.0,RE_2020_3,44.0,119.95,0.0,119.95,0.00,89.96,129.02,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
4,4,Whisky,EU,4.0,RE_2020_4,25.0,217.43,5.0,206.56,-10.87,163.07,222.18,nein,nein,nein,...,nein,nein,nein,ja,nein,ja,ja,ja,ja,nein,nein,nein,nein,ja,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25074,25074,Whisky,EU,9995.0,RE_2023_9995,228.0,206.73,0.0,206.73,0.00,155.05,222.36,NaN,NaN,NaN,...,nein,nein,nein,nein,nein,nein,nein,nein,nein,ja,nein,nein,nein,nein,2023
25075,25075,Whisky,EU,9996.0,RE_2023_9996,126.0,117.78,0.0,117.78,0.00,88.34,126.68,NaN,NaN,NaN,...,nein,ja,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023
25076,25076,Wein,EU,9997.0,RE_2023_9997,253.0,105.83,0.0,105.83,0.00,79.37,113.83,NaN,NaN,NaN,...,nein,nein,ja,nein,nein,nein,ja,nein,nein,nein,ja,nein,nein,ja,2023
25077,25077,Whisky,EU,9998.0,RE_2023_9998,215.0,175.00,0.0,175.00,0.00,131.25,188.23,NaN,NaN,NaN,...,nein,ja,nein,nein,ja,nein,nein,nein,nein,nein,nein,nein,nein,ja,2023
25078,25078,Whisky,EU,9999.0,RE_2023_9999,141.0,113.73,10.0,113.73,-11.37,85.30,110.10,NaN,NaN,NaN,...,nein,ja,ja,nein,ja,nein,ja,ja,nein,nein,nein,nein,nein,nein,2023

### c) prepare_every_second_column
schriebe eine Funktion prepare_every_second_column
- welche am Ende _ungerade anfügt, wenn zu Beginn des Columnnamens eine ungerade Zahl steht

In [136]:
# ich denke mal er meint einfach jede zweite column umbenennen
# ich gehe davon aus, dass die erste spalte den index 0 hat also ist die zweite spalte ungerade
def prepare_every_second_column(df: pd.DataFrame) -> pd.DataFrame:
    result = df.copy()

    result.columns = [f"{col}_ungerade" if i % 2 != 0 else col for i, col in enumerate(result.columns)]

    return result

test = prepare_every_second_column(data_basis)
test

,Unnamed: 0,GETRAENK_ungerade,REGION,BESTELLNUMMER_ungerade,RECHNUNGSNUMMER,KUNDENNUMMER_ungerade,LISTENPREIS,RABATT_IN_PROZENT_ungerade,VERKAUFSPREIS,RABATT_PREIS_ungerade,EINKAUFPREIS,VK_PERIS_IN_USD_ungerade,Newsletter_1_Cupon_2020,Newsletter_2_Cupon_2020_ungerade,Newsletter_3_Cupon_2020,...,Newsletter_11_Cupon_2022,Newsletter_12_Cupon_2022_ungerade,Newsletter_1_Cupon_2023,Newsletter_2_Cupon_2023_ungerade,Newsletter_3_Cupon_2023,Newsletter_4_Cupon_2023_ungerade,Newsletter_5_Cupon_2023,Newsletter_6_Cupon_2023_ungerade,Newsletter_7_Cupon_2023,Newsletter_8_Cupon_2023_ungerade,Newsletter_9_Cupon_2023,Newsletter_10_Cupon_2023_ungerade,Newsletter_11_Cupon_2023,Newsletter_12_Cupon_2023_ungerade,YEAR
0,0,Rum,Asien,0.0,RE_2020_0,27.0,86.23,0.0,86.23,0.00,64.67,92.75,nein,nein,ja,...,nein,ja,nein,nein,nein,ja,nein,ja,ja,nein,ja,nein,nein,ja,2020
1,1,Wein,EU,1.0,RE_2020_1,87.0,182.93,0.0,182.93,0.00,137.20,196.76,NaN,NaN,NaN,...,ja,ja,nein,nein,nein,nein,ja,nein,nein,ja,nein,nein,nein,nein,2020
2,2,Wein,Asien,2.0,RE_2020_2,76.0,103.97,0.0,103.97,0.00,77.98,111.83,NaN,NaN,NaN,...,nein,ja,nein,nein,nein,nein,nein,nein,ja,ja,ja,nein,nein,ja,2020
3,3,Whisky,USA,3.0,RE_2020_3,44.0,119.95,0.0,119.95,0.00,89.96,129.02,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
4,4,Whisky,EU,4.0,RE_2020_4,25.0,217.43,5.0,206.56,-10.87,163.07,222.18,nein,nein,nein,...,nein,nein,nein,ja,nein,ja,ja,ja,ja,nein,nein,nein,nein,ja,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25074,25074,Whisky,EU,9995.0,RE_2023_9995,228.0,206.73,0.0,206.73,0.00,155.05,222.36,NaN,NaN,NaN,...,nein,nein,nein,nein,nein,nein,nein,nein,nein,ja,nein,nein,nein,nein,2023
25075,25075,Whisky,EU,9996.0,RE_2023_9996,126.0,117.78,0.0,117.78,0.00,88.34,126.68,NaN,NaN,NaN,...,nein,ja,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023
25076,25076,Wein,EU,9997.0,RE_2023_9997,253.0,105.83,0.0,105.83,0.00,79.37,113.83,NaN,NaN,NaN,...,nein,nein,ja,nein,nein,nein,ja,nein,nein,nein,ja,nein,nein,ja,2023
25077,25077,Whisky,EU,9998.0,RE_2023_9998,215.0,175.00,0.0,175.00,0.00,131.25,188.23,NaN,NaN,NaN,...,nein,ja,nein,nein,ja,nein,nein,nein,nein,nein,nein,nein,nein,ja,2023
25078,25078,Whisky,EU,9999.0,RE_2023_9999,141.0,113.73,10.0,113.73,-11.37,85.30,110.10,NaN,NaN,NaN,...,nein,ja,ja,nein,ja,nein,ja,ja,nein,nein,nein,nein,nein,nein,2023

### d) Datenobjekte in dem Dataframe ändern
- ändere die float Werte aus data_news_out in int Werte
- verwende hierfür einen for loop und select_dtypes

In [137]:
for col in data_news_out.select_dtypes(include="float").columns:
    data_news_out[col] = data_news_out[col].astype(int)
data_news_out.dtypes

GETRAENK             str
REGION               str
BESTELLNUMMER      int64
RECHNUNGSNUMMER      str
LISTENPREIS        int64
                   ...
VERKAUFSPREIS      int64
RABATT_PREIS       int64
EINKAUFPREIS       int64
VK_PERIS_IN_USD    int64
YEAR                 str
Length: 11, dtype: object

- ändere nun alle int Columns to float Columns

In [138]:
for col in data_news_out.select_dtypes(include="int").columns:
    data_news_out[col] = data_news_out[col].astype(float)
data_news_out.dtypes

GETRAENK               str
REGION                 str
BESTELLNUMMER      float64
RECHNUNGSNUMMER        str
LISTENPREIS        float64
                    ...
VERKAUFSPREIS      float64
RABATT_PREIS       float64
EINKAUFPREIS       float64
VK_PERIS_IN_USD    float64
YEAR                   str
Length: 11, dtype: object

### e) Verteilung der verschiedenen Ausprägungen der Columns
- Zähle die verschiedenen Ausprägungen der Column GETRAENK

In [141]:
data_basis.value_counts(subset="GETRAENK")

GETRAENK
Whisky        13747
Wein           6287
Champagner     2554
Rum            2478
Name: count, dtype: int64

- die prozentuale Verteilung der Ausprägungen der Column REGION

In [143]:
data_basis["REGION"].value_counts(normalize=True) * 100

REGION
EU       50.137576
USA      29.915859
Asien    19.946565
Name: proportion, dtype: float64

### f) Wertevergleich von zwei Columns
- führe den unteren Code aus, um eine neue Column mit zufälligen Werten zuerhalten

In [150]:
choice = ["Rum", "Wein", "Whisky", "Champagner"]
data_basis["GETRAENK_2"] = [random.choice(choice) for i in range(data_basis.shape[0])]
data_basis.value_counts(subset="GETRAENK_2")

GETRAENK_2
Champagner    6395
Whisky        6302
Wein          6240
Rum           6142
Name: count, dtype: int64

- erstele eine neue Column mit dem Namen Difference 
- überprufe in jedem Record, ob in der Column GETRAENK und GETRAENK_2 die gleichen Werte bestehen
- wenn identisch soll GETRAENK in die Column Difference ansonsten JA
**Tipp** apply und lambda

In [152]:
data_basis["DIFFERENCE"] = data_basis.apply(lambda row: row["GETRAENK"] if row["GETRAENK"] == row["GETRAENK_2"] else "Ja", axis=1)
data_basis.value_counts("DIFFERENCE")

DIFFERENCE
Ja            18779
Whisky         3438
Wein           1585
Champagner      653
Rum             624
Name: count, dtype: int64

- erstelle einen Sub-Dataframes, welcher nur die beiden Columns GETRAENK und GETRAENK_2 identisch haben

In [153]:
sub_df = data_basis[data_basis["DIFFERENCE"] == "Ja"]
sub_df

,Unnamed: 0,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD,Newsletter_1_Cupon_2020,Newsletter_2_Cupon_2020,Newsletter_3_Cupon_2020,...,Newsletter_1_Cupon_2023,Newsletter_2_Cupon_2023,Newsletter_3_Cupon_2023,Newsletter_4_Cupon_2023,Newsletter_5_Cupon_2023,Newsletter_6_Cupon_2023,Newsletter_7_Cupon_2023,Newsletter_8_Cupon_2023,Newsletter_9_Cupon_2023,Newsletter_10_Cupon_2023,Newsletter_11_Cupon_2023,Newsletter_12_Cupon_2023,YEAR,GETRAENK_2,DIFFERENCE
0,0,Rum,Asien,0.0,RE_2020_0,27.0,86.23,0.0,86.23,0.00,64.67,92.75,nein,nein,ja,...,nein,nein,nein,ja,nein,ja,ja,nein,ja,nein,nein,ja,2020,Champagner,Ja
1,1,Wein,EU,1.0,RE_2020_1,87.0,182.93,0.0,182.93,0.00,137.20,196.76,NaN,NaN,NaN,...,nein,nein,nein,nein,ja,nein,nein,ja,nein,nein,nein,nein,2020,Champagner,Ja
2,2,Wein,Asien,2.0,RE_2020_2,76.0,103.97,0.0,103.97,0.00,77.98,111.83,NaN,NaN,NaN,...,nein,nein,nein,nein,nein,nein,ja,ja,ja,nein,nein,ja,2020,Whisky,Ja
3,3,Whisky,USA,3.0,RE_2020_3,44.0,119.95,0.0,119.95,0.00,89.96,129.02,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020,Champagner,Ja
4,4,Whisky,EU,4.0,RE_2020_4,25.0,217.43,5.0,206.56,-10.87,163.07,222.18,nein,nein,nein,...,nein,ja,nein,ja,ja,ja,ja,nein,nein,nein,nein,ja,2020,Champagner,Ja
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25072,25072,Wein,EU,9993.0,RE_2023_9993,177.0,197.52,10.0,197.52,-19.75,148.14,191.21,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,Champagner,Ja
25073,25073,Whisky,EU,9994.0,RE_2023_9994,116.0,155.83,0.0,155.83,0.00,116.87,167.61,NaN,NaN,NaN,...,nein,nein,nein,nein,nein,ja,ja,ja,nein,nein,nein,ja,2023,Wein,Ja
25074,25074,Whisky,EU,9995.0,RE_2023_9995,228.0,206.73,0.0,206.73,0.00,155.05,222.36,NaN,NaN,NaN,...,nein,nein,nein,nein,nein,nein,nein,ja,nein,nein,nein,nein,2023,Wein,Ja
25075,25075,Whisky,EU,9996.0,RE_2023_9996,126.0,117.78,0.0,117.78,0.00,88.34,126.68,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,Champagner,Ja
25076,25076,Wein,EU,9997.0,RE_2023_9997,253.0,105.83,0.0,105.83,0.00,79.37,113.83,NaN,NaN,NaN,...,ja,nein,nein,nein,ja,nein,nein,nein,ja,nein,nein,ja,2023,Whisky,Ja

- Bestimme in einer neuen Column ob der LISTENPREIS über 130 ist

In [154]:
data_basis["LISTENPREIS_GROESSER_130"] = data_basis.apply(lambda row: True if row["LISTENPREIS"] > 130 else False, axis=1)
data_basis

,Unnamed: 0,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD,Newsletter_1_Cupon_2020,Newsletter_2_Cupon_2020,Newsletter_3_Cupon_2020,...,Newsletter_2_Cupon_2023,Newsletter_3_Cupon_2023,Newsletter_4_Cupon_2023,Newsletter_5_Cupon_2023,Newsletter_6_Cupon_2023,Newsletter_7_Cupon_2023,Newsletter_8_Cupon_2023,Newsletter_9_Cupon_2023,Newsletter_10_Cupon_2023,Newsletter_11_Cupon_2023,Newsletter_12_Cupon_2023,YEAR,GETRAENK_2,DIFFERENCE,LISTENPREIS_GROESSER_130
0,0,Rum,Asien,0.0,RE_2020_0,27.0,86.23,0.0,86.23,0.00,64.67,92.75,nein,nein,ja,...,nein,nein,ja,nein,ja,ja,nein,ja,nein,nein,ja,2020,Champagner,Ja,False
1,1,Wein,EU,1.0,RE_2020_1,87.0,182.93,0.0,182.93,0.00,137.20,196.76,NaN,NaN,NaN,...,nein,nein,nein,ja,nein,nein,ja,nein,nein,nein,nein,2020,Champagner,Ja,True
2,2,Wein,Asien,2.0,RE_2020_2,76.0,103.97,0.0,103.97,0.00,77.98,111.83,NaN,NaN,NaN,...,nein,nein,nein,nein,nein,ja,ja,ja,nein,nein,ja,2020,Whisky,Ja,False
3,3,Whisky,USA,3.0,RE_2020_3,44.0,119.95,0.0,119.95,0.00,89.96,129.02,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020,Champagner,Ja,False
4,4,Whisky,EU,4.0,RE_2020_4,25.0,217.43,5.0,206.56,-10.87,163.07,222.18,nein,nein,nein,...,ja,nein,ja,ja,ja,ja,nein,nein,nein,nein,ja,2020,Champagner,Ja,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25074,25074,Whisky,EU,9995.0,RE_2023_9995,228.0,206.73,0.0,206.73,0.00,155.05,222.36,NaN,NaN,NaN,...,nein,nein,nein,nein,nein,nein,ja,nein,nein,nein,nein,2023,Wein,Ja,True
25075,25075,Whisky,EU,9996.0,RE_2023_9996,126.0,117.78,0.0,117.78,0.00,88.34,126.68,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,Champagner,Ja,False
25076,25076,Wein,EU,9997.0,RE_2023_9997,253.0,105.83,0.0,105.83,0.00,79.37,113.83,NaN,NaN,NaN,...,nein,nein,nein,ja,nein,nein,nein,ja,nein,nein,ja,2023,Whisky,Ja,False
25077,25077,Whisky,EU,9998.0,RE_2023_9998,215.0,175.00,0.0,175.00,0.00,131.25,188.23,NaN,NaN,NaN,...,nein,ja,nein,nein,nein,nein,nein,nein,nein,nein,ja,2023,Whisky,Whisky,True
25078,25078,Whisky,EU,9999.0,RE_2023_9999,141.0,113.73,10.0,113.73,-11.37,85.30,110.10,NaN,NaN,NaN,...,nein,ja,nein,ja,ja,nein,nein,nein,nein,nein,nein,2023,Whisky,Whisky,False

### g) isin
- verändere den Datentyp der Column JAHR in int
- bilde jeweils einen Sub-Dataframes für die Jahre 2021 und 2020 und den Rechnungen aus diesen Jahren

In [168]:
data_basis["YEAR"] = data_basis["YEAR"].astype(int)

sub_2020 = data_basis[data_basis["YEAR"].isin([2020])]
sub_2021 = data_basis[data_basis["YEAR"].isin([2021])]

print(sub_2020.shape)
print(sub_2021.shape)

(2000, 64)
(5000, 64)

- finde alle Records in 2021, welche auch in 2020 enthalten sind

In [163]:
# aufgabe ergibt keinen sinn: wann sind einträge gleich zu stellen? wenn der selbe Kunde kauft? wenn es die selbe Bestellnummer hat?
# Bestellnummer ist bspw. eine inkrementierende zahl also könnte es nichtmal vorkommen
# aber scheinbar gibts trotzdem welche ?!


records_2020_2021 = sub_2021[sub_2021["BESTELLNUMMER"].isin(sub_2020["BESTELLNUMMER"])]
records_2020_2021

,Unnamed: 0,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD,Newsletter_1_Cupon_2020,Newsletter_2_Cupon_2020,Newsletter_3_Cupon_2020,...,Newsletter_2_Cupon_2023,Newsletter_3_Cupon_2023,Newsletter_4_Cupon_2023,Newsletter_5_Cupon_2023,Newsletter_6_Cupon_2023,Newsletter_7_Cupon_2023,Newsletter_8_Cupon_2023,Newsletter_9_Cupon_2023,Newsletter_10_Cupon_2023,Newsletter_11_Cupon_2023,Newsletter_12_Cupon_2023,YEAR,GETRAENK_2,DIFFERENCE,LISTENPREIS_GROESSER_130
2000,2000,Wein,EU,0.0,RE_2021_0,114.0,210.38,0.0,210.38,0.00,157.78,226.28,NaN,NaN,NaN,...,nein,ja,nein,nein,ja,nein,nein,nein,nein,nein,nein,2021,Champagner,Ja,True
2001,2001,Whisky,Asien,1.0,RE_2021_1,57.0,223.11,0.0,223.11,0.00,167.33,239.98,NaN,NaN,NaN,...,nein,nein,nein,nein,nein,ja,ja,nein,nein,nein,ja,2021,Whisky,Whisky,True
2002,2002,Whisky,EU,2.0,RE_2021_2,125.0,218.12,0.0,218.12,0.00,163.59,234.61,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,Champagner,Ja,True
2003,2003,Champagner,Asien,3.0,RE_2021_3,69.0,179.72,0.0,179.72,0.00,134.79,193.31,NaN,NaN,NaN,...,ja,nein,ja,nein,ja,ja,nein,nein,nein,nein,ja,2021,Rum,Ja,True
2004,2004,Champagner,EU,4.0,RE_2021_4,71.0,83.83,5.0,79.64,-4.19,62.87,85.66,nein,nein,ja,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,Rum,Ja,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,3995,Rum,EU,1995.0,RE_2021_1995,59.0,127.26,0.0,127.26,0.00,95.44,136.88,nein,nein,nein,...,nein,nein,nein,nein,ja,ja,ja,nein,nein,nein,ja,2021,Wein,Ja,False
3996,3996,Whisky,EU,1996.0,RE_2021_1996,104.0,85.42,0.0,85.42,0.00,64.06,91.88,NaN,NaN,NaN,...,nein,nein,ja,ja,nein,ja,ja,nein,nein,nein,nein,2021,Rum,Ja,False
3997,3997,Rum,USA,1997.0,RE_2021_1997,118.0,176.02,10.0,158.42,-17.60,132.02,170.40,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,Wein,Ja,True
3998,3998,Wein,USA,1998.0,RE_2021_1998,157.0,124.58,0.0,124.58,0.00,93.44,134.00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,Rum,Ja,False
3999,3999,Wein,EU,1999.0,RE_2021_1999,124.0,178.94,5.0,169.99,-8.95,134.20,182.84,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,Rum,Ja,True

- finde alle Records im Dataframes 2021, welche nicht im Dataframes 2020 enthalten sind

In [166]:
not_records_2020_2021 = sub_2021[~sub_2021["BESTELLNUMMER"].isin(sub_2020["BESTELLNUMMER"])]
not_records_2020_2021

,Unnamed: 0,GETRAENK,REGION,BESTELLNUMMER,RECHNUNGSNUMMER,KUNDENNUMMER,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD,Newsletter_1_Cupon_2020,Newsletter_2_Cupon_2020,Newsletter_3_Cupon_2020,...,Newsletter_2_Cupon_2023,Newsletter_3_Cupon_2023,Newsletter_4_Cupon_2023,Newsletter_5_Cupon_2023,Newsletter_6_Cupon_2023,Newsletter_7_Cupon_2023,Newsletter_8_Cupon_2023,Newsletter_9_Cupon_2023,Newsletter_10_Cupon_2023,Newsletter_11_Cupon_2023,Newsletter_12_Cupon_2023,YEAR,GETRAENK_2,DIFFERENCE,LISTENPREIS_GROESSER_130
4000,4000,Champagner,USA,2000.0,RE_2021_2000,66.0,162.30,0.0,162.30,0.00,121.72,174.57,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,Whisky,Ja,True
4001,4001,Whisky,EU,2001.0,RE_2021_2001,133.0,83.64,0.0,83.64,0.00,62.73,89.96,NaN,NaN,NaN,...,nein,nein,nein,ja,nein,nein,ja,nein,nein,nein,ja,2021,Wein,Ja,False
4002,4002,Whisky,EU,2002.0,RE_2021_2002,76.0,175.85,0.0,175.85,0.00,131.89,189.14,NaN,NaN,NaN,...,nein,nein,nein,nein,nein,ja,ja,ja,nein,nein,ja,2021,Rum,Ja,True
4003,4003,Wein,EU,2003.0,RE_2021_2003,129.0,151.37,0.0,151.37,0.00,113.53,162.81,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,Rum,Ja,True
4004,4004,Rum,USA,2004.0,RE_2021_2004,90.0,109.80,0.0,109.80,0.00,82.35,118.10,NaN,NaN,NaN,...,nein,nein,nein,nein,ja,nein,ja,nein,nein,nein,ja,2021,Wein,Ja,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,6995,Rum,EU,4995.0,RE_2021_4995,128.0,126.20,5.0,119.89,-6.31,94.65,128.95,NaN,NaN,NaN,...,nein,ja,nein,nein,ja,ja,ja,nein,nein,nein,ja,2021,Wein,Ja,False
6996,6996,Whisky,EU,4996.0,RE_2021_4996,130.0,130.73,0.0,130.73,0.00,98.05,140.61,NaN,NaN,NaN,...,nein,ja,nein,nein,ja,ja,nein,nein,nein,nein,ja,2021,Champagner,Ja,True
6997,6997,Wein,USA,4997.0,RE_2021_4997,103.0,221.26,0.0,221.26,0.00,165.94,237.99,NaN,NaN,NaN,...,nein,ja,nein,ja,nein,nein,ja,nein,nein,nein,nein,2021,Champagner,Ja,True
6998,6998,Wein,EU,4998.0,RE_2021_4998,141.0,112.46,0.0,112.46,0.00,84.34,120.96,NaN,NaN,NaN,...,nein,ja,nein,ja,ja,nein,nein,nein,nein,nein,nein,2021,Whisky,Ja,False
6999,6999,Whisky,Asien,4999.0,RE_2021_4999,147.0,100.00,0.0,100.00,0.00,75.00,107.56,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,Champagner,Ja,False

- erstelle zwei Dataframes in dem ersten Dataframe sollen die ersten 6 Columns enthalten sein und dem anderen Dataframes die anderen Columns
- probiere dies in einer Reihe zu schrieben

In [169]:
df_first6, df_rest = data_basis.iloc[:, :6], data_basis.iloc[:, 6:]

In [170]:
df_first6

       Unnamed: 0 GETRAENK REGION  BESTELLNUMMER RECHNUNGSNUMMER  KUNDENNUMMER
0               0      Rum  Asien            0.0       RE_2020_0          27.0
1               1     Wein     EU            1.0       RE_2020_1          87.0
2               2     Wein  Asien            2.0       RE_2020_2          76.0
3               3   Whisky    USA            3.0       RE_2020_3          44.0
4               4   Whisky     EU            4.0       RE_2020_4          25.0
...           ...      ...    ...            ...             ...           ...
25074       25074   Whisky     EU         9995.0    RE_2023_9995         228.0
25075       25075   Whisky     EU         9996.0    RE_2023_9996         126.0
25076       25076     Wein     EU         9997.0    RE_2023_9997         253.0
25077       25077   Whisky     EU         9998.0    RE_2023_9998         215.0
25078       25078   Whisky     EU         9999.0    RE_2023_9999         141.0

[25079 rows x 6 columns]

In [171]:
df_rest

,LISTENPREIS,RABATT_IN_PROZENT,VERKAUFSPREIS,RABATT_PREIS,EINKAUFPREIS,VK_PERIS_IN_USD,Newsletter_1_Cupon_2020,Newsletter_2_Cupon_2020,Newsletter_3_Cupon_2020,Newsletter_4_Cupon_2020,Newsletter_5_Cupon_2020,Newsletter_6_Cupon_2020,Newsletter_7_Cupon_2020,Newsletter_8_Cupon_2020,Newsletter_9_Cupon_2020,...,Newsletter_2_Cupon_2023,Newsletter_3_Cupon_2023,Newsletter_4_Cupon_2023,Newsletter_5_Cupon_2023,Newsletter_6_Cupon_2023,Newsletter_7_Cupon_2023,Newsletter_8_Cupon_2023,Newsletter_9_Cupon_2023,Newsletter_10_Cupon_2023,Newsletter_11_Cupon_2023,Newsletter_12_Cupon_2023,YEAR,GETRAENK_2,DIFFERENCE,LISTENPREIS_GROESSER_130
0,86.23,0.0,86.23,0.00,64.67,92.75,nein,nein,ja,ja,ja,nein,ja,nein,ja,...,nein,nein,ja,nein,ja,ja,nein,ja,nein,nein,ja,2020,Champagner,Ja,False
1,182.93,0.0,182.93,0.00,137.20,196.76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,nein,nein,nein,ja,nein,nein,ja,nein,nein,nein,nein,2020,Champagner,Ja,True
2,103.97,0.0,103.97,0.00,77.98,111.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,nein,nein,nein,nein,nein,ja,ja,ja,nein,nein,ja,2020,Whisky,Ja,False
3,119.95,0.0,119.95,0.00,89.96,129.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020,Champagner,Ja,False
4,217.43,5.0,206.56,-10.87,163.07,222.18,nein,nein,nein,nein,nein,ja,nein,nein,nein,...,ja,nein,ja,ja,ja,ja,nein,nein,nein,nein,ja,2020,Champagner,Ja,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25074,206.73,0.0,206.73,0.00,155.05,222.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,nein,nein,nein,nein,nein,nein,ja,nein,nein,nein,nein,2023,Wein,Ja,True
25075,117.78,0.0,117.78,0.00,88.34,126.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,Champagner,Ja,False
25076,105.83,0.0,105.83,0.00,79.37,113.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,nein,nein,nein,ja,nein,nein,nein,ja,nein,nein,ja,2023,Whisky,Ja,False
25077,175.00,0.0,175.00,0.00,131.25,188.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,nein,ja,nein,nein,nein,nein,nein,nein,nein,nein,ja,2023,Whisky,Whisky,True
25078,113.73,10.0,113.73,-11.37,85.30,110.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,nein,ja,nein,ja,ja,nein,nein,nein,nein,nein,nein,2023,Whisky,Whisky,False