# Ubungsskript 11: weitere Aufgaben

importiere die folgenden Bibliotheken
- pandas
- numpay
- from datetime das modul datetime
- random

## Aufgabe 1: 
- Erstelle einen Dataframe `tele_data_export` mit: 
<br>
"Akkulaufzeit": [12, 24, 16, 20, 12, 30], <br>
"Aufladezeit": [2, 3, 1, 2, 1, 2], <br>
"Verkaufte Geräte": [300, 500, 200, 200, 150, 400] <br>

- und exportiere diese Datei, als csv unter dem Namen `tele_data_export.csv` ohne den Index mitzugeben

## Aufgabe 2:
- anzeigen des csv-files als DataFrame `tele_data_export` und dessen Ausgabe als `tele_data`
- anzeigen des csv-files als DataFrame `tele_data_export` und dessen Ausgabe als `tele_data_test` mit folgenden Bedingunen:
    - Die Column Bezeichnungen sollen: "AKKU", "LADE", "MENGE"
    - die zweite und dritte Row soll nicht mit geladen werden
    - es sollen nur drei Elemente geladen werden

   AKKU  LADE  MENGE
0    12     2    300
1    20     2    200
2    12     1    150

## Aufgabe 3 a: 
- Schriebe die Columnnamen von `tele_data` in Grossbuchstaben für
- entferne die Leerzeichen mit einem Unterstrich `_`

   AKKULAUFZEIT  AUFLADEZEIT  VERKAUFTE_GERÄTE
0            12            2               300
1            24            3               500
2            16            1               200
3            20            2               200
4            12            1               150
5            30            2               400

## Aufgabe 3 b:
- füge allen Column aus dem Datframe `tele_data_test` am Anfang die Zahl `1_` an und am Ende `_#` und gebe den neuen Dataframe aus

   1_AKKU_#  1_LADE_#  1_MENGE_#
0        12         2        300
1        20         2        200
2        12         1        150

## Aufgabe 4:
- Finde mithilfe der agg() Methode im Dataframe `tele_data` folgende Werte
    - Die Durchschnittliche Akkulaufzeit
    - Die minimale und Maximale Aufladezeit
    - Die Summe der verkauften Geräte

      AKKULAUFZEIT
mean          19.0

     AUFLADEZEIT
min            1
max            3

     VERKAUFTE_GERÄTE
sum              1750

## Aufgabe 5:
- schreibe die Daten `bundesliga` in eine Excel-Datei mit dem Namen `Budesliga_Tore.xlsx` und einem Blattnamen `Uebersicht`
- füge anschliessend dem Excel in einem zusätzlichen Sheet die `tele_data` hinzu

In [ ]:
bundesliga = pd.DataFrame([[48, 100, 84], [52, 99, 75], [58, 97, 85]], 
                          index=['19/20', '20/21', '21/22'], 
                          columns=['SCFreiburg', 'FCBayernMünchen', 'BorussiaDortmund'])

## Aufgabe 6:
- lese aus der Bundesliga_Tore.xlsx beide Tabellen aus
- lese aus der Bundesliga_Tore.xlsx den Sheet `Uebersicht` aus und speichere diesen in der Variable `bundesliga_neu`

{'Uebersicht':   Unnamed: 0  SCFreiburg  FCBayernMünchen  BorussiaDortmund
 0      19/20          48              100                84
 1      20/21          52               99                75
 2      21/22          58               97                85,
 'neu':    Unnamed: 0  AKKULAUFZEIT  AUFLADEZEIT  VERKAUFTE_GERÄTE
 0           0            12            2               300
 1           1            24            3               500
 2           2            16            1               200
 3           3            20            2               200
 4           4            12            1               150
 5           5            30            2               400}

  Unnamed: 0  SCFreiburg  FCBayernMünchen  BorussiaDortmund
0      19/20          48              100                84
1      20/21          52               99                75
2      21/22          58               97                85

## Aufgabe 7: 
Gegeben sind 2 Dictionary mit jeweils unterschiedlichen Informationen über die Kunden, eines Autohändlers.
1) Wandle zuerst die Kundendaten in 2 Dataframes um
2) Wandle nun die 2 Dataframes zu einem neuen Dataframe um, welcher alle gegeben Kundendaten in beiden Daten enthält 
    - mittels `merge`

3 rows --> 9232 und 9231 stimmen nicht überein

In [ ]:
data1 = {
"customer_id": ["4321", "5928", "4229","9231"],
"name": ["Müller", "Schmidt", "Schulz", "Müller"], "age": [49, 32,72,36],
"location": ["Mannheim", "Leipzig", "Berlin", "Dresden"]
}

data2 = {
"customer_id": ["4321", "5928", "4229","9232"], "model": ["A1","A5", "Q7", "R8"],
"colour": ["rot", "weiß", "schwarz", "schwarz"]
}

  customer_id     name  age  location model   colour
0        4321   Müller   49  Mannheim    A1      rot
1        5928  Schmidt   32   Leipzig    A5     weiß
2        4229   Schulz   72    Berlin    Q7  schwarz

## Aufgabe 8: concat
- a) Konkatenieren Sie `italy_weather und canada_weather` zu einem einzigen DataFrame `wetter` und printen Sie das Ergebnis aus
- b) Konkatenieren Sie `italy_weather und canada_weather` zu einem einzigen DataFrame `wetter_b` und stellen Sie sicher, dass der Index ignoriert wird, d.h. die Indexes der beiden DataFrames werden neu nummeriert. Printen Sie das Ergebnis aus.
- c) Konkatenieren Sie `italy_weather und canada_weather` zu einem einzigen DataFrame `wetter_c` und fügen Sie eine Hierarchieebene (keys) hinzu, um die Herkunft der Daten (Italy / Canada) zu kennzeichnen. Printen Sie das Ergebnis aus.

In [19]:
italy_weather = pd.DataFrame({"city": ["rome","milan","florence"], "temperature": [25,32,27]})
canada_weather = pd.DataFrame({"city": ["toronto","vancouver","montreal"],"temperature": [-2,10,-5]})

In [20]:
# a)

        city  temperature
0       rome           25
1      milan           32
2   florence           27
0    toronto           -2
1  vancouver           10
2   montreal           -5

In [21]:
#b)

        city  temperature
0       rome           25
1      milan           32
2   florence           27
3    toronto           -2
4  vancouver           10
5   montreal           -5

In [22]:
#c)

               city  temperature
Italy  0       rome           25
       1      milan           32
       2   florence           27
Canada 0    toronto           -2
       1  vancouver           10
       2   montreal           -5

## Aufgabe 9: apply
- a) Gib den quadrierten Preis für jeden Record aus `housing_df`, verwende dabei `np.square`.
- b) gebe jeder Stadt auf der `Column City` noch ein `U.S.` am Ende an
        - Schreibe eine funktion, welche das U.S anfügt

In [ ]:
housing_df = pd.DataFrame({'City': ['Denver', 'Los Angeles', 'Washington D.C', 'Los Angeles'], 
                           'Price' : [1500000, 1930000, 225000, 11000],
                           'Sqft' : [11000, 5400, 2200, 7000]})

0    2250000000000
1    3724900000000
2      50625000000
3        121000000
Name: Price, dtype: int64

                 City    Price   Sqft
0          Denver U.S  1500000  11000
1     Los Angeles U.S  1930000   5400
2  Washington D.C U.S   225000   2200
3     Los Angeles U.S    11000   7000

## Aufgabe 10: append
- Erstellen einer leeren Liste
- Hinzufügen von Elementen zur Liste Apfel, Banane und Orange
- Hinzufügen einer verschachtelten Liste [Erdbeere, Himbeere, Blaubeere]
- Hinzufügen eines dictionarys {"Name": "Maximilian", "Alter": 25, "Wohnort": "Berlin"}
- Die Liste mit allen Elementen ausgeben

['Apfel', 'Banane', 'Orange', ['Erdbeere', 'Himbeere', 'Blaubeere'], {'Name': 'Maximilian', 'Alter': 25, 'Wohnort': 'Berlin'}]

- gebe aus der Liste zwei zuzufälligen Wert raus

['Orange', ['Erdbeere', 'Himbeere', 'Blaubeere']]

## Aufgabe 11:
- a) setze die Column `first name` und `last name` als Index fest für den DataFrame `anwesenheitsliste`
- b) ändere in dem Dataframe `anwesenheitsliste` den Namen `Elon` zu `Jeffray` und setzte den gleichen Index wie aus a
- c) ändere in dem Dataframe `anwesenheitsliste` den Namen `Bill` zu `Jeffray` und setzte den gleichen Index wie aus a
<br><br>
Was sind die Unterschiede in den verschiedenen Index?

In [1]:
anwesenheitsliste_data_bse = {
    "first name":["Jeffray", "Elon", "Bill", "Richard"],
    "last name":["Bezos", "Musk", "Gates", "Branson"],
    "present":[True, False, False, False]
}

  first name last name  present
0    Jeffray     Bezos     True
1       Elon      Musk    False
2       Bill     Gates    False
3    Richard   Branson    False

                      present
first name last name
Jeffray    Bezos         True
Elon       Musk         False
Bill       Gates        False
Richard    Branson      False

                      present
first name last name
Jeffray    Bezos         True
Elon       Musk         False
Bill       Gates        False
Richard    Branson      False

## Aufgabe 12: to_datetime
- formatiere date1 = ['12-12-12', '11/11/11', '10.10.10'] mithilfe to_datetime in das jeweilige Datum um.
- Gegeben ist die Variable: `date2 = '23_04_28'` schreibe einen to_datetime Befehl, um das Datum der Präsentaion auszugeben
    - Tipp: benutze `format`   
- In dem Dataframe: `date3` soll die Spalte `date` mit dem Format `DD-Mon-YY` mit to_datetime in das Format `YYYY-MM-DD` ausgetauscht werden
    - Tipp: Das Format der abgekürzten Monatsnamen ist `%b`

In [6]:
date1 = ['12-12-12', '11/11/11', '10.10.10']

/var/folders/lg/p5y3283s2dv2b7qgn_d1dw0r0000gn/T/ipykernel_22940/3305957627.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(date1)

DatetimeIndex(['2012-12-12', '2011-11-11', '2010-10-10'], dtype='datetime64[ns]', freq=None)

Timestamp('2023-04-28 00:00:00')

   id       date      name
0   1 2022-03-28       Max
1   2 2022-04-02  Wolfgang
2   3 2022-04-09     Klaus

## Aufgabe 13:
- Erstelle das current_date und berechne aus date3 das Timedelta in `time_delta` aus `current_date` und `date`

Timestamp('2024-07-28 00:00:00')

   id       date      name time_delta
0   1 2022-03-28       Max  -853 days
1   2 2022-04-02  Wolfgang  -848 days
2   3 2022-04-09     Klaus  -841 days

## Aufgabe 14:
- bestimme aus list das gesamte timedelta (addiere die Werte)
- Ergebnis: 4 days 04:56:30

In [13]:
list = ['1 D 3 H 30 T 15 S', '2 D 5 H 10 T 45 S', '20 H 15 T 30 S']

4 days 04:56:30

## Aufgabe 15: between
- Wähle alle Zeilen aus, in denen die Spalte `Alter` `zwischen 18 und 25` liegt aus den Daten `names_and_ages`. Beide Werte sollen nicht mit ausgegeben werden
- Berechne in der neuen Column `Geburtsjahr` das Geburtsjahr aus

In [15]:
data = {'Namen':['Jannik', 'Max', 'Jonas', 'Leon', 'Celina', 'Ksenia', 'Rebecca', 'Marina', 'Melanie', 'Anna', 'Julius', 'Julia', 'Sonja', 'Eva'],
'Alter':[19, 23, 34, 16, 12, 23, 24, 25, 32, 18, 22, 24, 27, 25]} 
names_and_age = pd.DataFrame(data)

      Namen  Alter  GEBURTSJAHR
0    Jannik     19         2004
1       Max     23         2000
5    Ksenia     23         2000
6   Rebecca     24         1999
10   Julius     22         2001
11    Julia     24         1999

## Aufgabe 16: compare
- Sie haben zwei Datensammlungen vom Fertigungsbetrieb erhalten. Die Daten wurden von Maschinensensoren gelesen, jedoch wurde eine automaisch und die andere von einem Mitarbeiter erfasst. 
- ``Vergleiche die Datensätze`` (gebe die unterschiede der beiden Datensätz aus
- schätze den ``prozentualen`` Unterschied 5%.

In [20]:
data_sensor = pd.Series([79,60,18,65,79,75,64,63,87,48,51,59,1,33,70,20,67,50,41,39,6,34,68,76,38,91,97,54,34,
                         83,85,30,94,99, 97,80,62,13,60,46,68,59,4,29,40,10,15,41,51,60,23,24,37,71,14,38,98,
                         92,18,57,89,21,77,51,41,82,30,7,73,34,42,96,43,21,77,63,73,78,89,90,60,45,50,27,34,
                         32,26,42,18,24,21,32,59,12,49,62,25,81,14,12])
data_hand = pd.Series([79,13,18,65,79,75,64,63,87,48,51,59,1,33,70,20,67,50,41,39,6,34,68,76,38,91,97,54,34,
                       np.nan,85,30,94,99,97,80,62,13,'x',46,68,59,4,29,40,10,15,41,51,60,23,24,37,71,14,38,
                       98,92,18,57,89,21,77,'',41,82,30, 7,73,34,42,96,43,21,77,63,'o',78,89,90,60,45,50,27,34
                       ,32,26,42,18,24,21,32,59,12,49,62,25,81,14,np.nan])

   self  other
1    13   60.0
29  NaN   83.0
38    x   60.0
63        51.0
76    o   73.0
99  NaN   12.0

7.59493670886076

6.0

## Aufgabe 17: drop
- **kopiere** `tele_data` in jeweils ein neues tele_data_a
    - entferne von dem DataFrame tele_data die Column `AUFLADEZEIT`
    - entferne den `3 index`
``

   AKKULAUFZEIT  AUFLADEZEIT  VERKAUFTE_GERÄTE
0            12            2               300
1            24            3               500
2            16            1               200
4            12            1               150
5            30            2               400

   AKKULAUFZEIT  AUFLADEZEIT  VERKAUFTE_GERÄTE
0            12            2               300
2            16            1               200
3            20            2               200
4            12            1               150
5            30            2               400

## Aufgabe 18: drop_duplicates
- a) Lösche die Duplikate der Spalte `style` aus dem DataFrame und gebe den neuen DataFrame mit dem Namen `new_drop_duplicates` aus
- b)Lösche die Duplikate der Spalte `style und brand` aus dem DataFrame und gebe den neuen DataFrame mit dem Namen `new_drop_duplicates_2` aus
- c) Lösche die Duplikate der Spalte `brand` und `ersetze diese mit dem **letzten** Duplikat`. Die Änderung soll direkt im `new_drop_duplicates` vorgenommen und ohne den `alten` Zeilenindexe ausgegeben werden

In [ ]:
drop_dupli = pd.DataFrame({
    'brand': ['Barilla', 'Yum Yum', 'Yum Yum', 'De Cecco', 'De Cecco'], 
    'style': ['linguine', 'instant', 'instant', 'penne', 'linguine'],
    'price': [2.88, 0.59, 0.79, 2.56, 2.39]
})

      brand     style  price
0   Barilla  linguine   2.88
1   Yum Yum   instant   0.59
3  De Cecco     penne   2.56

      brand     style  price
0   Barilla  linguine   2.88
1   Yum Yum   instant   0.59
3  De Cecco     penne   2.56
4  De Cecco  linguine   2.39

      brand     style  price
0   Barilla  linguine   2.88
1   Yum Yum   instant   0.79
2  De Cecco  linguine   2.39

## Aufgabe 19: set_axis
- setze von new_drop_duplicates_2 einen neuen `Index als brand` und speichere es unter der Variable `new_drop_set_index`
- setze den row-Index aus `new_drop_set_index` auf `'aa', 'bb', 'cc', 'dd'`
- setze die Columns aus `new_drop_set_index` auf `'python', 'r'`

             style  price
brand
Barilla   linguine   2.88
Yum Yum    instant   0.59
De Cecco     penne   2.56
De Cecco  linguine   2.39

       style  price
aa  linguine   2.88
bb   instant   0.59
cc     penne   2.56
dd  linguine   2.39

            python     r
brand
Barilla   linguine  2.88
Yum Yum    instant  0.59
De Cecco     penne  2.56
De Cecco  linguine  2.39

## Aufgabe 20: sort_values
- sortiere den Dataframe `data_sort_values` einmal die Spalte `Alter` absteigend und den `Wohnort` aufsteigend

In [ ]:
data_sort = ({'Name': ['Kai', 'Alina', 'Marie', 'David', 'Isabell', 'Marco', 'Anja'],
         'Alter': [25, 21, 28, 35, 27, 32, 33],
         'Wohnort': ['Hamburg', 'Bremen', 'Münster', 'Frankfurt', 'Bremen', 'München', 'Frankfurt']})
data_sort_values = pd.DataFrame(data_sort)

1    21
0    25
4    27
2    28
5    32
6    33
3    35
Name: Alter, dtype: int64

      Name  Alter    Wohnort
3    David     35  Frankfurt
6     Anja     33  Frankfurt
5    Marco     32    München
2    Marie     28    Münster
4  Isabell     27     Bremen
0      Kai     25    Hamburg
1    Alina     21     Bremen

      Name  Alter    Wohnort
2    Marie     28    Münster
5    Marco     32    München
0      Kai     25    Hamburg
3    David     35  Frankfurt
6     Anja     33  Frankfurt
1    Alina     21     Bremen
4  Isabell     27     Bremen

## Aufgabe 21: where
- bestimme aus dem DataFrame `data_sort_values` alle Einträge die `grösser sind als 30` und lösche alle `NaN` Werte

    Name  Alter    Wohnort
3  David   35.0  Frankfurt
5  Marco   32.0    München
6   Anja   33.0  Frankfurt

## Aufgabe 21: count
-  Zähle wie oft jedes `Tier in der jeweiligen Farbe` vorkommt und gebe dies in `absteigender` Reihenfolge aus.
- Zähle wie oft jedes `Tier` in diesem DataFrame `data_animal` vorkommt und gebe dies in `aufsteigender` Reihenfolge aus.
- Zähle den `Prozentanteil` jeder `Farbe` mithilfe von subset.

In [ ]:
data_ani = {"tier":["Hase", "Eichhörnchen", "Pferd", "Huhn", "Huhn", "Hase", "Pferd", "Hase", "Hund", "Hase", "Hase", "Eichhörnchen", "Huhn"],
            "farbe":["braun", "orange", "weiß", "rot", "schwarz", "weiß" ,"braun", "braun", "orange", "weiß", "braun", "braun", "orange"]}
data_animal = pd.DataFrame(data_ani)

tier          farbe
Hase          braun      3
              weiß       2
Eichhörnchen  braun      1
              orange     1
Huhn          orange     1
              rot        1
              schwarz    1
Hund          orange     1
Pferd         braun      1
              weiß       1
Name: count, dtype: int64

tier
Hund            1
Eichhörnchen    2
Pferd           2
Huhn            3
Hase            5
Name: count, dtype: int64

farbe
braun      0.384615
orange     0.230769
weiß       0.230769
rot        0.076923
schwarz    0.076923
Name: proportion, dtype: float64

## Aufgabe 22:pivot
- Benutze die pivot Methode so, dass die id zum index wird aus dem DataFrame `pivot_bse`, die columns sollten aus haus-nr bestehen und der Rest soll zu den values werden. Gebe das neue DF aus.
- Gebe nun, ähnlich wie in der Präsentation, die Vornamen und Nachnamen aus, welche in der Hausnummer 55 wohnen.
- Reshape folgendes DF `users` so, dass weekday der index wird, city zu columns und die values nur die visitors sind. Gebe das neue DF aus.

In [ ]:
pivot_bse = pd.DataFrame({
    'strasse': ['Europastrasse', 'Europastrasse', 'Europastrasse', 'Hangstrasse','Hangstrasse', 'Hangstrasse', 'Amthausplatz',
    'Amthausplatz', 'Amthausplatz'] ,
    'vorname': ['Tom', 'Jim', 'Rainer', 'Bren', 'Bob', 'Ernst', 'Jo', 'Lee', 'Rob'],
    'nachname': ['Ate', 'Knopf', 'Zufall', 'Essel', 'Fahrer', 'Fall', 'Ghurt', 'Kor', 'Otter'],
    'haus-nr': [55, 3, 12, 44, 55, 21, 12, 3, 3], 
    'id': [0, 1, 2, 3,4,5, 6, 7, 8]}
)

users = pd.DataFrame(
    {"weekday": ['Sun','Sun','Mon','Mon'],
     "city": ["Loerrach", "Frankfurt", "Loerrach", "Frankfurt"],
     "visitors": [119, 207, 426, 412],
     "signups":  [7, 12, 3, 5]}
)

        vorname                           nachname
haus-nr      3       12     21    44   55       3       12    21     44
id
0           NaN     NaN    NaN   NaN  Tom      NaN     NaN   NaN    NaN  \
1           Jim     NaN    NaN   NaN  NaN    Knopf     NaN   NaN    NaN
2           NaN  Rainer    NaN   NaN  NaN      NaN  Zufall   NaN    NaN
3           NaN     NaN    NaN  Bren  NaN      NaN     NaN   NaN  Essel
4           NaN     NaN    NaN   NaN  Bob      NaN     NaN   NaN    NaN
5           NaN     NaN  Ernst   NaN  NaN      NaN     NaN  Fall    NaN
6           NaN      Jo    NaN   NaN  NaN      NaN   Ghurt   NaN    NaN
7           Lee     NaN    NaN   NaN  NaN      Kor     NaN   NaN    NaN
8           Rob     NaN    NaN   NaN  NaN    Otter     NaN   NaN    NaN

                       strasse
haus-nr      55             3              12           21           44
id
0           Ate            NaN            NaN          NaN          NaN  \
1           NaN  Europastrasse            NaN          NaN          NaN
2           NaN            NaN  Europastrasse          NaN          NaN
3           NaN            NaN            NaN          NaN  Hangstrasse
4        Fahrer            NaN            NaN          NaN          NaN
5           NaN            NaN            NaN  Hangstrasse          NaN
6           NaN            NaN   Amthausplatz          NaN          NaN
7           NaN   Amthausplatz            NaN          NaN          NaN
8           NaN   Amthausplatz            NaN          NaN          NaN


haus-nr             55
id
0        Europastrasse
1                  NaN
2                  NaN
3                  NaN
4          Hangstrasse
5                  NaN
6                  NaN
7                  NaN
8                  NaN

        vorname nachname
haus-nr      55       55
id
0           Tom      Ate
4           Bob   Fahrer

city     Frankfurt  Loerrach
weekday
Mon            412       426
Sun            207       119

## Aufgabe 23: pivot_table
- Implementiere ein `pivot_table` mit den persönlichen Abgaben und gebe an ob der Student bestanden hat (mittels ja/nein) und mit welcher Punktanzahl und schriebe die Ergebnisse in einen neuen DataFrame `my_table`

In [ ]:
df_pivo = pd.DataFrame({"Name": ["Jim","Tom","Lisa","Bill","Sabine","Gina","Timmy","Bernd"],
                   "Alter": [20,20,19,30,28,20,19,18],
                   "Geschlecht": ["m","m","w","m","w","w","m","m"],
                   "Bestanden":["ja","nein","ja","ja","nein","nein","ja","ja"],
                   "Punktzahl Python Prüfung":[56,45,76,87,33,45,65,98]})
df_pivo

                        Punktzahl Python Prüfung
Bestanden                                     ja  nein
Geschlecht Alter Name
m          18    Bernd                      98.0     -
           19    Timmy                      65.0     -
           20    Jim                        56.0     -
                 Tom                           -  45.0
           30    Bill                       87.0     -
w          19    Lisa                       76.0     -
           20    Gina                          -  45.0
           28    Sabine                        -  33.0

## Aufgabe 24: reset_index
- setze den Index aus dem DataFrame `my_table` zurück
- setze die Sub Index `Geshlecht und Alter` aus dem DataFrame `my_table` zurück

          Geschlecht Alter    Name Punktzahl Python Prüfung
Bestanden                                                ja  nein
0                  m    18   Bernd                     98.0     -
1                  m    19   Timmy                     65.0     -
2                  m    20     Jim                     56.0     -
3                  m    20     Tom                        -  45.0
4                  m    30    Bill                     87.0     -
5                  w    19    Lisa                     76.0     -
6                  w    20    Gina                        -  45.0
7                  w    28  Sabine                        -  33.0

          Geschlecht Alter Punktzahl Python Prüfung
Bestanden                                        ja  nein
Name
Bernd              m    18                     98.0     -
Timmy              m    19                     65.0     -
Jim                m    20                     56.0     -
Tom                m    20                        -  45.0
Bill               m    30                     87.0     -
Lisa               w    19                     76.0     -
Gina               w    20                        -  45.0
Sabine             w    28                        -  33.0

## Aufgabe 20: cut und qcut
- füge dem DataFrame `data_cut` eine neue column `age_1 und age_2` hinzu
- `age_1` soll die Daten bis einschliesslich 40 als 1 makieren und bis 80 als 2 und alle über 80 als 3
- `age_2` soll die Daten in vier gleiche Bereiche (oder nahezu 4 gleiche Bereiche) aufteilen

    age
0    17
1    13
2    26
3    40
4    46
..  ...
95   45
96   23
97   21
98   20
99   12

[100 rows x 1 columns]

    age new_1 new_2
0    17     1    50
1    13     1    25
2    26     1    75
3    40     1   100
4    46     2   100
..  ...   ...   ...
95   45     2   100
96   23     1    50
97   21     1    50
98   20     1    50
99   12     1    25

[100 rows x 3 columns]

new_2
25     27
100    25
50     24
75     24
Name: count, dtype: int64

    age new_1 new_2
43    1     1    25
41    2     1    25
9     2     1    25
46    2     1    25
36    2     1    25
90    3     1    25
60    3     1    25
33    4     1    25
52    4     1    25
44    4     1    25
58    4     1    25
17    5     1    25
21    6     1    25
50    7     1    25
45    8     1    25
35    8     1    25
30    8     1    25
15   10     1    25
56   10     1    25
23   11     1    25
39   11     1    25
99   12     1    25
20   12     1    25
8    12     1    25
70   13     1    25
93   13     1    25
1    13     1    25